# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

teamId: Optional[str]
"""
The DevZero team ID.
"""

token: Optional[str]
"""
The DevZero API token for authentication.
"""

url: str
"""
The DevZero API base URL. Defaults to https://dakr.devzero.dev
"""

