# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetClusterIdByNameResult',
    'AwaitableGetClusterIdByNameResult',
    'get_cluster_id_by_name',
    'get_cluster_id_by_name_output',
]

@pulumi.output_type
class GetClusterIdByNameResult:
    def __init__(__self__, cluster_id=None):
        if cluster_id and not isinstance(cluster_id, str):
            raise TypeError("Expected argument 'cluster_id' to be a str")
        pulumi.set(__self__, "cluster_id", cluster_id)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> _builtins.str:
        """
        The ID of the cluster matching the given team and name.
        """
        return pulumi.get(self, "cluster_id")


class AwaitableGetClusterIdByNameResult(GetClusterIdByNameResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetClusterIdByNameResult(
            cluster_id=self.cluster_id)


def get_cluster_id_by_name(cloud_provider: Optional[_builtins.str] = None,
                           liveness: Optional[_builtins.str] = None,
                           name: Optional[_builtins.str] = None,
                           region: Optional[_builtins.str] = None,
                           team_id: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetClusterIdByNameResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str cloud_provider: Optional cloud provider filter. One of: 'AWS', 'GCP', 'AKS', 'OCI'.
    :param _builtins.str liveness: Controls liveness filtering: IGNORE, PREFER_LIVE, or REQUIRE_LIVE.
    :param _builtins.str name: The cluster name to look up.
    :param _builtins.str region: Optional region filter, e.g. "us-east-1".
    :param _builtins.str team_id: The team ID to search within.
    """
    __args__ = dict()
    __args__['cloudProvider'] = cloud_provider
    __args__['liveness'] = liveness
    __args__['name'] = name
    __args__['region'] = region
    __args__['teamId'] = team_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('devzero:resources:getClusterIdByName', __args__, opts=opts, typ=GetClusterIdByNameResult).value

    return AwaitableGetClusterIdByNameResult(
        cluster_id=pulumi.get(__ret__, 'cluster_id'))
def get_cluster_id_by_name_output(cloud_provider: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                  liveness: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                  name: Optional[pulumi.Input[_builtins.str]] = None,
                                  region: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                  team_id: Optional[pulumi.Input[_builtins.str]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetClusterIdByNameResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str cloud_provider: Optional cloud provider filter. One of: 'AWS', 'GCP', 'AKS', 'OCI'.
    :param _builtins.str liveness: Controls liveness filtering: IGNORE, PREFER_LIVE, or REQUIRE_LIVE.
    :param _builtins.str name: The cluster name to look up.
    :param _builtins.str region: Optional region filter, e.g. "us-east-1".
    :param _builtins.str team_id: The team ID to search within.
    """
    __args__ = dict()
    __args__['cloudProvider'] = cloud_provider
    __args__['liveness'] = liveness
    __args__['name'] = name
    __args__['region'] = region
    __args__['teamId'] = team_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('devzero:resources:getClusterIdByName', __args__, opts=opts, typ=GetClusterIdByNameResult)
    return __ret__.apply(lambda __response__: GetClusterIdByNameResult(
        cluster_id=pulumi.get(__response__, 'cluster_id')))
