# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'AMISelectorTermArgs',
    'AWSNodeClassSpecArgs',
    'AzureKubeletConfigurationArgs',
    'AzureNodeClassSpecArgs',
    'BlockDeviceArgs',
    'BlockDeviceMappingArgs',
    'CapacityReservationSelectorTermArgs',
    'DisruptionBudgetArgs',
    'DisruptionPolicyArgs',
    'HorizontalScalingArgs',
    'KubeletConfigurationArgs',
    'LabelSelectorArgs',
    'LabelSelectorRequirementArgs',
    'MetadataOptionsArgs',
    'NamePatternArgs',
    'RawKarpenterSpecArgs',
    'ResourceLimitsArgs',
    'SecurityGroupSelectorTermArgs',
    'SubnetSelectorTermArgs',
    'TaintArgs',
    'VerticalScalingArgs',
]

@pulumi.output_type
class AMISelectorTermArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "ssmParameter":
            suggest = "ssm_parameter"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AMISelectorTermArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AMISelectorTermArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AMISelectorTermArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 alias: Optional[_builtins.str] = None,
                 id: Optional[_builtins.str] = None,
                 name: Optional[_builtins.str] = None,
                 owner: Optional[_builtins.str] = None,
                 ssm_parameter: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param _builtins.str alias: Well-known alias for the AMI family (e.g. 'al2@latest').
        :param _builtins.str id: Explicit AMI ID.
        :param _builtins.str name: AMI name filter (supports wildcards).
        :param _builtins.str owner: AWS account ID or alias that owns the AMI.
        :param _builtins.str ssm_parameter: SSM parameter path that stores the AMI ID.
        :param Mapping[str, _builtins.str] tags: Map of AWS tags used to select AMIs.
        """
        if alias is not None:
            pulumi.set(__self__, "alias", alias)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if owner is not None:
            pulumi.set(__self__, "owner", owner)
        if ssm_parameter is not None:
            pulumi.set(__self__, "ssm_parameter", ssm_parameter)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def alias(self) -> Optional[_builtins.str]:
        """
        Well-known alias for the AMI family (e.g. 'al2@latest').
        """
        return pulumi.get(self, "alias")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        Explicit AMI ID.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        AMI name filter (supports wildcards).
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def owner(self) -> Optional[_builtins.str]:
        """
        AWS account ID or alias that owns the AMI.
        """
        return pulumi.get(self, "owner")

    @_builtins.property
    @pulumi.getter(name="ssmParameter")
    def ssm_parameter(self) -> Optional[_builtins.str]:
        """
        SSM parameter path that stores the AMI ID.
        """
        return pulumi.get(self, "ssm_parameter")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Map of AWS tags used to select AMIs.
        """
        return pulumi.get(self, "tags")


@pulumi.output_type
class AWSNodeClassSpecArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "amiFamily":
            suggest = "ami_family"
        elif key == "amiSelectorTerms":
            suggest = "ami_selector_terms"
        elif key == "associatePublicIpAddress":
            suggest = "associate_public_ip_address"
        elif key == "blockDeviceMappings":
            suggest = "block_device_mappings"
        elif key == "capacityReservationSelectorTerms":
            suggest = "capacity_reservation_selector_terms"
        elif key == "detailedMonitoring":
            suggest = "detailed_monitoring"
        elif key == "instanceProfile":
            suggest = "instance_profile"
        elif key == "instanceStorePolicy":
            suggest = "instance_store_policy"
        elif key == "metadataOptions":
            suggest = "metadata_options"
        elif key == "securityGroupSelectorTerms":
            suggest = "security_group_selector_terms"
        elif key == "subnetSelectorTerms":
            suggest = "subnet_selector_terms"
        elif key == "userData":
            suggest = "user_data"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AWSNodeClassSpecArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AWSNodeClassSpecArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AWSNodeClassSpecArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 ami_family: Optional[_builtins.str] = None,
                 ami_selector_terms: Optional[Sequence['outputs.AMISelectorTermArgs']] = None,
                 associate_public_ip_address: Optional[_builtins.bool] = None,
                 block_device_mappings: Optional[Sequence['outputs.BlockDeviceMappingArgs']] = None,
                 capacity_reservation_selector_terms: Optional[Sequence['outputs.CapacityReservationSelectorTermArgs']] = None,
                 context: Optional[_builtins.str] = None,
                 detailed_monitoring: Optional[_builtins.bool] = None,
                 instance_profile: Optional[_builtins.str] = None,
                 instance_store_policy: Optional[_builtins.str] = None,
                 kubelet: Optional['outputs.KubeletConfigurationArgs'] = None,
                 metadata_options: Optional['outputs.MetadataOptionsArgs'] = None,
                 role: Optional[_builtins.str] = None,
                 security_group_selector_terms: Optional[Sequence['outputs.SecurityGroupSelectorTermArgs']] = None,
                 subnet_selector_terms: Optional[Sequence['outputs.SubnetSelectorTermArgs']] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None,
                 user_data: Optional[_builtins.str] = None):
        """
        :param _builtins.str ami_family: AMI family shorthand (e.g. 'AL2', 'Bottlerocket', 'Windows2022').
        :param Sequence['AMISelectorTermArgs'] ami_selector_terms: Selectors for the AMIs used to launch nodes.
        :param _builtins.bool associate_public_ip_address: Whether to assign a public IP address to provisioned nodes.
        :param Sequence['BlockDeviceMappingArgs'] block_device_mappings: EBS block device mappings for nodes.
        :param Sequence['CapacityReservationSelectorTermArgs'] capacity_reservation_selector_terms: Selectors for EC2 capacity reservations to prioritize.
        :param _builtins.str context: EC2 launch template context ARN.
        :param _builtins.bool detailed_monitoring: Enable detailed CloudWatch monitoring for instances.
        :param _builtins.str instance_profile: IAM instance profile name (use instead of Role when profile already exists).
        :param _builtins.str instance_store_policy: Policy for handling instance store volumes. One of: 'RAID0'.
        :param 'KubeletConfigurationArgs' kubelet: Kubelet configuration overrides for AWS nodes.
        :param 'MetadataOptionsArgs' metadata_options: EC2 instance metadata (IMDS) options.
        :param _builtins.str role: IAM role name assigned to nodes.
        :param Sequence['SecurityGroupSelectorTermArgs'] security_group_selector_terms: Selectors for security groups attached to nodes.
        :param Sequence['SubnetSelectorTermArgs'] subnet_selector_terms: Selectors for the subnets nodes will be launched into.
        :param Mapping[str, _builtins.str] tags: AWS tags applied to all resources created by this node class.
        :param _builtins.str user_data: Custom user data script injected into the node launch template.
        """
        if ami_family is not None:
            pulumi.set(__self__, "ami_family", ami_family)
        if ami_selector_terms is not None:
            pulumi.set(__self__, "ami_selector_terms", ami_selector_terms)
        if associate_public_ip_address is not None:
            pulumi.set(__self__, "associate_public_ip_address", associate_public_ip_address)
        if block_device_mappings is not None:
            pulumi.set(__self__, "block_device_mappings", block_device_mappings)
        if capacity_reservation_selector_terms is not None:
            pulumi.set(__self__, "capacity_reservation_selector_terms", capacity_reservation_selector_terms)
        if context is not None:
            pulumi.set(__self__, "context", context)
        if detailed_monitoring is not None:
            pulumi.set(__self__, "detailed_monitoring", detailed_monitoring)
        if instance_profile is not None:
            pulumi.set(__self__, "instance_profile", instance_profile)
        if instance_store_policy is not None:
            pulumi.set(__self__, "instance_store_policy", instance_store_policy)
        if kubelet is not None:
            pulumi.set(__self__, "kubelet", kubelet)
        if metadata_options is not None:
            pulumi.set(__self__, "metadata_options", metadata_options)
        if role is not None:
            pulumi.set(__self__, "role", role)
        if security_group_selector_terms is not None:
            pulumi.set(__self__, "security_group_selector_terms", security_group_selector_terms)
        if subnet_selector_terms is not None:
            pulumi.set(__self__, "subnet_selector_terms", subnet_selector_terms)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if user_data is not None:
            pulumi.set(__self__, "user_data", user_data)

    @_builtins.property
    @pulumi.getter(name="amiFamily")
    def ami_family(self) -> Optional[_builtins.str]:
        """
        AMI family shorthand (e.g. 'AL2', 'Bottlerocket', 'Windows2022').
        """
        return pulumi.get(self, "ami_family")

    @_builtins.property
    @pulumi.getter(name="amiSelectorTerms")
    def ami_selector_terms(self) -> Optional[Sequence['outputs.AMISelectorTermArgs']]:
        """
        Selectors for the AMIs used to launch nodes.
        """
        return pulumi.get(self, "ami_selector_terms")

    @_builtins.property
    @pulumi.getter(name="associatePublicIpAddress")
    def associate_public_ip_address(self) -> Optional[_builtins.bool]:
        """
        Whether to assign a public IP address to provisioned nodes.
        """
        return pulumi.get(self, "associate_public_ip_address")

    @_builtins.property
    @pulumi.getter(name="blockDeviceMappings")
    def block_device_mappings(self) -> Optional[Sequence['outputs.BlockDeviceMappingArgs']]:
        """
        EBS block device mappings for nodes.
        """
        return pulumi.get(self, "block_device_mappings")

    @_builtins.property
    @pulumi.getter(name="capacityReservationSelectorTerms")
    def capacity_reservation_selector_terms(self) -> Optional[Sequence['outputs.CapacityReservationSelectorTermArgs']]:
        """
        Selectors for EC2 capacity reservations to prioritize.
        """
        return pulumi.get(self, "capacity_reservation_selector_terms")

    @_builtins.property
    @pulumi.getter
    def context(self) -> Optional[_builtins.str]:
        """
        EC2 launch template context ARN.
        """
        return pulumi.get(self, "context")

    @_builtins.property
    @pulumi.getter(name="detailedMonitoring")
    def detailed_monitoring(self) -> Optional[_builtins.bool]:
        """
        Enable detailed CloudWatch monitoring for instances.
        """
        return pulumi.get(self, "detailed_monitoring")

    @_builtins.property
    @pulumi.getter(name="instanceProfile")
    def instance_profile(self) -> Optional[_builtins.str]:
        """
        IAM instance profile name (use instead of Role when profile already exists).
        """
        return pulumi.get(self, "instance_profile")

    @_builtins.property
    @pulumi.getter(name="instanceStorePolicy")
    def instance_store_policy(self) -> Optional[_builtins.str]:
        """
        Policy for handling instance store volumes. One of: 'RAID0'.
        """
        return pulumi.get(self, "instance_store_policy")

    @_builtins.property
    @pulumi.getter
    def kubelet(self) -> Optional['outputs.KubeletConfigurationArgs']:
        """
        Kubelet configuration overrides for AWS nodes.
        """
        return pulumi.get(self, "kubelet")

    @_builtins.property
    @pulumi.getter(name="metadataOptions")
    def metadata_options(self) -> Optional['outputs.MetadataOptionsArgs']:
        """
        EC2 instance metadata (IMDS) options.
        """
        return pulumi.get(self, "metadata_options")

    @_builtins.property
    @pulumi.getter
    def role(self) -> Optional[_builtins.str]:
        """
        IAM role name assigned to nodes.
        """
        return pulumi.get(self, "role")

    @_builtins.property
    @pulumi.getter(name="securityGroupSelectorTerms")
    def security_group_selector_terms(self) -> Optional[Sequence['outputs.SecurityGroupSelectorTermArgs']]:
        """
        Selectors for security groups attached to nodes.
        """
        return pulumi.get(self, "security_group_selector_terms")

    @_builtins.property
    @pulumi.getter(name="subnetSelectorTerms")
    def subnet_selector_terms(self) -> Optional[Sequence['outputs.SubnetSelectorTermArgs']]:
        """
        Selectors for the subnets nodes will be launched into.
        """
        return pulumi.get(self, "subnet_selector_terms")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        AWS tags applied to all resources created by this node class.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="userData")
    def user_data(self) -> Optional[_builtins.str]:
        """
        Custom user data script injected into the node launch template.
        """
        return pulumi.get(self, "user_data")


@pulumi.output_type
class AzureKubeletConfigurationArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "allowedUnsafeSysctls":
            suggest = "allowed_unsafe_sysctls"
        elif key == "containerLogMaxFiles":
            suggest = "container_log_max_files"
        elif key == "containerLogMaxSize":
            suggest = "container_log_max_size"
        elif key == "cpuCfsQuota":
            suggest = "cpu_cfs_quota"
        elif key == "cpuCfsQuotaPeriod":
            suggest = "cpu_cfs_quota_period"
        elif key == "cpuManagerPolicy":
            suggest = "cpu_manager_policy"
        elif key == "imageGcHighThresholdPercent":
            suggest = "image_gc_high_threshold_percent"
        elif key == "imageGcLowThresholdPercent":
            suggest = "image_gc_low_threshold_percent"
        elif key == "podPidsLimit":
            suggest = "pod_pids_limit"
        elif key == "topologyManagerPolicy":
            suggest = "topology_manager_policy"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AzureKubeletConfigurationArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AzureKubeletConfigurationArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AzureKubeletConfigurationArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 allowed_unsafe_sysctls: Optional[Sequence[_builtins.str]] = None,
                 container_log_max_files: Optional[_builtins.int] = None,
                 container_log_max_size: Optional[_builtins.str] = None,
                 cpu_cfs_quota: Optional[_builtins.bool] = None,
                 cpu_cfs_quota_period: Optional[_builtins.str] = None,
                 cpu_manager_policy: Optional[_builtins.str] = None,
                 image_gc_high_threshold_percent: Optional[_builtins.int] = None,
                 image_gc_low_threshold_percent: Optional[_builtins.int] = None,
                 pod_pids_limit: Optional[_builtins.int] = None,
                 topology_manager_policy: Optional[_builtins.str] = None):
        """
        :param Sequence[_builtins.str] allowed_unsafe_sysctls: Unsafe sysctl patterns that are allowed (e.g. 'net.ipv4.*').
        :param _builtins.int container_log_max_files: Maximum number of container log files to retain.
        :param _builtins.str container_log_max_size: Maximum container log file size before rotation (e.g. '10Mi').
        :param _builtins.bool cpu_cfs_quota: Whether to enforce CPU CFS quota for containers.
        :param _builtins.str cpu_cfs_quota_period: CPU CFS quota period (e.g. '100ms').
        :param _builtins.str cpu_manager_policy: CPU manager policy. One of: 'none', 'static'.
        :param _builtins.int image_gc_high_threshold_percent: Disk usage percentage triggering image GC.
        :param _builtins.int image_gc_low_threshold_percent: Disk usage percentage below which image GC stops.
        :param _builtins.int pod_pids_limit: Maximum number of process IDs per pod.
        :param _builtins.str topology_manager_policy: Topology manager policy for NUMA-aware scheduling.
        """
        if allowed_unsafe_sysctls is not None:
            pulumi.set(__self__, "allowed_unsafe_sysctls", allowed_unsafe_sysctls)
        if container_log_max_files is not None:
            pulumi.set(__self__, "container_log_max_files", container_log_max_files)
        if container_log_max_size is not None:
            pulumi.set(__self__, "container_log_max_size", container_log_max_size)
        if cpu_cfs_quota is not None:
            pulumi.set(__self__, "cpu_cfs_quota", cpu_cfs_quota)
        if cpu_cfs_quota_period is not None:
            pulumi.set(__self__, "cpu_cfs_quota_period", cpu_cfs_quota_period)
        if cpu_manager_policy is not None:
            pulumi.set(__self__, "cpu_manager_policy", cpu_manager_policy)
        if image_gc_high_threshold_percent is not None:
            pulumi.set(__self__, "image_gc_high_threshold_percent", image_gc_high_threshold_percent)
        if image_gc_low_threshold_percent is not None:
            pulumi.set(__self__, "image_gc_low_threshold_percent", image_gc_low_threshold_percent)
        if pod_pids_limit is not None:
            pulumi.set(__self__, "pod_pids_limit", pod_pids_limit)
        if topology_manager_policy is not None:
            pulumi.set(__self__, "topology_manager_policy", topology_manager_policy)

    @_builtins.property
    @pulumi.getter(name="allowedUnsafeSysctls")
    def allowed_unsafe_sysctls(self) -> Optional[Sequence[_builtins.str]]:
        """
        Unsafe sysctl patterns that are allowed (e.g. 'net.ipv4.*').
        """
        return pulumi.get(self, "allowed_unsafe_sysctls")

    @_builtins.property
    @pulumi.getter(name="containerLogMaxFiles")
    def container_log_max_files(self) -> Optional[_builtins.int]:
        """
        Maximum number of container log files to retain.
        """
        return pulumi.get(self, "container_log_max_files")

    @_builtins.property
    @pulumi.getter(name="containerLogMaxSize")
    def container_log_max_size(self) -> Optional[_builtins.str]:
        """
        Maximum container log file size before rotation (e.g. '10Mi').
        """
        return pulumi.get(self, "container_log_max_size")

    @_builtins.property
    @pulumi.getter(name="cpuCfsQuota")
    def cpu_cfs_quota(self) -> Optional[_builtins.bool]:
        """
        Whether to enforce CPU CFS quota for containers.
        """
        return pulumi.get(self, "cpu_cfs_quota")

    @_builtins.property
    @pulumi.getter(name="cpuCfsQuotaPeriod")
    def cpu_cfs_quota_period(self) -> Optional[_builtins.str]:
        """
        CPU CFS quota period (e.g. '100ms').
        """
        return pulumi.get(self, "cpu_cfs_quota_period")

    @_builtins.property
    @pulumi.getter(name="cpuManagerPolicy")
    def cpu_manager_policy(self) -> Optional[_builtins.str]:
        """
        CPU manager policy. One of: 'none', 'static'.
        """
        return pulumi.get(self, "cpu_manager_policy")

    @_builtins.property
    @pulumi.getter(name="imageGcHighThresholdPercent")
    def image_gc_high_threshold_percent(self) -> Optional[_builtins.int]:
        """
        Disk usage percentage triggering image GC.
        """
        return pulumi.get(self, "image_gc_high_threshold_percent")

    @_builtins.property
    @pulumi.getter(name="imageGcLowThresholdPercent")
    def image_gc_low_threshold_percent(self) -> Optional[_builtins.int]:
        """
        Disk usage percentage below which image GC stops.
        """
        return pulumi.get(self, "image_gc_low_threshold_percent")

    @_builtins.property
    @pulumi.getter(name="podPidsLimit")
    def pod_pids_limit(self) -> Optional[_builtins.int]:
        """
        Maximum number of process IDs per pod.
        """
        return pulumi.get(self, "pod_pids_limit")

    @_builtins.property
    @pulumi.getter(name="topologyManagerPolicy")
    def topology_manager_policy(self) -> Optional[_builtins.str]:
        """
        Topology manager policy for NUMA-aware scheduling.
        """
        return pulumi.get(self, "topology_manager_policy")


@pulumi.output_type
class AzureNodeClassSpecArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "fipsMode":
            suggest = "fips_mode"
        elif key == "imageFamily":
            suggest = "image_family"
        elif key == "maxPods":
            suggest = "max_pods"
        elif key == "osDiskSizeGb":
            suggest = "os_disk_size_gb"
        elif key == "vnetSubnetId":
            suggest = "vnet_subnet_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AzureNodeClassSpecArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AzureNodeClassSpecArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AzureNodeClassSpecArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 fips_mode: Optional[_builtins.str] = None,
                 image_family: Optional[_builtins.str] = None,
                 kubelet: Optional['outputs.AzureKubeletConfigurationArgs'] = None,
                 max_pods: Optional[_builtins.int] = None,
                 os_disk_size_gb: Optional[_builtins.int] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None,
                 vnet_subnet_id: Optional[_builtins.str] = None):
        """
        :param _builtins.str fips_mode: FIPS compliance mode. One of: 'Enabled', 'Disabled'.
        :param _builtins.str image_family: Azure node image family (e.g. 'AzureLinux', 'Ubuntu2204').
        :param 'AzureKubeletConfigurationArgs' kubelet: Kubelet configuration overrides for Azure nodes.
        :param _builtins.int max_pods: Maximum pods per node (overrides AKS default).
        :param _builtins.int os_disk_size_gb: OS disk size in GB.
        :param Mapping[str, _builtins.str] tags: Azure tags applied to all resources created by this node class.
        :param _builtins.str vnet_subnet_id: Azure VNet subnet resource ID for node networking.
        """
        if fips_mode is not None:
            pulumi.set(__self__, "fips_mode", fips_mode)
        if image_family is not None:
            pulumi.set(__self__, "image_family", image_family)
        if kubelet is not None:
            pulumi.set(__self__, "kubelet", kubelet)
        if max_pods is not None:
            pulumi.set(__self__, "max_pods", max_pods)
        if os_disk_size_gb is not None:
            pulumi.set(__self__, "os_disk_size_gb", os_disk_size_gb)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if vnet_subnet_id is not None:
            pulumi.set(__self__, "vnet_subnet_id", vnet_subnet_id)

    @_builtins.property
    @pulumi.getter(name="fipsMode")
    def fips_mode(self) -> Optional[_builtins.str]:
        """
        FIPS compliance mode. One of: 'Enabled', 'Disabled'.
        """
        return pulumi.get(self, "fips_mode")

    @_builtins.property
    @pulumi.getter(name="imageFamily")
    def image_family(self) -> Optional[_builtins.str]:
        """
        Azure node image family (e.g. 'AzureLinux', 'Ubuntu2204').
        """
        return pulumi.get(self, "image_family")

    @_builtins.property
    @pulumi.getter
    def kubelet(self) -> Optional['outputs.AzureKubeletConfigurationArgs']:
        """
        Kubelet configuration overrides for Azure nodes.
        """
        return pulumi.get(self, "kubelet")

    @_builtins.property
    @pulumi.getter(name="maxPods")
    def max_pods(self) -> Optional[_builtins.int]:
        """
        Maximum pods per node (overrides AKS default).
        """
        return pulumi.get(self, "max_pods")

    @_builtins.property
    @pulumi.getter(name="osDiskSizeGb")
    def os_disk_size_gb(self) -> Optional[_builtins.int]:
        """
        OS disk size in GB.
        """
        return pulumi.get(self, "os_disk_size_gb")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Azure tags applied to all resources created by this node class.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="vnetSubnetId")
    def vnet_subnet_id(self) -> Optional[_builtins.str]:
        """
        Azure VNet subnet resource ID for node networking.
        """
        return pulumi.get(self, "vnet_subnet_id")


@pulumi.output_type
class BlockDeviceArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "deleteOnTermination":
            suggest = "delete_on_termination"
        elif key == "kmsKeyId":
            suggest = "kms_key_id"
        elif key == "snapshotId":
            suggest = "snapshot_id"
        elif key == "volumeInitializationRate":
            suggest = "volume_initialization_rate"
        elif key == "volumeSize":
            suggest = "volume_size"
        elif key == "volumeType":
            suggest = "volume_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in BlockDeviceArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        BlockDeviceArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        BlockDeviceArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 delete_on_termination: Optional[_builtins.bool] = None,
                 encrypted: Optional[_builtins.bool] = None,
                 iops: Optional[_builtins.int] = None,
                 kms_key_id: Optional[_builtins.str] = None,
                 snapshot_id: Optional[_builtins.str] = None,
                 throughput: Optional[_builtins.int] = None,
                 volume_initialization_rate: Optional[_builtins.int] = None,
                 volume_size: Optional[_builtins.str] = None,
                 volume_type: Optional[_builtins.str] = None):
        """
        :param _builtins.bool delete_on_termination: Whether to delete the EBS volume when the instance terminates.
        :param _builtins.bool encrypted: Whether to encrypt the EBS volume.
        :param _builtins.int iops: IOPS to provision for io1/io2 volume types.
        :param _builtins.str kms_key_id: KMS key ID or ARN used to encrypt the volume.
        :param _builtins.str snapshot_id: EBS snapshot ID to restore the volume from.
        :param _builtins.int throughput: Throughput in MiB/s for gp3 volumes.
        :param _builtins.int volume_initialization_rate: Rate in MiB/s for initializing volumes from snapshots.
        :param _builtins.str volume_size: Volume size (e.g. '20Gi').
        :param _builtins.str volume_type: EBS volume type (e.g. 'gp3', 'io1', 'st1').
        """
        if delete_on_termination is not None:
            pulumi.set(__self__, "delete_on_termination", delete_on_termination)
        if encrypted is not None:
            pulumi.set(__self__, "encrypted", encrypted)
        if iops is not None:
            pulumi.set(__self__, "iops", iops)
        if kms_key_id is not None:
            pulumi.set(__self__, "kms_key_id", kms_key_id)
        if snapshot_id is not None:
            pulumi.set(__self__, "snapshot_id", snapshot_id)
        if throughput is not None:
            pulumi.set(__self__, "throughput", throughput)
        if volume_initialization_rate is not None:
            pulumi.set(__self__, "volume_initialization_rate", volume_initialization_rate)
        if volume_size is not None:
            pulumi.set(__self__, "volume_size", volume_size)
        if volume_type is not None:
            pulumi.set(__self__, "volume_type", volume_type)

    @_builtins.property
    @pulumi.getter(name="deleteOnTermination")
    def delete_on_termination(self) -> Optional[_builtins.bool]:
        """
        Whether to delete the EBS volume when the instance terminates.
        """
        return pulumi.get(self, "delete_on_termination")

    @_builtins.property
    @pulumi.getter
    def encrypted(self) -> Optional[_builtins.bool]:
        """
        Whether to encrypt the EBS volume.
        """
        return pulumi.get(self, "encrypted")

    @_builtins.property
    @pulumi.getter
    def iops(self) -> Optional[_builtins.int]:
        """
        IOPS to provision for io1/io2 volume types.
        """
        return pulumi.get(self, "iops")

    @_builtins.property
    @pulumi.getter(name="kmsKeyId")
    def kms_key_id(self) -> Optional[_builtins.str]:
        """
        KMS key ID or ARN used to encrypt the volume.
        """
        return pulumi.get(self, "kms_key_id")

    @_builtins.property
    @pulumi.getter(name="snapshotId")
    def snapshot_id(self) -> Optional[_builtins.str]:
        """
        EBS snapshot ID to restore the volume from.
        """
        return pulumi.get(self, "snapshot_id")

    @_builtins.property
    @pulumi.getter
    def throughput(self) -> Optional[_builtins.int]:
        """
        Throughput in MiB/s for gp3 volumes.
        """
        return pulumi.get(self, "throughput")

    @_builtins.property
    @pulumi.getter(name="volumeInitializationRate")
    def volume_initialization_rate(self) -> Optional[_builtins.int]:
        """
        Rate in MiB/s for initializing volumes from snapshots.
        """
        return pulumi.get(self, "volume_initialization_rate")

    @_builtins.property
    @pulumi.getter(name="volumeSize")
    def volume_size(self) -> Optional[_builtins.str]:
        """
        Volume size (e.g. '20Gi').
        """
        return pulumi.get(self, "volume_size")

    @_builtins.property
    @pulumi.getter(name="volumeType")
    def volume_type(self) -> Optional[_builtins.str]:
        """
        EBS volume type (e.g. 'gp3', 'io1', 'st1').
        """
        return pulumi.get(self, "volume_type")


@pulumi.output_type
class BlockDeviceMappingArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "deviceName":
            suggest = "device_name"
        elif key == "rootVolume":
            suggest = "root_volume"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in BlockDeviceMappingArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        BlockDeviceMappingArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        BlockDeviceMappingArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 device_name: Optional[_builtins.str] = None,
                 ebs: Optional['outputs.BlockDeviceArgs'] = None,
                 root_volume: Optional[_builtins.bool] = None):
        """
        :param _builtins.str device_name: Device name to map the volume to (e.g. '/dev/xvda').
        :param 'BlockDeviceArgs' ebs: EBS volume configuration for this device.
        :param _builtins.bool root_volume: Whether this mapping is for the root volume.
        """
        if device_name is not None:
            pulumi.set(__self__, "device_name", device_name)
        if ebs is not None:
            pulumi.set(__self__, "ebs", ebs)
        if root_volume is not None:
            pulumi.set(__self__, "root_volume", root_volume)

    @_builtins.property
    @pulumi.getter(name="deviceName")
    def device_name(self) -> Optional[_builtins.str]:
        """
        Device name to map the volume to (e.g. '/dev/xvda').
        """
        return pulumi.get(self, "device_name")

    @_builtins.property
    @pulumi.getter
    def ebs(self) -> Optional['outputs.BlockDeviceArgs']:
        """
        EBS volume configuration for this device.
        """
        return pulumi.get(self, "ebs")

    @_builtins.property
    @pulumi.getter(name="rootVolume")
    def root_volume(self) -> Optional[_builtins.bool]:
        """
        Whether this mapping is for the root volume.
        """
        return pulumi.get(self, "root_volume")


@pulumi.output_type
class CapacityReservationSelectorTermArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "ownerId":
            suggest = "owner_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in CapacityReservationSelectorTermArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        CapacityReservationSelectorTermArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        CapacityReservationSelectorTermArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 id: Optional[_builtins.str] = None,
                 owner_id: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param _builtins.str id: Explicit capacity reservation ID.
        :param _builtins.str owner_id: AWS account ID that owns the capacity reservation.
        :param Mapping[str, _builtins.str] tags: Map of AWS tags used to select capacity reservations.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if owner_id is not None:
            pulumi.set(__self__, "owner_id", owner_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        Explicit capacity reservation ID.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="ownerId")
    def owner_id(self) -> Optional[_builtins.str]:
        """
        AWS account ID that owns the capacity reservation.
        """
        return pulumi.get(self, "owner_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Map of AWS tags used to select capacity reservations.
        """
        return pulumi.get(self, "tags")


@pulumi.output_type
class DisruptionBudgetArgs(dict):
    def __init__(__self__, *,
                 duration: Optional[_builtins.str] = None,
                 nodes: Optional[_builtins.str] = None,
                 reasons: Optional[Sequence[_builtins.str]] = None,
                 schedule: Optional[_builtins.str] = None):
        """
        :param _builtins.str duration: Duration the budget window stays active (e.g. '1h', '30m').
        :param _builtins.str nodes: Maximum nodes that may be disrupted, as an absolute count or percentage (e.g. '10%').
        :param Sequence[_builtins.str] reasons: Disruption reasons this budget applies to (e.g. 'Underutilized', 'Empty', 'Drifted').
        :param _builtins.str schedule: Cron schedule during which this budget is active (5-field format).
        """
        if duration is not None:
            pulumi.set(__self__, "duration", duration)
        if nodes is not None:
            pulumi.set(__self__, "nodes", nodes)
        if reasons is not None:
            pulumi.set(__self__, "reasons", reasons)
        if schedule is not None:
            pulumi.set(__self__, "schedule", schedule)

    @_builtins.property
    @pulumi.getter
    def duration(self) -> Optional[_builtins.str]:
        """
        Duration the budget window stays active (e.g. '1h', '30m').
        """
        return pulumi.get(self, "duration")

    @_builtins.property
    @pulumi.getter
    def nodes(self) -> Optional[_builtins.str]:
        """
        Maximum nodes that may be disrupted, as an absolute count or percentage (e.g. '10%').
        """
        return pulumi.get(self, "nodes")

    @_builtins.property
    @pulumi.getter
    def reasons(self) -> Optional[Sequence[_builtins.str]]:
        """
        Disruption reasons this budget applies to (e.g. 'Underutilized', 'Empty', 'Drifted').
        """
        return pulumi.get(self, "reasons")

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> Optional[_builtins.str]:
        """
        Cron schedule during which this budget is active (5-field format).
        """
        return pulumi.get(self, "schedule")


@pulumi.output_type
class DisruptionPolicyArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "consolidateAfter":
            suggest = "consolidate_after"
        elif key == "consolidationPolicy":
            suggest = "consolidation_policy"
        elif key == "expireAfter":
            suggest = "expire_after"
        elif key == "terminationGracePeriodSeconds":
            suggest = "termination_grace_period_seconds"
        elif key == "ttlSecondsAfterEmpty":
            suggest = "ttl_seconds_after_empty"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in DisruptionPolicyArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        DisruptionPolicyArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        DisruptionPolicyArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 budgets: Optional[Sequence['outputs.DisruptionBudgetArgs']] = None,
                 consolidate_after: Optional[_builtins.str] = None,
                 consolidation_policy: Optional[_builtins.str] = None,
                 expire_after: Optional[_builtins.str] = None,
                 termination_grace_period_seconds: Optional[_builtins.int] = None,
                 ttl_seconds_after_empty: Optional[_builtins.int] = None):
        """
        :param Sequence['DisruptionBudgetArgs'] budgets: Disruption budgets limiting how many nodes can be disrupted at once.
        :param _builtins.str consolidate_after: Duration to wait after a node becomes empty before consolidating (e.g. '30s').
        :param _builtins.str consolidation_policy: When to consolidate nodes. One of: 'WhenEmpty', 'WhenUnderutilized'.
        :param _builtins.str expire_after: Duration after which provisioned nodes are replaced regardless of load (e.g. '720h').
        :param _builtins.int termination_grace_period_seconds: Grace period in seconds before forcefully terminating a draining node.
        :param _builtins.int ttl_seconds_after_empty: Seconds before an empty node is terminated (deprecated; prefer ConsolidateAfter).
        """
        if budgets is not None:
            pulumi.set(__self__, "budgets", budgets)
        if consolidate_after is not None:
            pulumi.set(__self__, "consolidate_after", consolidate_after)
        if consolidation_policy is not None:
            pulumi.set(__self__, "consolidation_policy", consolidation_policy)
        if expire_after is not None:
            pulumi.set(__self__, "expire_after", expire_after)
        if termination_grace_period_seconds is not None:
            pulumi.set(__self__, "termination_grace_period_seconds", termination_grace_period_seconds)
        if ttl_seconds_after_empty is not None:
            pulumi.set(__self__, "ttl_seconds_after_empty", ttl_seconds_after_empty)

    @_builtins.property
    @pulumi.getter
    def budgets(self) -> Optional[Sequence['outputs.DisruptionBudgetArgs']]:
        """
        Disruption budgets limiting how many nodes can be disrupted at once.
        """
        return pulumi.get(self, "budgets")

    @_builtins.property
    @pulumi.getter(name="consolidateAfter")
    def consolidate_after(self) -> Optional[_builtins.str]:
        """
        Duration to wait after a node becomes empty before consolidating (e.g. '30s').
        """
        return pulumi.get(self, "consolidate_after")

    @_builtins.property
    @pulumi.getter(name="consolidationPolicy")
    def consolidation_policy(self) -> Optional[_builtins.str]:
        """
        When to consolidate nodes. One of: 'WhenEmpty', 'WhenUnderutilized'.
        """
        return pulumi.get(self, "consolidation_policy")

    @_builtins.property
    @pulumi.getter(name="expireAfter")
    def expire_after(self) -> Optional[_builtins.str]:
        """
        Duration after which provisioned nodes are replaced regardless of load (e.g. '720h').
        """
        return pulumi.get(self, "expire_after")

    @_builtins.property
    @pulumi.getter(name="terminationGracePeriodSeconds")
    def termination_grace_period_seconds(self) -> Optional[_builtins.int]:
        """
        Grace period in seconds before forcefully terminating a draining node.
        """
        return pulumi.get(self, "termination_grace_period_seconds")

    @_builtins.property
    @pulumi.getter(name="ttlSecondsAfterEmpty")
    def ttl_seconds_after_empty(self) -> Optional[_builtins.int]:
        """
        Seconds before an empty node is terminated (deprecated; prefer ConsolidateAfter).
        """
        return pulumi.get(self, "ttl_seconds_after_empty")


@pulumi.output_type
class HorizontalScalingArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "maxReplicaChangePercent":
            suggest = "max_replica_change_percent"
        elif key == "maxReplicas":
            suggest = "max_replicas"
        elif key == "minDataPoints":
            suggest = "min_data_points"
        elif key == "minReplicas":
            suggest = "min_replicas"
        elif key == "primaryMetric":
            suggest = "primary_metric"
        elif key == "targetUtilization":
            suggest = "target_utilization"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in HorizontalScalingArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        HorizontalScalingArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        HorizontalScalingArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 enabled: Optional[_builtins.bool] = None,
                 max_replica_change_percent: Optional[_builtins.float] = None,
                 max_replicas: Optional[_builtins.int] = None,
                 min_data_points: Optional[_builtins.int] = None,
                 min_replicas: Optional[_builtins.int] = None,
                 primary_metric: Optional[_builtins.str] = None,
                 target_utilization: Optional[_builtins.float] = None):
        """
        :param _builtins.bool enabled: Enable horizontal (replica) scaling.
        :param _builtins.float max_replica_change_percent: Maximum percentage change in replica count per recommendation cycle.
        :param _builtins.int max_replicas: Maximum number of replicas to scale up to.
        :param _builtins.int min_data_points: Minimum data points required before a recommendation is emitted.
        :param _builtins.int min_replicas: Minimum number of replicas to maintain.
        :param _builtins.str primary_metric: Primary metric for HPA decisions. One of: 'cpu', 'memory', 'gpu', 'network_ingress', 'network_egress'.
        :param _builtins.float target_utilization: Target utilization ratio (0-1) for the primary metric.
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if max_replica_change_percent is not None:
            pulumi.set(__self__, "max_replica_change_percent", max_replica_change_percent)
        if max_replicas is not None:
            pulumi.set(__self__, "max_replicas", max_replicas)
        if min_data_points is not None:
            pulumi.set(__self__, "min_data_points", min_data_points)
        if min_replicas is not None:
            pulumi.set(__self__, "min_replicas", min_replicas)
        if primary_metric is not None:
            pulumi.set(__self__, "primary_metric", primary_metric)
        if target_utilization is not None:
            pulumi.set(__self__, "target_utilization", target_utilization)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        Enable horizontal (replica) scaling.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="maxReplicaChangePercent")
    def max_replica_change_percent(self) -> Optional[_builtins.float]:
        """
        Maximum percentage change in replica count per recommendation cycle.
        """
        return pulumi.get(self, "max_replica_change_percent")

    @_builtins.property
    @pulumi.getter(name="maxReplicas")
    def max_replicas(self) -> Optional[_builtins.int]:
        """
        Maximum number of replicas to scale up to.
        """
        return pulumi.get(self, "max_replicas")

    @_builtins.property
    @pulumi.getter(name="minDataPoints")
    def min_data_points(self) -> Optional[_builtins.int]:
        """
        Minimum data points required before a recommendation is emitted.
        """
        return pulumi.get(self, "min_data_points")

    @_builtins.property
    @pulumi.getter(name="minReplicas")
    def min_replicas(self) -> Optional[_builtins.int]:
        """
        Minimum number of replicas to maintain.
        """
        return pulumi.get(self, "min_replicas")

    @_builtins.property
    @pulumi.getter(name="primaryMetric")
    def primary_metric(self) -> Optional[_builtins.str]:
        """
        Primary metric for HPA decisions. One of: 'cpu', 'memory', 'gpu', 'network_ingress', 'network_egress'.
        """
        return pulumi.get(self, "primary_metric")

    @_builtins.property
    @pulumi.getter(name="targetUtilization")
    def target_utilization(self) -> Optional[_builtins.float]:
        """
        Target utilization ratio (0-1) for the primary metric.
        """
        return pulumi.get(self, "target_utilization")


@pulumi.output_type
class KubeletConfigurationArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "clusterDns":
            suggest = "cluster_dns"
        elif key == "cpuCfsQuota":
            suggest = "cpu_cfs_quota"
        elif key == "evictionHard":
            suggest = "eviction_hard"
        elif key == "evictionMaxPodGracePeriod":
            suggest = "eviction_max_pod_grace_period"
        elif key == "evictionSoft":
            suggest = "eviction_soft"
        elif key == "evictionSoftGracePeriod":
            suggest = "eviction_soft_grace_period"
        elif key == "imageGcHighThresholdPercent":
            suggest = "image_gc_high_threshold_percent"
        elif key == "imageGcLowThresholdPercent":
            suggest = "image_gc_low_threshold_percent"
        elif key == "kubeReserved":
            suggest = "kube_reserved"
        elif key == "maxPods":
            suggest = "max_pods"
        elif key == "podsPerCore":
            suggest = "pods_per_core"
        elif key == "systemReserved":
            suggest = "system_reserved"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in KubeletConfigurationArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        KubeletConfigurationArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        KubeletConfigurationArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 cluster_dns: Optional[Sequence[_builtins.str]] = None,
                 cpu_cfs_quota: Optional[_builtins.bool] = None,
                 eviction_hard: Optional[Mapping[str, _builtins.str]] = None,
                 eviction_max_pod_grace_period: Optional[_builtins.int] = None,
                 eviction_soft: Optional[Mapping[str, _builtins.str]] = None,
                 eviction_soft_grace_period: Optional[Mapping[str, _builtins.str]] = None,
                 image_gc_high_threshold_percent: Optional[_builtins.int] = None,
                 image_gc_low_threshold_percent: Optional[_builtins.int] = None,
                 kube_reserved: Optional[Mapping[str, _builtins.str]] = None,
                 max_pods: Optional[_builtins.int] = None,
                 pods_per_core: Optional[_builtins.int] = None,
                 system_reserved: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param Sequence[_builtins.str] cluster_dns: List of DNS server IP addresses used by kubelet.
        :param _builtins.bool cpu_cfs_quota: Whether to enforce CPU CFS quota limits for containers.
        :param Mapping[str, _builtins.str] eviction_hard: Hard eviction thresholds that trigger immediate pod eviction.
        :param _builtins.int eviction_max_pod_grace_period: Maximum grace period in seconds when evicting pods.
        :param Mapping[str, _builtins.str] eviction_soft: Soft eviction thresholds that trigger eviction after a grace period.
        :param Mapping[str, _builtins.str] eviction_soft_grace_period: Grace period for each soft eviction threshold.
        :param _builtins.int image_gc_high_threshold_percent: Disk usage percentage that triggers image garbage collection.
        :param _builtins.int image_gc_low_threshold_percent: Disk usage percentage below which image GC stops freeing space.
        :param Mapping[str, _builtins.str] kube_reserved: Resources reserved for Kubernetes system components.
        :param _builtins.int max_pods: Maximum number of pods per node.
        :param _builtins.int pods_per_core: Maximum pods per CPU core (multiplied by core count for max pods).
        :param Mapping[str, _builtins.str] system_reserved: Resources reserved for OS system daemons (e.g. {'cpu': '100m'}).
        """
        if cluster_dns is not None:
            pulumi.set(__self__, "cluster_dns", cluster_dns)
        if cpu_cfs_quota is not None:
            pulumi.set(__self__, "cpu_cfs_quota", cpu_cfs_quota)
        if eviction_hard is not None:
            pulumi.set(__self__, "eviction_hard", eviction_hard)
        if eviction_max_pod_grace_period is not None:
            pulumi.set(__self__, "eviction_max_pod_grace_period", eviction_max_pod_grace_period)
        if eviction_soft is not None:
            pulumi.set(__self__, "eviction_soft", eviction_soft)
        if eviction_soft_grace_period is not None:
            pulumi.set(__self__, "eviction_soft_grace_period", eviction_soft_grace_period)
        if image_gc_high_threshold_percent is not None:
            pulumi.set(__self__, "image_gc_high_threshold_percent", image_gc_high_threshold_percent)
        if image_gc_low_threshold_percent is not None:
            pulumi.set(__self__, "image_gc_low_threshold_percent", image_gc_low_threshold_percent)
        if kube_reserved is not None:
            pulumi.set(__self__, "kube_reserved", kube_reserved)
        if max_pods is not None:
            pulumi.set(__self__, "max_pods", max_pods)
        if pods_per_core is not None:
            pulumi.set(__self__, "pods_per_core", pods_per_core)
        if system_reserved is not None:
            pulumi.set(__self__, "system_reserved", system_reserved)

    @_builtins.property
    @pulumi.getter(name="clusterDns")
    def cluster_dns(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of DNS server IP addresses used by kubelet.
        """
        return pulumi.get(self, "cluster_dns")

    @_builtins.property
    @pulumi.getter(name="cpuCfsQuota")
    def cpu_cfs_quota(self) -> Optional[_builtins.bool]:
        """
        Whether to enforce CPU CFS quota limits for containers.
        """
        return pulumi.get(self, "cpu_cfs_quota")

    @_builtins.property
    @pulumi.getter(name="evictionHard")
    def eviction_hard(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Hard eviction thresholds that trigger immediate pod eviction.
        """
        return pulumi.get(self, "eviction_hard")

    @_builtins.property
    @pulumi.getter(name="evictionMaxPodGracePeriod")
    def eviction_max_pod_grace_period(self) -> Optional[_builtins.int]:
        """
        Maximum grace period in seconds when evicting pods.
        """
        return pulumi.get(self, "eviction_max_pod_grace_period")

    @_builtins.property
    @pulumi.getter(name="evictionSoft")
    def eviction_soft(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Soft eviction thresholds that trigger eviction after a grace period.
        """
        return pulumi.get(self, "eviction_soft")

    @_builtins.property
    @pulumi.getter(name="evictionSoftGracePeriod")
    def eviction_soft_grace_period(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Grace period for each soft eviction threshold.
        """
        return pulumi.get(self, "eviction_soft_grace_period")

    @_builtins.property
    @pulumi.getter(name="imageGcHighThresholdPercent")
    def image_gc_high_threshold_percent(self) -> Optional[_builtins.int]:
        """
        Disk usage percentage that triggers image garbage collection.
        """
        return pulumi.get(self, "image_gc_high_threshold_percent")

    @_builtins.property
    @pulumi.getter(name="imageGcLowThresholdPercent")
    def image_gc_low_threshold_percent(self) -> Optional[_builtins.int]:
        """
        Disk usage percentage below which image GC stops freeing space.
        """
        return pulumi.get(self, "image_gc_low_threshold_percent")

    @_builtins.property
    @pulumi.getter(name="kubeReserved")
    def kube_reserved(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Resources reserved for Kubernetes system components.
        """
        return pulumi.get(self, "kube_reserved")

    @_builtins.property
    @pulumi.getter(name="maxPods")
    def max_pods(self) -> Optional[_builtins.int]:
        """
        Maximum number of pods per node.
        """
        return pulumi.get(self, "max_pods")

    @_builtins.property
    @pulumi.getter(name="podsPerCore")
    def pods_per_core(self) -> Optional[_builtins.int]:
        """
        Maximum pods per CPU core (multiplied by core count for max pods).
        """
        return pulumi.get(self, "pods_per_core")

    @_builtins.property
    @pulumi.getter(name="systemReserved")
    def system_reserved(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Resources reserved for OS system daemons (e.g. {'cpu': '100m'}).
        """
        return pulumi.get(self, "system_reserved")


@pulumi.output_type
class LabelSelectorArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "matchExpressions":
            suggest = "match_expressions"
        elif key == "matchLabels":
            suggest = "match_labels"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in LabelSelectorArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        LabelSelectorArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        LabelSelectorArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 match_expressions: Optional[Sequence['outputs.LabelSelectorRequirementArgs']] = None,
                 match_labels: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param Sequence['LabelSelectorRequirementArgs'] match_expressions: List of label selector requirements joined by AND.
        :param Mapping[str, _builtins.str] match_labels: Map of label key-value pairs that must all match exactly.
        """
        if match_expressions is not None:
            pulumi.set(__self__, "match_expressions", match_expressions)
        if match_labels is not None:
            pulumi.set(__self__, "match_labels", match_labels)

    @_builtins.property
    @pulumi.getter(name="matchExpressions")
    def match_expressions(self) -> Optional[Sequence['outputs.LabelSelectorRequirementArgs']]:
        """
        List of label selector requirements joined by AND.
        """
        return pulumi.get(self, "match_expressions")

    @_builtins.property
    @pulumi.getter(name="matchLabels")
    def match_labels(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Map of label key-value pairs that must all match exactly.
        """
        return pulumi.get(self, "match_labels")


@pulumi.output_type
class LabelSelectorRequirementArgs(dict):
    def __init__(__self__, *,
                 key: Optional[_builtins.str] = None,
                 operator: Optional[_builtins.str] = None,
                 values: Optional[Sequence[_builtins.str]] = None):
        """
        :param _builtins.str key: The label key that the selector applies to.
        :param _builtins.str operator: Operator relating the key and values. One of: 'In', 'NotIn', 'Exists', 'DoesNotExist'.
        :param Sequence[_builtins.str] values: Array of string values. Required for 'In' and 'NotIn' operators.
        """
        if key is not None:
            pulumi.set(__self__, "key", key)
        if operator is not None:
            pulumi.set(__self__, "operator", operator)
        if values is not None:
            pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[_builtins.str]:
        """
        The label key that the selector applies to.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def operator(self) -> Optional[_builtins.str]:
        """
        Operator relating the key and values. One of: 'In', 'NotIn', 'Exists', 'DoesNotExist'.
        """
        return pulumi.get(self, "operator")

    @_builtins.property
    @pulumi.getter
    def values(self) -> Optional[Sequence[_builtins.str]]:
        """
        Array of string values. Required for 'In' and 'NotIn' operators.
        """
        return pulumi.get(self, "values")


@pulumi.output_type
class MetadataOptionsArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "httpEndpoint":
            suggest = "http_endpoint"
        elif key == "httpProtocolIpv6":
            suggest = "http_protocol_ipv6"
        elif key == "httpPutResponseHopLimit":
            suggest = "http_put_response_hop_limit"
        elif key == "httpTokens":
            suggest = "http_tokens"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in MetadataOptionsArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        MetadataOptionsArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        MetadataOptionsArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 http_endpoint: Optional[_builtins.str] = None,
                 http_protocol_ipv6: Optional[_builtins.str] = None,
                 http_put_response_hop_limit: Optional[_builtins.int] = None,
                 http_tokens: Optional[_builtins.str] = None):
        """
        :param _builtins.str http_endpoint: Enable or disable the instance metadata endpoint. One of: 'enabled', 'disabled'.
        :param _builtins.str http_protocol_ipv6: Enable IPv6 for the metadata endpoint. One of: 'enabled', 'disabled'.
        :param _builtins.int http_put_response_hop_limit: HTTP PUT response hop limit for metadata requests (1-64).
        :param _builtins.str http_tokens: Whether to require IMDSv2 tokens. One of: 'optional', 'required'.
        """
        if http_endpoint is not None:
            pulumi.set(__self__, "http_endpoint", http_endpoint)
        if http_protocol_ipv6 is not None:
            pulumi.set(__self__, "http_protocol_ipv6", http_protocol_ipv6)
        if http_put_response_hop_limit is not None:
            pulumi.set(__self__, "http_put_response_hop_limit", http_put_response_hop_limit)
        if http_tokens is not None:
            pulumi.set(__self__, "http_tokens", http_tokens)

    @_builtins.property
    @pulumi.getter(name="httpEndpoint")
    def http_endpoint(self) -> Optional[_builtins.str]:
        """
        Enable or disable the instance metadata endpoint. One of: 'enabled', 'disabled'.
        """
        return pulumi.get(self, "http_endpoint")

    @_builtins.property
    @pulumi.getter(name="httpProtocolIpv6")
    def http_protocol_ipv6(self) -> Optional[_builtins.str]:
        """
        Enable IPv6 for the metadata endpoint. One of: 'enabled', 'disabled'.
        """
        return pulumi.get(self, "http_protocol_ipv6")

    @_builtins.property
    @pulumi.getter(name="httpPutResponseHopLimit")
    def http_put_response_hop_limit(self) -> Optional[_builtins.int]:
        """
        HTTP PUT response hop limit for metadata requests (1-64).
        """
        return pulumi.get(self, "http_put_response_hop_limit")

    @_builtins.property
    @pulumi.getter(name="httpTokens")
    def http_tokens(self) -> Optional[_builtins.str]:
        """
        Whether to require IMDSv2 tokens. One of: 'optional', 'required'.
        """
        return pulumi.get(self, "http_tokens")


@pulumi.output_type
class NamePatternArgs(dict):
    def __init__(__self__, *,
                 flags: Optional[_builtins.str] = None,
                 pattern: Optional[_builtins.str] = None):
        """
        :param _builtins.str flags: Optional regex flags (e.g. 'i' for case-insensitive).
        :param _builtins.str pattern: Regular expression pattern to match workload names.
        """
        if flags is not None:
            pulumi.set(__self__, "flags", flags)
        if pattern is not None:
            pulumi.set(__self__, "pattern", pattern)

    @_builtins.property
    @pulumi.getter
    def flags(self) -> Optional[_builtins.str]:
        """
        Optional regex flags (e.g. 'i' for case-insensitive).
        """
        return pulumi.get(self, "flags")

    @_builtins.property
    @pulumi.getter
    def pattern(self) -> Optional[_builtins.str]:
        """
        Regular expression pattern to match workload names.
        """
        return pulumi.get(self, "pattern")


@pulumi.output_type
class RawKarpenterSpecArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "nodeclassYaml":
            suggest = "nodeclass_yaml"
        elif key == "nodepoolYaml":
            suggest = "nodepool_yaml"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RawKarpenterSpecArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RawKarpenterSpecArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RawKarpenterSpecArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 nodeclass_yaml: Optional[_builtins.str] = None,
                 nodepool_yaml: Optional[_builtins.str] = None):
        """
        :param _builtins.str nodeclass_yaml: Raw YAML for a complete Karpenter NodeClass resource (escape hatch).
        :param _builtins.str nodepool_yaml: Raw YAML for a complete Karpenter NodePool resource (escape hatch).
        """
        if nodeclass_yaml is not None:
            pulumi.set(__self__, "nodeclass_yaml", nodeclass_yaml)
        if nodepool_yaml is not None:
            pulumi.set(__self__, "nodepool_yaml", nodepool_yaml)

    @_builtins.property
    @pulumi.getter(name="nodeclassYaml")
    def nodeclass_yaml(self) -> Optional[_builtins.str]:
        """
        Raw YAML for a complete Karpenter NodeClass resource (escape hatch).
        """
        return pulumi.get(self, "nodeclass_yaml")

    @_builtins.property
    @pulumi.getter(name="nodepoolYaml")
    def nodepool_yaml(self) -> Optional[_builtins.str]:
        """
        Raw YAML for a complete Karpenter NodePool resource (escape hatch).
        """
        return pulumi.get(self, "nodepool_yaml")


@pulumi.output_type
class ResourceLimitsArgs(dict):
    def __init__(__self__, *,
                 cpu: Optional[_builtins.str] = None,
                 memory: Optional[_builtins.str] = None):
        """
        :param _builtins.str cpu: Maximum total CPU that may be provisioned (e.g. '1000' for 1000 vCPUs).
        :param _builtins.str memory: Maximum total memory that may be provisioned (e.g. '1000Gi').
        """
        if cpu is not None:
            pulumi.set(__self__, "cpu", cpu)
        if memory is not None:
            pulumi.set(__self__, "memory", memory)

    @_builtins.property
    @pulumi.getter
    def cpu(self) -> Optional[_builtins.str]:
        """
        Maximum total CPU that may be provisioned (e.g. '1000' for 1000 vCPUs).
        """
        return pulumi.get(self, "cpu")

    @_builtins.property
    @pulumi.getter
    def memory(self) -> Optional[_builtins.str]:
        """
        Maximum total memory that may be provisioned (e.g. '1000Gi').
        """
        return pulumi.get(self, "memory")


@pulumi.output_type
class SecurityGroupSelectorTermArgs(dict):
    def __init__(__self__, *,
                 id: Optional[_builtins.str] = None,
                 name: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param _builtins.str id: Explicit AWS security group ID.
        :param _builtins.str name: Security group name filter.
        :param Mapping[str, _builtins.str] tags: Map of AWS tags used to select security groups.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        Explicit AWS security group ID.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        Security group name filter.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Map of AWS tags used to select security groups.
        """
        return pulumi.get(self, "tags")


@pulumi.output_type
class SubnetSelectorTermArgs(dict):
    def __init__(__self__, *,
                 id: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param _builtins.str id: Explicit AWS subnet ID.
        :param Mapping[str, _builtins.str] tags: Map of AWS tags used to select subnets.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        Explicit AWS subnet ID.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Map of AWS tags used to select subnets.
        """
        return pulumi.get(self, "tags")


@pulumi.output_type
class TaintArgs(dict):
    def __init__(__self__, *,
                 effect: _builtins.str,
                 key: _builtins.str,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.str effect: Taint effect. One of: 'NoSchedule', 'PreferNoSchedule', 'NoExecute'.
        :param _builtins.str key: Taint key to apply to provisioned nodes.
        :param _builtins.str value: Taint value associated with the key.
        """
        pulumi.set(__self__, "effect", effect)
        pulumi.set(__self__, "key", key)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def effect(self) -> _builtins.str:
        """
        Taint effect. One of: 'NoSchedule', 'PreferNoSchedule', 'NoExecute'.
        """
        return pulumi.get(self, "effect")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        """
        Taint key to apply to provisioned nodes.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        Taint value associated with the key.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class VerticalScalingArgs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "adjustReqEvenIfNotSet":
            suggest = "adjust_req_even_if_not_set"
        elif key == "limitMultiplier":
            suggest = "limit_multiplier"
        elif key == "limitsAdjustmentEnabled":
            suggest = "limits_adjustment_enabled"
        elif key == "limitsRemovalEnabled":
            suggest = "limits_removal_enabled"
        elif key == "maxRequest":
            suggest = "max_request"
        elif key == "maxScaleDownPercent":
            suggest = "max_scale_down_percent"
        elif key == "maxScaleUpPercent":
            suggest = "max_scale_up_percent"
        elif key == "minDataPoints":
            suggest = "min_data_points"
        elif key == "minRequest":
            suggest = "min_request"
        elif key == "overheadMultiplier":
            suggest = "overhead_multiplier"
        elif key == "targetPercentile":
            suggest = "target_percentile"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in VerticalScalingArgs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        VerticalScalingArgs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        VerticalScalingArgs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 adjust_req_even_if_not_set: Optional[_builtins.bool] = None,
                 enabled: Optional[_builtins.bool] = None,
                 limit_multiplier: Optional[_builtins.float] = None,
                 limits_adjustment_enabled: Optional[_builtins.bool] = None,
                 limits_removal_enabled: Optional[_builtins.bool] = None,
                 max_request: Optional[_builtins.int] = None,
                 max_scale_down_percent: Optional[_builtins.float] = None,
                 max_scale_up_percent: Optional[_builtins.float] = None,
                 min_data_points: Optional[_builtins.int] = None,
                 min_request: Optional[_builtins.int] = None,
                 overhead_multiplier: Optional[_builtins.float] = None,
                 target_percentile: Optional[_builtins.float] = None):
        """
        :param _builtins.bool adjust_req_even_if_not_set: Recommend requests even when the workload has no existing requests set. Server/web default: true.
        :param _builtins.bool enabled: Enable vertical scaling for this resource type.
        :param _builtins.float limit_multiplier: Multiplier applied to the request to derive the resource limit.
        :param _builtins.bool limits_adjustment_enabled: Whether to also adjust resource limits alongside requests.
        :param _builtins.bool limits_removal_enabled: Actively remove limits from workloads (CPU only). Takes precedence over limitsAdjustmentEnabled. Web default: true for CPU, false for Memory.
        :param _builtins.int max_request: Maximum resource request in millicores (CPU) or bytes (memory/GPU).
        :param _builtins.float max_scale_down_percent: Maximum percentage decrease allowed in a single recommendation cycle.
        :param _builtins.float max_scale_up_percent: Maximum percentage increase allowed in a single recommendation cycle.
        :param _builtins.int min_data_points: Minimum number of data points required before a recommendation is emitted.
        :param _builtins.int min_request: Minimum resource request in millicores (CPU) or bytes (memory/GPU).
        :param _builtins.float overhead_multiplier: Multiplier applied on top of the recommendation to add headroom.
        :param _builtins.float target_percentile: Percentile of usage data used as the recommendation target (e.g. 0.95).
        """
        if adjust_req_even_if_not_set is not None:
            pulumi.set(__self__, "adjust_req_even_if_not_set", adjust_req_even_if_not_set)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if limit_multiplier is not None:
            pulumi.set(__self__, "limit_multiplier", limit_multiplier)
        if limits_adjustment_enabled is not None:
            pulumi.set(__self__, "limits_adjustment_enabled", limits_adjustment_enabled)
        if limits_removal_enabled is not None:
            pulumi.set(__self__, "limits_removal_enabled", limits_removal_enabled)
        if max_request is not None:
            pulumi.set(__self__, "max_request", max_request)
        if max_scale_down_percent is None:
            max_scale_down_percent = 1
        if max_scale_down_percent is not None:
            pulumi.set(__self__, "max_scale_down_percent", max_scale_down_percent)
        if max_scale_up_percent is None:
            max_scale_up_percent = 1000
        if max_scale_up_percent is not None:
            pulumi.set(__self__, "max_scale_up_percent", max_scale_up_percent)
        if min_data_points is None:
            min_data_points = 20
        if min_data_points is not None:
            pulumi.set(__self__, "min_data_points", min_data_points)
        if min_request is not None:
            pulumi.set(__self__, "min_request", min_request)
        if overhead_multiplier is not None:
            pulumi.set(__self__, "overhead_multiplier", overhead_multiplier)
        if target_percentile is not None:
            pulumi.set(__self__, "target_percentile", target_percentile)

    @_builtins.property
    @pulumi.getter(name="adjustReqEvenIfNotSet")
    def adjust_req_even_if_not_set(self) -> Optional[_builtins.bool]:
        """
        Recommend requests even when the workload has no existing requests set. Server/web default: true.
        """
        return pulumi.get(self, "adjust_req_even_if_not_set")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        Enable vertical scaling for this resource type.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="limitMultiplier")
    def limit_multiplier(self) -> Optional[_builtins.float]:
        """
        Multiplier applied to the request to derive the resource limit.
        """
        return pulumi.get(self, "limit_multiplier")

    @_builtins.property
    @pulumi.getter(name="limitsAdjustmentEnabled")
    def limits_adjustment_enabled(self) -> Optional[_builtins.bool]:
        """
        Whether to also adjust resource limits alongside requests.
        """
        return pulumi.get(self, "limits_adjustment_enabled")

    @_builtins.property
    @pulumi.getter(name="limitsRemovalEnabled")
    def limits_removal_enabled(self) -> Optional[_builtins.bool]:
        """
        Actively remove limits from workloads (CPU only). Takes precedence over limitsAdjustmentEnabled. Web default: true for CPU, false for Memory.
        """
        return pulumi.get(self, "limits_removal_enabled")

    @_builtins.property
    @pulumi.getter(name="maxRequest")
    def max_request(self) -> Optional[_builtins.int]:
        """
        Maximum resource request in millicores (CPU) or bytes (memory/GPU).
        """
        return pulumi.get(self, "max_request")

    @_builtins.property
    @pulumi.getter(name="maxScaleDownPercent")
    def max_scale_down_percent(self) -> Optional[_builtins.float]:
        """
        Maximum percentage decrease allowed in a single recommendation cycle.
        """
        return pulumi.get(self, "max_scale_down_percent")

    @_builtins.property
    @pulumi.getter(name="maxScaleUpPercent")
    def max_scale_up_percent(self) -> Optional[_builtins.float]:
        """
        Maximum percentage increase allowed in a single recommendation cycle.
        """
        return pulumi.get(self, "max_scale_up_percent")

    @_builtins.property
    @pulumi.getter(name="minDataPoints")
    def min_data_points(self) -> Optional[_builtins.int]:
        """
        Minimum number of data points required before a recommendation is emitted.
        """
        return pulumi.get(self, "min_data_points")

    @_builtins.property
    @pulumi.getter(name="minRequest")
    def min_request(self) -> Optional[_builtins.int]:
        """
        Minimum resource request in millicores (CPU) or bytes (memory/GPU).
        """
        return pulumi.get(self, "min_request")

    @_builtins.property
    @pulumi.getter(name="overheadMultiplier")
    def overhead_multiplier(self) -> Optional[_builtins.float]:
        """
        Multiplier applied on top of the recommendation to add headroom.
        """
        return pulumi.get(self, "overhead_multiplier")

    @_builtins.property
    @pulumi.getter(name="targetPercentile")
    def target_percentile(self) -> Optional[_builtins.float]:
        """
        Percentile of usage data used as the recommendation target (e.g. 0.95).
        """
        return pulumi.get(self, "target_percentile")


