# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['WorkloadPolicyArgs', 'WorkloadPolicy']

@pulumi.input_type
class WorkloadPolicyArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 action_triggers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 cooldown_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 cpu_vertical_scaling: Optional[pulumi.Input['VerticalScalingArgsArgs']] = None,
                 cron_schedule: Optional[pulumi.Input[_builtins.str]] = None,
                 defragmentation_schedule: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 detection_triggers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 drift_delta_percent: Optional[pulumi.Input[_builtins.float]] = None,
                 gpu_vertical_scaling: Optional[pulumi.Input['VerticalScalingArgsArgs']] = None,
                 gpu_vram_vertical_scaling: Optional[pulumi.Input['VerticalScalingArgsArgs']] = None,
                 horizontal_scaling: Optional[pulumi.Input['HorizontalScalingArgsArgs']] = None,
                 hysteresis_vs_target: Optional[pulumi.Input[_builtins.float]] = None,
                 live_migration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 loopback_period_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 memory_vertical_scaling: Optional[pulumi.Input['VerticalScalingArgsArgs']] = None,
                 min_change_percent: Optional[pulumi.Input[_builtins.float]] = None,
                 min_data_points: Optional[pulumi.Input[_builtins.int]] = None,
                 min_vpa_window_data_points: Optional[pulumi.Input[_builtins.int]] = None,
                 scheduler_plugins: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 stability_cv_max: Optional[pulumi.Input[_builtins.float]] = None,
                 startup_period_seconds: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a WorkloadPolicy resource.
        """
        pulumi.set(__self__, "name", name)
        if action_triggers is not None:
            pulumi.set(__self__, "action_triggers", action_triggers)
        if cooldown_minutes is not None:
            pulumi.set(__self__, "cooldown_minutes", cooldown_minutes)
        if cpu_vertical_scaling is not None:
            pulumi.set(__self__, "cpu_vertical_scaling", cpu_vertical_scaling)
        if cron_schedule is not None:
            pulumi.set(__self__, "cron_schedule", cron_schedule)
        if defragmentation_schedule is not None:
            pulumi.set(__self__, "defragmentation_schedule", defragmentation_schedule)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if detection_triggers is not None:
            pulumi.set(__self__, "detection_triggers", detection_triggers)
        if drift_delta_percent is not None:
            pulumi.set(__self__, "drift_delta_percent", drift_delta_percent)
        if gpu_vertical_scaling is not None:
            pulumi.set(__self__, "gpu_vertical_scaling", gpu_vertical_scaling)
        if gpu_vram_vertical_scaling is not None:
            pulumi.set(__self__, "gpu_vram_vertical_scaling", gpu_vram_vertical_scaling)
        if horizontal_scaling is not None:
            pulumi.set(__self__, "horizontal_scaling", horizontal_scaling)
        if hysteresis_vs_target is not None:
            pulumi.set(__self__, "hysteresis_vs_target", hysteresis_vs_target)
        if live_migration_enabled is not None:
            pulumi.set(__self__, "live_migration_enabled", live_migration_enabled)
        if loopback_period_seconds is not None:
            pulumi.set(__self__, "loopback_period_seconds", loopback_period_seconds)
        if memory_vertical_scaling is not None:
            pulumi.set(__self__, "memory_vertical_scaling", memory_vertical_scaling)
        if min_change_percent is not None:
            pulumi.set(__self__, "min_change_percent", min_change_percent)
        if min_data_points is not None:
            pulumi.set(__self__, "min_data_points", min_data_points)
        if min_vpa_window_data_points is not None:
            pulumi.set(__self__, "min_vpa_window_data_points", min_vpa_window_data_points)
        if scheduler_plugins is not None:
            pulumi.set(__self__, "scheduler_plugins", scheduler_plugins)
        if stability_cv_max is not None:
            pulumi.set(__self__, "stability_cv_max", stability_cv_max)
        if startup_period_seconds is not None:
            pulumi.set(__self__, "startup_period_seconds", startup_period_seconds)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="actionTriggers")
    def action_triggers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "action_triggers")

    @action_triggers.setter
    def action_triggers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "action_triggers", value)

    @_builtins.property
    @pulumi.getter(name="cooldownMinutes")
    def cooldown_minutes(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "cooldown_minutes")

    @cooldown_minutes.setter
    def cooldown_minutes(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "cooldown_minutes", value)

    @_builtins.property
    @pulumi.getter(name="cpuVerticalScaling")
    def cpu_vertical_scaling(self) -> Optional[pulumi.Input['VerticalScalingArgsArgs']]:
        return pulumi.get(self, "cpu_vertical_scaling")

    @cpu_vertical_scaling.setter
    def cpu_vertical_scaling(self, value: Optional[pulumi.Input['VerticalScalingArgsArgs']]):
        pulumi.set(self, "cpu_vertical_scaling", value)

    @_builtins.property
    @pulumi.getter(name="cronSchedule")
    def cron_schedule(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cron_schedule")

    @cron_schedule.setter
    def cron_schedule(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cron_schedule", value)

    @_builtins.property
    @pulumi.getter(name="defragmentationSchedule")
    def defragmentation_schedule(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "defragmentation_schedule")

    @defragmentation_schedule.setter
    def defragmentation_schedule(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "defragmentation_schedule", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="detectionTriggers")
    def detection_triggers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "detection_triggers")

    @detection_triggers.setter
    def detection_triggers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "detection_triggers", value)

    @_builtins.property
    @pulumi.getter(name="driftDeltaPercent")
    def drift_delta_percent(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "drift_delta_percent")

    @drift_delta_percent.setter
    def drift_delta_percent(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "drift_delta_percent", value)

    @_builtins.property
    @pulumi.getter(name="gpuVerticalScaling")
    def gpu_vertical_scaling(self) -> Optional[pulumi.Input['VerticalScalingArgsArgs']]:
        return pulumi.get(self, "gpu_vertical_scaling")

    @gpu_vertical_scaling.setter
    def gpu_vertical_scaling(self, value: Optional[pulumi.Input['VerticalScalingArgsArgs']]):
        pulumi.set(self, "gpu_vertical_scaling", value)

    @_builtins.property
    @pulumi.getter(name="gpuVramVerticalScaling")
    def gpu_vram_vertical_scaling(self) -> Optional[pulumi.Input['VerticalScalingArgsArgs']]:
        return pulumi.get(self, "gpu_vram_vertical_scaling")

    @gpu_vram_vertical_scaling.setter
    def gpu_vram_vertical_scaling(self, value: Optional[pulumi.Input['VerticalScalingArgsArgs']]):
        pulumi.set(self, "gpu_vram_vertical_scaling", value)

    @_builtins.property
    @pulumi.getter(name="horizontalScaling")
    def horizontal_scaling(self) -> Optional[pulumi.Input['HorizontalScalingArgsArgs']]:
        return pulumi.get(self, "horizontal_scaling")

    @horizontal_scaling.setter
    def horizontal_scaling(self, value: Optional[pulumi.Input['HorizontalScalingArgsArgs']]):
        pulumi.set(self, "horizontal_scaling", value)

    @_builtins.property
    @pulumi.getter(name="hysteresisVsTarget")
    def hysteresis_vs_target(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "hysteresis_vs_target")

    @hysteresis_vs_target.setter
    def hysteresis_vs_target(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "hysteresis_vs_target", value)

    @_builtins.property
    @pulumi.getter(name="liveMigrationEnabled")
    def live_migration_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "live_migration_enabled")

    @live_migration_enabled.setter
    def live_migration_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "live_migration_enabled", value)

    @_builtins.property
    @pulumi.getter(name="loopbackPeriodSeconds")
    def loopback_period_seconds(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "loopback_period_seconds")

    @loopback_period_seconds.setter
    def loopback_period_seconds(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "loopback_period_seconds", value)

    @_builtins.property
    @pulumi.getter(name="memoryVerticalScaling")
    def memory_vertical_scaling(self) -> Optional[pulumi.Input['VerticalScalingArgsArgs']]:
        return pulumi.get(self, "memory_vertical_scaling")

    @memory_vertical_scaling.setter
    def memory_vertical_scaling(self, value: Optional[pulumi.Input['VerticalScalingArgsArgs']]):
        pulumi.set(self, "memory_vertical_scaling", value)

    @_builtins.property
    @pulumi.getter(name="minChangePercent")
    def min_change_percent(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "min_change_percent")

    @min_change_percent.setter
    def min_change_percent(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "min_change_percent", value)

    @_builtins.property
    @pulumi.getter(name="minDataPoints")
    def min_data_points(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "min_data_points")

    @min_data_points.setter
    def min_data_points(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "min_data_points", value)

    @_builtins.property
    @pulumi.getter(name="minVpaWindowDataPoints")
    def min_vpa_window_data_points(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "min_vpa_window_data_points")

    @min_vpa_window_data_points.setter
    def min_vpa_window_data_points(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "min_vpa_window_data_points", value)

    @_builtins.property
    @pulumi.getter(name="schedulerPlugins")
    def scheduler_plugins(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "scheduler_plugins")

    @scheduler_plugins.setter
    def scheduler_plugins(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "scheduler_plugins", value)

    @_builtins.property
    @pulumi.getter(name="stabilityCvMax")
    def stability_cv_max(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "stability_cv_max")

    @stability_cv_max.setter
    def stability_cv_max(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "stability_cv_max", value)

    @_builtins.property
    @pulumi.getter(name="startupPeriodSeconds")
    def startup_period_seconds(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "startup_period_seconds")

    @startup_period_seconds.setter
    def startup_period_seconds(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "startup_period_seconds", value)


@pulumi.type_token("devzero:resources:WorkloadPolicy")
class WorkloadPolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action_triggers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 cooldown_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 cpu_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 cron_schedule: Optional[pulumi.Input[_builtins.str]] = None,
                 defragmentation_schedule: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 detection_triggers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 drift_delta_percent: Optional[pulumi.Input[_builtins.float]] = None,
                 gpu_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 gpu_vram_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 horizontal_scaling: Optional[pulumi.Input[Union['HorizontalScalingArgsArgs', 'HorizontalScalingArgsArgsDict']]] = None,
                 hysteresis_vs_target: Optional[pulumi.Input[_builtins.float]] = None,
                 live_migration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 loopback_period_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 memory_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 min_change_percent: Optional[pulumi.Input[_builtins.float]] = None,
                 min_data_points: Optional[pulumi.Input[_builtins.int]] = None,
                 min_vpa_window_data_points: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 scheduler_plugins: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 stability_cv_max: Optional[pulumi.Input[_builtins.float]] = None,
                 startup_period_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Create a WorkloadPolicy resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WorkloadPolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WorkloadPolicy resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param WorkloadPolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkloadPolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action_triggers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 cooldown_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 cpu_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 cron_schedule: Optional[pulumi.Input[_builtins.str]] = None,
                 defragmentation_schedule: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 detection_triggers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 drift_delta_percent: Optional[pulumi.Input[_builtins.float]] = None,
                 gpu_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 gpu_vram_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 horizontal_scaling: Optional[pulumi.Input[Union['HorizontalScalingArgsArgs', 'HorizontalScalingArgsArgsDict']]] = None,
                 hysteresis_vs_target: Optional[pulumi.Input[_builtins.float]] = None,
                 live_migration_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 loopback_period_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 memory_vertical_scaling: Optional[pulumi.Input[Union['VerticalScalingArgsArgs', 'VerticalScalingArgsArgsDict']]] = None,
                 min_change_percent: Optional[pulumi.Input[_builtins.float]] = None,
                 min_data_points: Optional[pulumi.Input[_builtins.int]] = None,
                 min_vpa_window_data_points: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 scheduler_plugins: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 stability_cv_max: Optional[pulumi.Input[_builtins.float]] = None,
                 startup_period_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkloadPolicyArgs.__new__(WorkloadPolicyArgs)

            __props__.__dict__["action_triggers"] = action_triggers
            __props__.__dict__["cooldown_minutes"] = cooldown_minutes
            __props__.__dict__["cpu_vertical_scaling"] = cpu_vertical_scaling
            __props__.__dict__["cron_schedule"] = cron_schedule
            __props__.__dict__["defragmentation_schedule"] = defragmentation_schedule
            __props__.__dict__["description"] = description
            __props__.__dict__["detection_triggers"] = detection_triggers
            __props__.__dict__["drift_delta_percent"] = drift_delta_percent
            __props__.__dict__["gpu_vertical_scaling"] = gpu_vertical_scaling
            __props__.__dict__["gpu_vram_vertical_scaling"] = gpu_vram_vertical_scaling
            __props__.__dict__["horizontal_scaling"] = horizontal_scaling
            __props__.__dict__["hysteresis_vs_target"] = hysteresis_vs_target
            __props__.__dict__["live_migration_enabled"] = live_migration_enabled
            __props__.__dict__["loopback_period_seconds"] = loopback_period_seconds
            __props__.__dict__["memory_vertical_scaling"] = memory_vertical_scaling
            __props__.__dict__["min_change_percent"] = min_change_percent
            __props__.__dict__["min_data_points"] = min_data_points
            __props__.__dict__["min_vpa_window_data_points"] = min_vpa_window_data_points
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["scheduler_plugins"] = scheduler_plugins
            __props__.__dict__["stability_cv_max"] = stability_cv_max
            __props__.__dict__["startup_period_seconds"] = startup_period_seconds
        super(WorkloadPolicy, __self__).__init__(
            'devzero:resources:WorkloadPolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'WorkloadPolicy':
        """
        Get an existing WorkloadPolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = WorkloadPolicyArgs.__new__(WorkloadPolicyArgs)

        __props__.__dict__["action_triggers"] = None
        __props__.__dict__["cooldown_minutes"] = None
        __props__.__dict__["cpu_vertical_scaling"] = None
        __props__.__dict__["cron_schedule"] = None
        __props__.__dict__["defragmentation_schedule"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["detection_triggers"] = None
        __props__.__dict__["drift_delta_percent"] = None
        __props__.__dict__["gpu_vertical_scaling"] = None
        __props__.__dict__["gpu_vram_vertical_scaling"] = None
        __props__.__dict__["horizontal_scaling"] = None
        __props__.__dict__["hysteresis_vs_target"] = None
        __props__.__dict__["live_migration_enabled"] = None
        __props__.__dict__["loopback_period_seconds"] = None
        __props__.__dict__["memory_vertical_scaling"] = None
        __props__.__dict__["min_change_percent"] = None
        __props__.__dict__["min_data_points"] = None
        __props__.__dict__["min_vpa_window_data_points"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["scheduler_plugins"] = None
        __props__.__dict__["stability_cv_max"] = None
        __props__.__dict__["startup_period_seconds"] = None
        return WorkloadPolicy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="actionTriggers")
    def action_triggers(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Action triggers: 'on_detection' or 'on_schedule'.
        """
        return pulumi.get(self, "action_triggers")

    @_builtins.property
    @pulumi.getter(name="cooldownMinutes")
    def cooldown_minutes(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Minutes to wait between applying recommendations.
        """
        return pulumi.get(self, "cooldown_minutes")

    @_builtins.property
    @pulumi.getter(name="cpuVerticalScaling")
    def cpu_vertical_scaling(self) -> pulumi.Output[Optional['outputs.VerticalScalingArgs']]:
        return pulumi.get(self, "cpu_vertical_scaling")

    @_builtins.property
    @pulumi.getter(name="cronSchedule")
    def cron_schedule(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Cron expression for scheduled application (5-field format).
        """
        return pulumi.get(self, "cron_schedule")

    @_builtins.property
    @pulumi.getter(name="defragmentationSchedule")
    def defragmentation_schedule(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Cron expression for background defragmentation.
        """
        return pulumi.get(self, "defragmentation_schedule")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Free-form description of the policy.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="detectionTriggers")
    def detection_triggers(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
        """
        return pulumi.get(self, "detection_triggers")

    @_builtins.property
    @pulumi.getter(name="driftDeltaPercent")
    def drift_delta_percent(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Percentage drift from baseline that triggers VPA refresh.
        """
        return pulumi.get(self, "drift_delta_percent")

    @_builtins.property
    @pulumi.getter(name="gpuVerticalScaling")
    def gpu_vertical_scaling(self) -> pulumi.Output[Optional['outputs.VerticalScalingArgs']]:
        return pulumi.get(self, "gpu_vertical_scaling")

    @_builtins.property
    @pulumi.getter(name="gpuVramVerticalScaling")
    def gpu_vram_vertical_scaling(self) -> pulumi.Output[Optional['outputs.VerticalScalingArgs']]:
        return pulumi.get(self, "gpu_vram_vertical_scaling")

    @_builtins.property
    @pulumi.getter(name="horizontalScaling")
    def horizontal_scaling(self) -> pulumi.Output[Optional['outputs.HorizontalScalingArgs']]:
        return pulumi.get(self, "horizontal_scaling")

    @_builtins.property
    @pulumi.getter(name="hysteresisVsTarget")
    def hysteresis_vs_target(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Hysteresis threshold vs target for HPA coordination.
        """
        return pulumi.get(self, "hysteresis_vs_target")

    @_builtins.property
    @pulumi.getter(name="liveMigrationEnabled")
    def live_migration_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Allow live migration when applying recommendations.
        """
        return pulumi.get(self, "live_migration_enabled")

    @_builtins.property
    @pulumi.getter(name="loopbackPeriodSeconds")
    def loopback_period_seconds(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Period in seconds to look back for resource usage data.
        """
        return pulumi.get(self, "loopback_period_seconds")

    @_builtins.property
    @pulumi.getter(name="memoryVerticalScaling")
    def memory_vertical_scaling(self) -> pulumi.Output[Optional['outputs.VerticalScalingArgs']]:
        return pulumi.get(self, "memory_vertical_scaling")

    @_builtins.property
    @pulumi.getter(name="minChangePercent")
    def min_change_percent(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Global minimum change threshold for applying recommendations.
        """
        return pulumi.get(self, "min_change_percent")

    @_builtins.property
    @pulumi.getter(name="minDataPoints")
    def min_data_points(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Global minimum data points required for recommendations.
        """
        return pulumi.get(self, "min_data_points")

    @_builtins.property
    @pulumi.getter(name="minVpaWindowDataPoints")
    def min_vpa_window_data_points(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Minimum data points in VPA analysis window.
        """
        return pulumi.get(self, "min_vpa_window_data_points")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-friendly name for the policy.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="schedulerPlugins")
    def scheduler_plugins(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Kubernetes scheduler plugins to activate.
        """
        return pulumi.get(self, "scheduler_plugins")

    @_builtins.property
    @pulumi.getter(name="stabilityCvMax")
    def stability_cv_max(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Maximum coefficient of variation for workload to be considered stable.
        """
        return pulumi.get(self, "stability_cv_max")

    @_builtins.property
    @pulumi.getter(name="startupPeriodSeconds")
    def startup_period_seconds(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Period in seconds to ignore usage data after workload starts.
        """
        return pulumi.get(self, "startup_period_seconds")

