# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import errno
from setuptools import setup, find_packages
from setuptools.command.install import install
from subprocess import check_call


VERSION = "0.0.0"
def readme():
    for path in ['README.md', 'pulumi_devzero/README.md']:
        try:
            with open(path, encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            continue
    return "devzero Pulumi Package - Development Version"


setup(name='pulumi_devzero',
      python_requires='>=3.9',
      version=VERSION,
      description="A Pulumi provider for managing DevZero infrastructure resources.",
      long_description=readme(),
      long_description_content_type='text/markdown',
      keywords='pulumi devzero category/cloud',
      url='https://devzero.io',
      project_urls={
          'Repository': 'https://github.com/devzero-inc/pulumi-provider-devzero'
      },
      license='MIT',
      packages=find_packages(),
      package_data={
          'pulumi_devzero': [
              'py.typed',
              'pulumi-plugin.json',
          ]
      },
      install_requires=[
          'parver>=0.2.1',
          'pulumi>=3.0.0,<4.0.0',
          'semver>=2.8.1',
          'typing-extensions>=4.11,<5; python_version < "3.11"'
      ],
      zip_safe=False)
