// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetClusterIdByName(ctx *pulumi.Context, args *GetClusterIdByNameArgs, opts ...pulumi.InvokeOption) (*GetClusterIdByNameResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetClusterIdByNameResult
	err := ctx.Invoke("devzero:resources:getClusterIdByName", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetClusterIdByNameArgs struct {
	// Optional cloud provider filter. One of: 'AWS', 'GCP', 'AKS', 'OCI'.
	CloudProvider *string `pulumi:"cloudProvider"`
	// Controls liveness filtering: IGNORE, PREFER_LIVE, or REQUIRE_LIVE.
	Liveness *string `pulumi:"liveness"`
	// The cluster name to look up.
	Name string `pulumi:"name"`
	// Optional region filter, e.g. "us-east-1".
	Region *string `pulumi:"region"`
	// The team ID to search within.
	TeamId string `pulumi:"teamId"`
}

type GetClusterIdByNameResult struct {
	// The ID of the cluster matching the given team and name.
	ClusterId string `pulumi:"clusterId"`
}

func GetClusterIdByNameOutput(ctx *pulumi.Context, args GetClusterIdByNameOutputArgs, opts ...pulumi.InvokeOption) GetClusterIdByNameResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetClusterIdByNameResultOutput, error) {
			args := v.(GetClusterIdByNameArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("devzero:resources:getClusterIdByName", args, GetClusterIdByNameResultOutput{}, options).(GetClusterIdByNameResultOutput), nil
		}).(GetClusterIdByNameResultOutput)
}

type GetClusterIdByNameOutputArgs struct {
	// Optional cloud provider filter. One of: 'AWS', 'GCP', 'AKS', 'OCI'.
	CloudProvider pulumi.StringPtrInput `pulumi:"cloudProvider"`
	// Controls liveness filtering: IGNORE, PREFER_LIVE, or REQUIRE_LIVE.
	Liveness pulumi.StringPtrInput `pulumi:"liveness"`
	// The cluster name to look up.
	Name pulumi.StringInput `pulumi:"name"`
	// Optional region filter, e.g. "us-east-1".
	Region pulumi.StringPtrInput `pulumi:"region"`
	// The team ID to search within.
	TeamId pulumi.StringInput `pulumi:"teamId"`
}

func (GetClusterIdByNameOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClusterIdByNameArgs)(nil)).Elem()
}

type GetClusterIdByNameResultOutput struct{ *pulumi.OutputState }

func (GetClusterIdByNameResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClusterIdByNameResult)(nil)).Elem()
}

func (o GetClusterIdByNameResultOutput) ToGetClusterIdByNameResultOutput() GetClusterIdByNameResultOutput {
	return o
}

func (o GetClusterIdByNameResultOutput) ToGetClusterIdByNameResultOutputWithContext(ctx context.Context) GetClusterIdByNameResultOutput {
	return o
}

// The ID of the cluster matching the given team and name.
func (o GetClusterIdByNameResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterIdByNameResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetClusterIdByNameResultOutput{})
}
