// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "devzero:resources:Cluster":
		r = &Cluster{}
	case "devzero:resources:NodePolicy":
		r = &NodePolicy{}
	case "devzero:resources:NodePolicyTarget":
		r = &NodePolicyTarget{}
	case "devzero:resources:WorkloadPolicy":
		r = &WorkloadPolicy{}
	case "devzero:resources:WorkloadPolicyTarget":
		r = &WorkloadPolicyTarget{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"devzero",
		"resources",
		&module{version},
	)
}
