// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NodePolicyTarget struct {
	pulumi.CustomResourceState

	// Cluster IDs where this node policy applies.
	ClusterIds pulumi.StringArrayOutput `pulumi:"clusterIds"`
	// Free-form description of the target.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Whether this target is active. Defaults to true.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Human-friendly name for the target.
	Name pulumi.StringOutput `pulumi:"name"`
	// Node policy ID this target is attached to.
	PolicyId pulumi.StringOutput `pulumi:"policyId"`
}

// NewNodePolicyTarget registers a new resource with the given unique name, arguments, and options.
func NewNodePolicyTarget(ctx *pulumi.Context,
	name string, args *NodePolicyTargetArgs, opts ...pulumi.ResourceOption) (*NodePolicyTarget, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterIds == nil {
		return nil, errors.New("invalid value for required argument 'ClusterIds'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.PolicyId == nil {
		return nil, errors.New("invalid value for required argument 'PolicyId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NodePolicyTarget
	err := ctx.RegisterResource("devzero:resources:NodePolicyTarget", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNodePolicyTarget gets an existing NodePolicyTarget resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNodePolicyTarget(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NodePolicyTargetState, opts ...pulumi.ResourceOption) (*NodePolicyTarget, error) {
	var resource NodePolicyTarget
	err := ctx.ReadResource("devzero:resources:NodePolicyTarget", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NodePolicyTarget resources.
type nodePolicyTargetState struct {
}

type NodePolicyTargetState struct {
}

func (NodePolicyTargetState) ElementType() reflect.Type {
	return reflect.TypeOf((*nodePolicyTargetState)(nil)).Elem()
}

type nodePolicyTargetArgs struct {
	ClusterIds  []string `pulumi:"clusterIds"`
	Description *string  `pulumi:"description"`
	Enabled     *bool    `pulumi:"enabled"`
	Name        string   `pulumi:"name"`
	PolicyId    string   `pulumi:"policyId"`
}

// The set of arguments for constructing a NodePolicyTarget resource.
type NodePolicyTargetArgs struct {
	ClusterIds  pulumi.StringArrayInput
	Description pulumi.StringPtrInput
	Enabled     pulumi.BoolPtrInput
	Name        pulumi.StringInput
	PolicyId    pulumi.StringInput
}

func (NodePolicyTargetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nodePolicyTargetArgs)(nil)).Elem()
}

type NodePolicyTargetInput interface {
	pulumi.Input

	ToNodePolicyTargetOutput() NodePolicyTargetOutput
	ToNodePolicyTargetOutputWithContext(ctx context.Context) NodePolicyTargetOutput
}

func (*NodePolicyTarget) ElementType() reflect.Type {
	return reflect.TypeOf((**NodePolicyTarget)(nil)).Elem()
}

func (i *NodePolicyTarget) ToNodePolicyTargetOutput() NodePolicyTargetOutput {
	return i.ToNodePolicyTargetOutputWithContext(context.Background())
}

func (i *NodePolicyTarget) ToNodePolicyTargetOutputWithContext(ctx context.Context) NodePolicyTargetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePolicyTargetOutput)
}

// NodePolicyTargetArrayInput is an input type that accepts NodePolicyTargetArray and NodePolicyTargetArrayOutput values.
// You can construct a concrete instance of `NodePolicyTargetArrayInput` via:
//
//	NodePolicyTargetArray{ NodePolicyTargetArgs{...} }
type NodePolicyTargetArrayInput interface {
	pulumi.Input

	ToNodePolicyTargetArrayOutput() NodePolicyTargetArrayOutput
	ToNodePolicyTargetArrayOutputWithContext(context.Context) NodePolicyTargetArrayOutput
}

type NodePolicyTargetArray []NodePolicyTargetInput

func (NodePolicyTargetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NodePolicyTarget)(nil)).Elem()
}

func (i NodePolicyTargetArray) ToNodePolicyTargetArrayOutput() NodePolicyTargetArrayOutput {
	return i.ToNodePolicyTargetArrayOutputWithContext(context.Background())
}

func (i NodePolicyTargetArray) ToNodePolicyTargetArrayOutputWithContext(ctx context.Context) NodePolicyTargetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePolicyTargetArrayOutput)
}

// NodePolicyTargetMapInput is an input type that accepts NodePolicyTargetMap and NodePolicyTargetMapOutput values.
// You can construct a concrete instance of `NodePolicyTargetMapInput` via:
//
//	NodePolicyTargetMap{ "key": NodePolicyTargetArgs{...} }
type NodePolicyTargetMapInput interface {
	pulumi.Input

	ToNodePolicyTargetMapOutput() NodePolicyTargetMapOutput
	ToNodePolicyTargetMapOutputWithContext(context.Context) NodePolicyTargetMapOutput
}

type NodePolicyTargetMap map[string]NodePolicyTargetInput

func (NodePolicyTargetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NodePolicyTarget)(nil)).Elem()
}

func (i NodePolicyTargetMap) ToNodePolicyTargetMapOutput() NodePolicyTargetMapOutput {
	return i.ToNodePolicyTargetMapOutputWithContext(context.Background())
}

func (i NodePolicyTargetMap) ToNodePolicyTargetMapOutputWithContext(ctx context.Context) NodePolicyTargetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePolicyTargetMapOutput)
}

type NodePolicyTargetOutput struct{ *pulumi.OutputState }

func (NodePolicyTargetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NodePolicyTarget)(nil)).Elem()
}

func (o NodePolicyTargetOutput) ToNodePolicyTargetOutput() NodePolicyTargetOutput {
	return o
}

func (o NodePolicyTargetOutput) ToNodePolicyTargetOutputWithContext(ctx context.Context) NodePolicyTargetOutput {
	return o
}

// Cluster IDs where this node policy applies.
func (o NodePolicyTargetOutput) ClusterIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NodePolicyTarget) pulumi.StringArrayOutput { return v.ClusterIds }).(pulumi.StringArrayOutput)
}

// Free-form description of the target.
func (o NodePolicyTargetOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NodePolicyTarget) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Whether this target is active. Defaults to true.
func (o NodePolicyTargetOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NodePolicyTarget) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Human-friendly name for the target.
func (o NodePolicyTargetOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NodePolicyTarget) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Node policy ID this target is attached to.
func (o NodePolicyTargetOutput) PolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v *NodePolicyTarget) pulumi.StringOutput { return v.PolicyId }).(pulumi.StringOutput)
}

type NodePolicyTargetArrayOutput struct{ *pulumi.OutputState }

func (NodePolicyTargetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NodePolicyTarget)(nil)).Elem()
}

func (o NodePolicyTargetArrayOutput) ToNodePolicyTargetArrayOutput() NodePolicyTargetArrayOutput {
	return o
}

func (o NodePolicyTargetArrayOutput) ToNodePolicyTargetArrayOutputWithContext(ctx context.Context) NodePolicyTargetArrayOutput {
	return o
}

func (o NodePolicyTargetArrayOutput) Index(i pulumi.IntInput) NodePolicyTargetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NodePolicyTarget {
		return vs[0].([]*NodePolicyTarget)[vs[1].(int)]
	}).(NodePolicyTargetOutput)
}

type NodePolicyTargetMapOutput struct{ *pulumi.OutputState }

func (NodePolicyTargetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NodePolicyTarget)(nil)).Elem()
}

func (o NodePolicyTargetMapOutput) ToNodePolicyTargetMapOutput() NodePolicyTargetMapOutput {
	return o
}

func (o NodePolicyTargetMapOutput) ToNodePolicyTargetMapOutputWithContext(ctx context.Context) NodePolicyTargetMapOutput {
	return o
}

func (o NodePolicyTargetMapOutput) MapIndex(k pulumi.StringInput) NodePolicyTargetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NodePolicyTarget {
		return vs[0].(map[string]*NodePolicyTarget)[vs[1].(string)]
	}).(NodePolicyTargetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NodePolicyTargetInput)(nil)).Elem(), &NodePolicyTarget{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodePolicyTargetArrayInput)(nil)).Elem(), NodePolicyTargetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodePolicyTargetMapInput)(nil)).Elem(), NodePolicyTargetMap{})
	pulumi.RegisterOutputType(NodePolicyTargetOutput{})
	pulumi.RegisterOutputType(NodePolicyTargetArrayOutput{})
	pulumi.RegisterOutputType(NodePolicyTargetMapOutput{})
}
