// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NodePolicy struct {
	pulumi.CustomResourceState

	// CPU architectures (e.g. amd64, arm64).
	Architectures LabelSelectorArgsPtrOutput `pulumi:"architectures"`
	// AWS-specific node class configuration.
	Aws AWSNodeClassSpecArgsPtrOutput `pulumi:"aws"`
	// Azure-specific node class configuration.
	Azure AzureNodeClassSpecArgsPtrOutput `pulumi:"azure"`
	// Capacity types (e.g. on-demand, spot).
	CapacityTypes LabelSelectorArgsPtrOutput `pulumi:"capacityTypes"`
	// Free-form description of the node policy.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Karpenter disruption policy for consolidation and expiry.
	Disruption DisruptionPolicyArgsPtrOutput `pulumi:"disruption"`
	// Filter instances by category (e.g. general-purpose, compute-optimized).
	InstanceCategories LabelSelectorArgsPtrOutput `pulumi:"instanceCategories"`
	// Filter instances by CPU count.
	InstanceCpus LabelSelectorArgsPtrOutput `pulumi:"instanceCpus"`
	// Filter instances by family (e.g. m5, c6i).
	InstanceFamilies LabelSelectorArgsPtrOutput `pulumi:"instanceFamilies"`
	// Filter instances by generation.
	InstanceGenerations LabelSelectorArgsPtrOutput `pulumi:"instanceGenerations"`
	// Filter instances by hypervisor type.
	InstanceHypervisors LabelSelectorArgsPtrOutput `pulumi:"instanceHypervisors"`
	// Filter instances by size (e.g. large, xlarge).
	InstanceSizes LabelSelectorArgsPtrOutput `pulumi:"instanceSizes"`
	// Explicitly select specific instance types.
	InstanceTypes LabelSelectorArgsPtrOutput `pulumi:"instanceTypes"`
	// Labels applied to provisioned nodes.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Resource limits on the total capacity managed by this policy.
	Limits ResourceLimitsArgsPtrOutput `pulumi:"limits"`
	// Human-friendly name for the node policy.
	Name pulumi.StringOutput `pulumi:"name"`
	// Override name for the generated Karpenter NodeClass.
	NodeClassName pulumi.StringPtrOutput `pulumi:"nodeClassName"`
	// Override name for the generated Karpenter NodePool.
	NodePoolName pulumi.StringPtrOutput `pulumi:"nodePoolName"`
	// Operating systems for nodes (e.g. linux, windows).
	OperatingSystems LabelSelectorArgsPtrOutput `pulumi:"operatingSystems"`
	// Raw Karpenter YAML for full NodePool/NodeClass customization.
	Raw RawKarpenterSpecArgsArrayOutput `pulumi:"raw"`
	// Taints applied to provisioned nodes.
	Taints TaintArgsArrayOutput `pulumi:"taints"`
	// Priority weight for this policy; higher values take precedence.
	Weight pulumi.IntPtrOutput `pulumi:"weight"`
	// Availability zones where nodes may be provisioned.
	Zones LabelSelectorArgsPtrOutput `pulumi:"zones"`
}

// NewNodePolicy registers a new resource with the given unique name, arguments, and options.
func NewNodePolicy(ctx *pulumi.Context,
	name string, args *NodePolicyArgs, opts ...pulumi.ResourceOption) (*NodePolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NodePolicy
	err := ctx.RegisterResource("devzero:resources:NodePolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNodePolicy gets an existing NodePolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNodePolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NodePolicyState, opts ...pulumi.ResourceOption) (*NodePolicy, error) {
	var resource NodePolicy
	err := ctx.ReadResource("devzero:resources:NodePolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NodePolicy resources.
type nodePolicyState struct {
}

type NodePolicyState struct {
}

func (NodePolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*nodePolicyState)(nil)).Elem()
}

type nodePolicyArgs struct {
	Architectures       *LabelSelectorArgs      `pulumi:"architectures"`
	Aws                 *AWSNodeClassSpecArgs   `pulumi:"aws"`
	Azure               *AzureNodeClassSpecArgs `pulumi:"azure"`
	CapacityTypes       *LabelSelectorArgs      `pulumi:"capacityTypes"`
	Description         *string                 `pulumi:"description"`
	Disruption          *DisruptionPolicyArgs   `pulumi:"disruption"`
	InstanceCategories  *LabelSelectorArgs      `pulumi:"instanceCategories"`
	InstanceCpus        *LabelSelectorArgs      `pulumi:"instanceCpus"`
	InstanceFamilies    *LabelSelectorArgs      `pulumi:"instanceFamilies"`
	InstanceGenerations *LabelSelectorArgs      `pulumi:"instanceGenerations"`
	InstanceHypervisors *LabelSelectorArgs      `pulumi:"instanceHypervisors"`
	InstanceSizes       *LabelSelectorArgs      `pulumi:"instanceSizes"`
	InstanceTypes       *LabelSelectorArgs      `pulumi:"instanceTypes"`
	Labels              map[string]string       `pulumi:"labels"`
	Limits              *ResourceLimitsArgs     `pulumi:"limits"`
	Name                string                  `pulumi:"name"`
	NodeClassName       *string                 `pulumi:"nodeClassName"`
	NodePoolName        *string                 `pulumi:"nodePoolName"`
	OperatingSystems    *LabelSelectorArgs      `pulumi:"operatingSystems"`
	Raw                 []RawKarpenterSpecArgs  `pulumi:"raw"`
	Taints              []TaintArgs             `pulumi:"taints"`
	Weight              *int                    `pulumi:"weight"`
	Zones               *LabelSelectorArgs      `pulumi:"zones"`
}

// The set of arguments for constructing a NodePolicy resource.
type NodePolicyArgs struct {
	Architectures       LabelSelectorArgsPtrInput
	Aws                 AWSNodeClassSpecArgsPtrInput
	Azure               AzureNodeClassSpecArgsPtrInput
	CapacityTypes       LabelSelectorArgsPtrInput
	Description         pulumi.StringPtrInput
	Disruption          DisruptionPolicyArgsPtrInput
	InstanceCategories  LabelSelectorArgsPtrInput
	InstanceCpus        LabelSelectorArgsPtrInput
	InstanceFamilies    LabelSelectorArgsPtrInput
	InstanceGenerations LabelSelectorArgsPtrInput
	InstanceHypervisors LabelSelectorArgsPtrInput
	InstanceSizes       LabelSelectorArgsPtrInput
	InstanceTypes       LabelSelectorArgsPtrInput
	Labels              pulumi.StringMapInput
	Limits              ResourceLimitsArgsPtrInput
	Name                pulumi.StringInput
	NodeClassName       pulumi.StringPtrInput
	NodePoolName        pulumi.StringPtrInput
	OperatingSystems    LabelSelectorArgsPtrInput
	Raw                 RawKarpenterSpecArgsArrayInput
	Taints              TaintArgsArrayInput
	Weight              pulumi.IntPtrInput
	Zones               LabelSelectorArgsPtrInput
}

func (NodePolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nodePolicyArgs)(nil)).Elem()
}

type NodePolicyInput interface {
	pulumi.Input

	ToNodePolicyOutput() NodePolicyOutput
	ToNodePolicyOutputWithContext(ctx context.Context) NodePolicyOutput
}

func (*NodePolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**NodePolicy)(nil)).Elem()
}

func (i *NodePolicy) ToNodePolicyOutput() NodePolicyOutput {
	return i.ToNodePolicyOutputWithContext(context.Background())
}

func (i *NodePolicy) ToNodePolicyOutputWithContext(ctx context.Context) NodePolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePolicyOutput)
}

// NodePolicyArrayInput is an input type that accepts NodePolicyArray and NodePolicyArrayOutput values.
// You can construct a concrete instance of `NodePolicyArrayInput` via:
//
//	NodePolicyArray{ NodePolicyArgs{...} }
type NodePolicyArrayInput interface {
	pulumi.Input

	ToNodePolicyArrayOutput() NodePolicyArrayOutput
	ToNodePolicyArrayOutputWithContext(context.Context) NodePolicyArrayOutput
}

type NodePolicyArray []NodePolicyInput

func (NodePolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NodePolicy)(nil)).Elem()
}

func (i NodePolicyArray) ToNodePolicyArrayOutput() NodePolicyArrayOutput {
	return i.ToNodePolicyArrayOutputWithContext(context.Background())
}

func (i NodePolicyArray) ToNodePolicyArrayOutputWithContext(ctx context.Context) NodePolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePolicyArrayOutput)
}

// NodePolicyMapInput is an input type that accepts NodePolicyMap and NodePolicyMapOutput values.
// You can construct a concrete instance of `NodePolicyMapInput` via:
//
//	NodePolicyMap{ "key": NodePolicyArgs{...} }
type NodePolicyMapInput interface {
	pulumi.Input

	ToNodePolicyMapOutput() NodePolicyMapOutput
	ToNodePolicyMapOutputWithContext(context.Context) NodePolicyMapOutput
}

type NodePolicyMap map[string]NodePolicyInput

func (NodePolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NodePolicy)(nil)).Elem()
}

func (i NodePolicyMap) ToNodePolicyMapOutput() NodePolicyMapOutput {
	return i.ToNodePolicyMapOutputWithContext(context.Background())
}

func (i NodePolicyMap) ToNodePolicyMapOutputWithContext(ctx context.Context) NodePolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePolicyMapOutput)
}

type NodePolicyOutput struct{ *pulumi.OutputState }

func (NodePolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NodePolicy)(nil)).Elem()
}

func (o NodePolicyOutput) ToNodePolicyOutput() NodePolicyOutput {
	return o
}

func (o NodePolicyOutput) ToNodePolicyOutputWithContext(ctx context.Context) NodePolicyOutput {
	return o
}

// CPU architectures (e.g. amd64, arm64).
func (o NodePolicyOutput) Architectures() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.Architectures }).(LabelSelectorArgsPtrOutput)
}

// AWS-specific node class configuration.
func (o NodePolicyOutput) Aws() AWSNodeClassSpecArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) AWSNodeClassSpecArgsPtrOutput { return v.Aws }).(AWSNodeClassSpecArgsPtrOutput)
}

// Azure-specific node class configuration.
func (o NodePolicyOutput) Azure() AzureNodeClassSpecArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) AzureNodeClassSpecArgsPtrOutput { return v.Azure }).(AzureNodeClassSpecArgsPtrOutput)
}

// Capacity types (e.g. on-demand, spot).
func (o NodePolicyOutput) CapacityTypes() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.CapacityTypes }).(LabelSelectorArgsPtrOutput)
}

// Free-form description of the node policy.
func (o NodePolicyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NodePolicy) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Karpenter disruption policy for consolidation and expiry.
func (o NodePolicyOutput) Disruption() DisruptionPolicyArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) DisruptionPolicyArgsPtrOutput { return v.Disruption }).(DisruptionPolicyArgsPtrOutput)
}

// Filter instances by category (e.g. general-purpose, compute-optimized).
func (o NodePolicyOutput) InstanceCategories() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.InstanceCategories }).(LabelSelectorArgsPtrOutput)
}

// Filter instances by CPU count.
func (o NodePolicyOutput) InstanceCpus() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.InstanceCpus }).(LabelSelectorArgsPtrOutput)
}

// Filter instances by family (e.g. m5, c6i).
func (o NodePolicyOutput) InstanceFamilies() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.InstanceFamilies }).(LabelSelectorArgsPtrOutput)
}

// Filter instances by generation.
func (o NodePolicyOutput) InstanceGenerations() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.InstanceGenerations }).(LabelSelectorArgsPtrOutput)
}

// Filter instances by hypervisor type.
func (o NodePolicyOutput) InstanceHypervisors() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.InstanceHypervisors }).(LabelSelectorArgsPtrOutput)
}

// Filter instances by size (e.g. large, xlarge).
func (o NodePolicyOutput) InstanceSizes() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.InstanceSizes }).(LabelSelectorArgsPtrOutput)
}

// Explicitly select specific instance types.
func (o NodePolicyOutput) InstanceTypes() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.InstanceTypes }).(LabelSelectorArgsPtrOutput)
}

// Labels applied to provisioned nodes.
func (o NodePolicyOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NodePolicy) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Resource limits on the total capacity managed by this policy.
func (o NodePolicyOutput) Limits() ResourceLimitsArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) ResourceLimitsArgsPtrOutput { return v.Limits }).(ResourceLimitsArgsPtrOutput)
}

// Human-friendly name for the node policy.
func (o NodePolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NodePolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Override name for the generated Karpenter NodeClass.
func (o NodePolicyOutput) NodeClassName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NodePolicy) pulumi.StringPtrOutput { return v.NodeClassName }).(pulumi.StringPtrOutput)
}

// Override name for the generated Karpenter NodePool.
func (o NodePolicyOutput) NodePoolName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NodePolicy) pulumi.StringPtrOutput { return v.NodePoolName }).(pulumi.StringPtrOutput)
}

// Operating systems for nodes (e.g. linux, windows).
func (o NodePolicyOutput) OperatingSystems() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.OperatingSystems }).(LabelSelectorArgsPtrOutput)
}

// Raw Karpenter YAML for full NodePool/NodeClass customization.
func (o NodePolicyOutput) Raw() RawKarpenterSpecArgsArrayOutput {
	return o.ApplyT(func(v *NodePolicy) RawKarpenterSpecArgsArrayOutput { return v.Raw }).(RawKarpenterSpecArgsArrayOutput)
}

// Taints applied to provisioned nodes.
func (o NodePolicyOutput) Taints() TaintArgsArrayOutput {
	return o.ApplyT(func(v *NodePolicy) TaintArgsArrayOutput { return v.Taints }).(TaintArgsArrayOutput)
}

// Priority weight for this policy; higher values take precedence.
func (o NodePolicyOutput) Weight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *NodePolicy) pulumi.IntPtrOutput { return v.Weight }).(pulumi.IntPtrOutput)
}

// Availability zones where nodes may be provisioned.
func (o NodePolicyOutput) Zones() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *NodePolicy) LabelSelectorArgsPtrOutput { return v.Zones }).(LabelSelectorArgsPtrOutput)
}

type NodePolicyArrayOutput struct{ *pulumi.OutputState }

func (NodePolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NodePolicy)(nil)).Elem()
}

func (o NodePolicyArrayOutput) ToNodePolicyArrayOutput() NodePolicyArrayOutput {
	return o
}

func (o NodePolicyArrayOutput) ToNodePolicyArrayOutputWithContext(ctx context.Context) NodePolicyArrayOutput {
	return o
}

func (o NodePolicyArrayOutput) Index(i pulumi.IntInput) NodePolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NodePolicy {
		return vs[0].([]*NodePolicy)[vs[1].(int)]
	}).(NodePolicyOutput)
}

type NodePolicyMapOutput struct{ *pulumi.OutputState }

func (NodePolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NodePolicy)(nil)).Elem()
}

func (o NodePolicyMapOutput) ToNodePolicyMapOutput() NodePolicyMapOutput {
	return o
}

func (o NodePolicyMapOutput) ToNodePolicyMapOutputWithContext(ctx context.Context) NodePolicyMapOutput {
	return o
}

func (o NodePolicyMapOutput) MapIndex(k pulumi.StringInput) NodePolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NodePolicy {
		return vs[0].(map[string]*NodePolicy)[vs[1].(string)]
	}).(NodePolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NodePolicyInput)(nil)).Elem(), &NodePolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodePolicyArrayInput)(nil)).Elem(), NodePolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodePolicyMapInput)(nil)).Elem(), NodePolicyMap{})
	pulumi.RegisterOutputType(NodePolicyOutput{})
	pulumi.RegisterOutputType(NodePolicyArrayOutput{})
	pulumi.RegisterOutputType(NodePolicyMapOutput{})
}
