// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WorkloadRule struct {
	pulumi.CustomResourceState

	// When to apply recommendations. Valid values: 'on_detection', 'on_schedule'. Example: ["on_detection"].
	ActionTriggers pulumi.StringArrayOutput `pulumi:"actionTriggers"`
	// When true the engine generates all rule fields automatically; manual field overrides are ignored. Example: false.
	AutoGenerate pulumi.BoolPtrOutput `pulumi:"autoGenerate"`
	// ID of the cluster this rule targets. Example: 'cluster-abc123'.
	ClusterId pulumi.StringOutput `pulumi:"clusterId"`
	// Per-container resource rule configurations. When empty, workload-level rules apply to all containers.
	Containers ContainerResourceRuleConfigArgsArrayOutput `pulumi:"containers"`
	// Minimum minutes between consecutive recommendation applications. Example: 60.
	CooldownMinutes pulumi.IntPtrOutput `pulumi:"cooldownMinutes"`
	// CPU vertical scaling rule configuration.
	CpuRule ResourceRuleConfigArgsPtrOutput `pulumi:"cpuRule"`
	// Cron expression for scheduled application (5-field UTC). Example: '0 2 * * *'.
	CronSchedule pulumi.StringPtrOutput `pulumi:"cronSchedule"`
	// Cron expression for node defragmentation. Example: '0 3 * * 0'.
	DefragmentationSchedule pulumi.StringPtrOutput `pulumi:"defragmentationSchedule"`
	// Events that trigger a recommendation. Valid values: 'pod_creation', 'pod_update', 'pod_reschedule'. Example: ["pod_creation"].
	DetectionTriggers pulumi.StringArrayOutput `pulumi:"detectionTriggers"`
	// Emergency response configuration for OOM and CPU throttle events.
	EmergencyResponse EmergencyResponseConfigArgsPtrOutput `pulumi:"emergencyResponse"`
	// GPU vertical scaling rule configuration.
	GpuRule ResourceRuleConfigArgsPtrOutput `pulumi:"gpuRule"`
	// Horizontal (replica) scaling rule configuration.
	HpaRule HPARuleConfigArgsPtrOutput `pulumi:"hpaRule"`
	// Kubernetes workload kind. One of: 'Deployment', 'StatefulSet', 'DaemonSet', 'CronJob', 'Job'. Example: 'Deployment'.
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Allow live pod migration when applying recommendations. Example: false.
	LiveMigrationEnabled pulumi.BoolPtrOutput `pulumi:"liveMigrationEnabled"`
	// Memory vertical scaling rule configuration.
	MemoryRule ResourceRuleConfigArgsPtrOutput `pulumi:"memoryRule"`
	// Name of the Kubernetes workload. Example: 'my-api'.
	Name pulumi.StringOutput `pulumi:"name"`
	// Kubernetes namespace of the workload. Example: 'production'.
	Namespace pulumi.StringOutput `pulumi:"namespace"`
	// Kubernetes scheduler plugins to activate. Example: ["binpacking"].
	SchedulerPlugins pulumi.StringArrayOutput `pulumi:"schedulerPlugins"`
	// Seconds after workload start to exclude from usage data. Example: 300.
	StartupPeriodSeconds pulumi.IntPtrOutput `pulumi:"startupPeriodSeconds"`
	// Use in-place pod vertical scaling instead of pod restarts. Example: false.
	UseInPlaceVerticalScaling pulumi.BoolPtrOutput `pulumi:"useInPlaceVerticalScaling"`
}

// NewWorkloadRule registers a new resource with the given unique name, arguments, and options.
func NewWorkloadRule(ctx *pulumi.Context,
	name string, args *WorkloadRuleArgs, opts ...pulumi.ResourceOption) (*WorkloadRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterId == nil {
		return nil, errors.New("invalid value for required argument 'ClusterId'")
	}
	if args.Kind == nil {
		return nil, errors.New("invalid value for required argument 'Kind'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Namespace == nil {
		return nil, errors.New("invalid value for required argument 'Namespace'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkloadRule
	err := ctx.RegisterResource("devzero:resources:WorkloadRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkloadRule gets an existing WorkloadRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkloadRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkloadRuleState, opts ...pulumi.ResourceOption) (*WorkloadRule, error) {
	var resource WorkloadRule
	err := ctx.ReadResource("devzero:resources:WorkloadRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkloadRule resources.
type workloadRuleState struct {
}

type WorkloadRuleState struct {
}

func (WorkloadRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadRuleState)(nil)).Elem()
}

type workloadRuleArgs struct {
	// When to apply recommendations. Valid values: 'on_detection', 'on_schedule'. Example: ["on_detection"].
	ActionTriggers []string `pulumi:"actionTriggers"`
	// When true the engine generates all rule fields automatically; manual field overrides are ignored. Example: false.
	AutoGenerate *bool `pulumi:"autoGenerate"`
	// ID of the cluster this rule targets. Example: 'cluster-abc123'.
	ClusterId string `pulumi:"clusterId"`
	// Per-container resource rule configurations. When empty, workload-level rules apply to all containers.
	Containers []ContainerResourceRuleConfigArgs `pulumi:"containers"`
	// Minimum minutes between consecutive recommendation applications. Example: 60.
	CooldownMinutes *int `pulumi:"cooldownMinutes"`
	// CPU vertical scaling rule configuration.
	CpuRule *ResourceRuleConfigArgs `pulumi:"cpuRule"`
	// Cron expression for scheduled application (5-field UTC). Example: '0 2 * * *'.
	CronSchedule *string `pulumi:"cronSchedule"`
	// Cron expression for node defragmentation. Example: '0 3 * * 0'.
	DefragmentationSchedule *string `pulumi:"defragmentationSchedule"`
	// Events that trigger a recommendation. Valid values: 'pod_creation', 'pod_update', 'pod_reschedule'. Example: ["pod_creation"].
	DetectionTriggers []string `pulumi:"detectionTriggers"`
	// Emergency response configuration for OOM and CPU throttle events.
	EmergencyResponse *EmergencyResponseConfigArgs `pulumi:"emergencyResponse"`
	// GPU vertical scaling rule configuration.
	GpuRule *ResourceRuleConfigArgs `pulumi:"gpuRule"`
	// Horizontal (replica) scaling rule configuration.
	HpaRule *HPARuleConfigArgs `pulumi:"hpaRule"`
	// Kubernetes workload kind. One of: 'Deployment', 'StatefulSet', 'DaemonSet', 'CronJob', 'Job'. Example: 'Deployment'.
	Kind string `pulumi:"kind"`
	// Allow live pod migration when applying recommendations. Example: false.
	LiveMigrationEnabled *bool `pulumi:"liveMigrationEnabled"`
	// Memory vertical scaling rule configuration.
	MemoryRule *ResourceRuleConfigArgs `pulumi:"memoryRule"`
	// Name of the Kubernetes workload. Example: 'my-api'.
	Name string `pulumi:"name"`
	// Kubernetes namespace of the workload. Example: 'production'.
	Namespace string `pulumi:"namespace"`
	// Kubernetes scheduler plugins to activate. Example: ["binpacking"].
	SchedulerPlugins []string `pulumi:"schedulerPlugins"`
	// Seconds after workload start to exclude from usage data. Example: 300.
	StartupPeriodSeconds *int `pulumi:"startupPeriodSeconds"`
	// Use in-place pod vertical scaling instead of pod restarts. Example: false.
	UseInPlaceVerticalScaling *bool `pulumi:"useInPlaceVerticalScaling"`
}

// The set of arguments for constructing a WorkloadRule resource.
type WorkloadRuleArgs struct {
	// When to apply recommendations. Valid values: 'on_detection', 'on_schedule'. Example: ["on_detection"].
	ActionTriggers pulumi.StringArrayInput
	// When true the engine generates all rule fields automatically; manual field overrides are ignored. Example: false.
	AutoGenerate pulumi.BoolPtrInput
	// ID of the cluster this rule targets. Example: 'cluster-abc123'.
	ClusterId pulumi.StringInput
	// Per-container resource rule configurations. When empty, workload-level rules apply to all containers.
	Containers ContainerResourceRuleConfigArgsArrayInput
	// Minimum minutes between consecutive recommendation applications. Example: 60.
	CooldownMinutes pulumi.IntPtrInput
	// CPU vertical scaling rule configuration.
	CpuRule ResourceRuleConfigArgsPtrInput
	// Cron expression for scheduled application (5-field UTC). Example: '0 2 * * *'.
	CronSchedule pulumi.StringPtrInput
	// Cron expression for node defragmentation. Example: '0 3 * * 0'.
	DefragmentationSchedule pulumi.StringPtrInput
	// Events that trigger a recommendation. Valid values: 'pod_creation', 'pod_update', 'pod_reschedule'. Example: ["pod_creation"].
	DetectionTriggers pulumi.StringArrayInput
	// Emergency response configuration for OOM and CPU throttle events.
	EmergencyResponse EmergencyResponseConfigArgsPtrInput
	// GPU vertical scaling rule configuration.
	GpuRule ResourceRuleConfigArgsPtrInput
	// Horizontal (replica) scaling rule configuration.
	HpaRule HPARuleConfigArgsPtrInput
	// Kubernetes workload kind. One of: 'Deployment', 'StatefulSet', 'DaemonSet', 'CronJob', 'Job'. Example: 'Deployment'.
	Kind pulumi.StringInput
	// Allow live pod migration when applying recommendations. Example: false.
	LiveMigrationEnabled pulumi.BoolPtrInput
	// Memory vertical scaling rule configuration.
	MemoryRule ResourceRuleConfigArgsPtrInput
	// Name of the Kubernetes workload. Example: 'my-api'.
	Name pulumi.StringInput
	// Kubernetes namespace of the workload. Example: 'production'.
	Namespace pulumi.StringInput
	// Kubernetes scheduler plugins to activate. Example: ["binpacking"].
	SchedulerPlugins pulumi.StringArrayInput
	// Seconds after workload start to exclude from usage data. Example: 300.
	StartupPeriodSeconds pulumi.IntPtrInput
	// Use in-place pod vertical scaling instead of pod restarts. Example: false.
	UseInPlaceVerticalScaling pulumi.BoolPtrInput
}

func (WorkloadRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadRuleArgs)(nil)).Elem()
}

type WorkloadRuleInput interface {
	pulumi.Input

	ToWorkloadRuleOutput() WorkloadRuleOutput
	ToWorkloadRuleOutputWithContext(ctx context.Context) WorkloadRuleOutput
}

func (*WorkloadRule) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadRule)(nil)).Elem()
}

func (i *WorkloadRule) ToWorkloadRuleOutput() WorkloadRuleOutput {
	return i.ToWorkloadRuleOutputWithContext(context.Background())
}

func (i *WorkloadRule) ToWorkloadRuleOutputWithContext(ctx context.Context) WorkloadRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadRuleOutput)
}

// WorkloadRuleArrayInput is an input type that accepts WorkloadRuleArray and WorkloadRuleArrayOutput values.
// You can construct a concrete instance of `WorkloadRuleArrayInput` via:
//
//	WorkloadRuleArray{ WorkloadRuleArgs{...} }
type WorkloadRuleArrayInput interface {
	pulumi.Input

	ToWorkloadRuleArrayOutput() WorkloadRuleArrayOutput
	ToWorkloadRuleArrayOutputWithContext(context.Context) WorkloadRuleArrayOutput
}

type WorkloadRuleArray []WorkloadRuleInput

func (WorkloadRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadRule)(nil)).Elem()
}

func (i WorkloadRuleArray) ToWorkloadRuleArrayOutput() WorkloadRuleArrayOutput {
	return i.ToWorkloadRuleArrayOutputWithContext(context.Background())
}

func (i WorkloadRuleArray) ToWorkloadRuleArrayOutputWithContext(ctx context.Context) WorkloadRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadRuleArrayOutput)
}

// WorkloadRuleMapInput is an input type that accepts WorkloadRuleMap and WorkloadRuleMapOutput values.
// You can construct a concrete instance of `WorkloadRuleMapInput` via:
//
//	WorkloadRuleMap{ "key": WorkloadRuleArgs{...} }
type WorkloadRuleMapInput interface {
	pulumi.Input

	ToWorkloadRuleMapOutput() WorkloadRuleMapOutput
	ToWorkloadRuleMapOutputWithContext(context.Context) WorkloadRuleMapOutput
}

type WorkloadRuleMap map[string]WorkloadRuleInput

func (WorkloadRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadRule)(nil)).Elem()
}

func (i WorkloadRuleMap) ToWorkloadRuleMapOutput() WorkloadRuleMapOutput {
	return i.ToWorkloadRuleMapOutputWithContext(context.Background())
}

func (i WorkloadRuleMap) ToWorkloadRuleMapOutputWithContext(ctx context.Context) WorkloadRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadRuleMapOutput)
}

type WorkloadRuleOutput struct{ *pulumi.OutputState }

func (WorkloadRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadRule)(nil)).Elem()
}

func (o WorkloadRuleOutput) ToWorkloadRuleOutput() WorkloadRuleOutput {
	return o
}

func (o WorkloadRuleOutput) ToWorkloadRuleOutputWithContext(ctx context.Context) WorkloadRuleOutput {
	return o
}

// When to apply recommendations. Valid values: 'on_detection', 'on_schedule'. Example: ["on_detection"].
func (o WorkloadRuleOutput) ActionTriggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringArrayOutput { return v.ActionTriggers }).(pulumi.StringArrayOutput)
}

// When true the engine generates all rule fields automatically; manual field overrides are ignored. Example: false.
func (o WorkloadRuleOutput) AutoGenerate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.BoolPtrOutput { return v.AutoGenerate }).(pulumi.BoolPtrOutput)
}

// ID of the cluster this rule targets. Example: 'cluster-abc123'.
func (o WorkloadRuleOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringOutput { return v.ClusterId }).(pulumi.StringOutput)
}

// Per-container resource rule configurations. When empty, workload-level rules apply to all containers.
func (o WorkloadRuleOutput) Containers() ContainerResourceRuleConfigArgsArrayOutput {
	return o.ApplyT(func(v *WorkloadRule) ContainerResourceRuleConfigArgsArrayOutput { return v.Containers }).(ContainerResourceRuleConfigArgsArrayOutput)
}

// Minimum minutes between consecutive recommendation applications. Example: 60.
func (o WorkloadRuleOutput) CooldownMinutes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.IntPtrOutput { return v.CooldownMinutes }).(pulumi.IntPtrOutput)
}

// CPU vertical scaling rule configuration.
func (o WorkloadRuleOutput) CpuRule() ResourceRuleConfigArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) ResourceRuleConfigArgsPtrOutput { return v.CpuRule }).(ResourceRuleConfigArgsPtrOutput)
}

// Cron expression for scheduled application (5-field UTC). Example: '0 2 * * *'.
func (o WorkloadRuleOutput) CronSchedule() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringPtrOutput { return v.CronSchedule }).(pulumi.StringPtrOutput)
}

// Cron expression for node defragmentation. Example: '0 3 * * 0'.
func (o WorkloadRuleOutput) DefragmentationSchedule() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringPtrOutput { return v.DefragmentationSchedule }).(pulumi.StringPtrOutput)
}

// Events that trigger a recommendation. Valid values: 'pod_creation', 'pod_update', 'pod_reschedule'. Example: ["pod_creation"].
func (o WorkloadRuleOutput) DetectionTriggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringArrayOutput { return v.DetectionTriggers }).(pulumi.StringArrayOutput)
}

// Emergency response configuration for OOM and CPU throttle events.
func (o WorkloadRuleOutput) EmergencyResponse() EmergencyResponseConfigArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) EmergencyResponseConfigArgsPtrOutput { return v.EmergencyResponse }).(EmergencyResponseConfigArgsPtrOutput)
}

// GPU vertical scaling rule configuration.
func (o WorkloadRuleOutput) GpuRule() ResourceRuleConfigArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) ResourceRuleConfigArgsPtrOutput { return v.GpuRule }).(ResourceRuleConfigArgsPtrOutput)
}

// Horizontal (replica) scaling rule configuration.
func (o WorkloadRuleOutput) HpaRule() HPARuleConfigArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) HPARuleConfigArgsPtrOutput { return v.HpaRule }).(HPARuleConfigArgsPtrOutput)
}

// Kubernetes workload kind. One of: 'Deployment', 'StatefulSet', 'DaemonSet', 'CronJob', 'Job'. Example: 'Deployment'.
func (o WorkloadRuleOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Allow live pod migration when applying recommendations. Example: false.
func (o WorkloadRuleOutput) LiveMigrationEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.BoolPtrOutput { return v.LiveMigrationEnabled }).(pulumi.BoolPtrOutput)
}

// Memory vertical scaling rule configuration.
func (o WorkloadRuleOutput) MemoryRule() ResourceRuleConfigArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) ResourceRuleConfigArgsPtrOutput { return v.MemoryRule }).(ResourceRuleConfigArgsPtrOutput)
}

// Name of the Kubernetes workload. Example: 'my-api'.
func (o WorkloadRuleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Kubernetes namespace of the workload. Example: 'production'.
func (o WorkloadRuleOutput) Namespace() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringOutput { return v.Namespace }).(pulumi.StringOutput)
}

// Kubernetes scheduler plugins to activate. Example: ["binpacking"].
func (o WorkloadRuleOutput) SchedulerPlugins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.StringArrayOutput { return v.SchedulerPlugins }).(pulumi.StringArrayOutput)
}

// Seconds after workload start to exclude from usage data. Example: 300.
func (o WorkloadRuleOutput) StartupPeriodSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.IntPtrOutput { return v.StartupPeriodSeconds }).(pulumi.IntPtrOutput)
}

// Use in-place pod vertical scaling instead of pod restarts. Example: false.
func (o WorkloadRuleOutput) UseInPlaceVerticalScaling() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkloadRule) pulumi.BoolPtrOutput { return v.UseInPlaceVerticalScaling }).(pulumi.BoolPtrOutput)
}

type WorkloadRuleArrayOutput struct{ *pulumi.OutputState }

func (WorkloadRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadRule)(nil)).Elem()
}

func (o WorkloadRuleArrayOutput) ToWorkloadRuleArrayOutput() WorkloadRuleArrayOutput {
	return o
}

func (o WorkloadRuleArrayOutput) ToWorkloadRuleArrayOutputWithContext(ctx context.Context) WorkloadRuleArrayOutput {
	return o
}

func (o WorkloadRuleArrayOutput) Index(i pulumi.IntInput) WorkloadRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkloadRule {
		return vs[0].([]*WorkloadRule)[vs[1].(int)]
	}).(WorkloadRuleOutput)
}

type WorkloadRuleMapOutput struct{ *pulumi.OutputState }

func (WorkloadRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadRule)(nil)).Elem()
}

func (o WorkloadRuleMapOutput) ToWorkloadRuleMapOutput() WorkloadRuleMapOutput {
	return o
}

func (o WorkloadRuleMapOutput) ToWorkloadRuleMapOutputWithContext(ctx context.Context) WorkloadRuleMapOutput {
	return o
}

func (o WorkloadRuleMapOutput) MapIndex(k pulumi.StringInput) WorkloadRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkloadRule {
		return vs[0].(map[string]*WorkloadRule)[vs[1].(string)]
	}).(WorkloadRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadRuleInput)(nil)).Elem(), &WorkloadRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadRuleArrayInput)(nil)).Elem(), WorkloadRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadRuleMapInput)(nil)).Elem(), WorkloadRuleMap{})
	pulumi.RegisterOutputType(WorkloadRuleOutput{})
	pulumi.RegisterOutputType(WorkloadRuleArrayOutput{})
	pulumi.RegisterOutputType(WorkloadRuleMapOutput{})
}
