// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WorkloadPolicyTarget struct {
	pulumi.CustomResourceState

	// Cluster IDs where this target applies.
	ClusterIds pulumi.StringArrayOutput `pulumi:"clusterIds"`
	// Free-form description of the target.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Enable or disable this target.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Restrict matching to specific Kubernetes kinds (e.g. Deployment, Pod).
	KindFilter pulumi.StringArrayOutput `pulumi:"kindFilter"`
	// Human-friendly name for this target.
	Name pulumi.StringOutput `pulumi:"name"`
	// Regex to match workload names.
	NamePattern NamePatternArgsPtrOutput `pulumi:"namePattern"`
	// Select namespaces by labels.
	NamespaceSelector LabelSelectorArgsPtrOutput `pulumi:"namespaceSelector"`
	// Restrict matching to specific node groups by name.
	NodeGroupNames pulumi.StringArrayOutput `pulumi:"nodeGroupNames"`
	// Workload policy ID this target is attached to.
	PolicyId pulumi.StringOutput `pulumi:"policyId"`
	// Evaluation priority; higher values take precedence when targets overlap.
	Priority pulumi.IntPtrOutput `pulumi:"priority"`
	// Explicit list of workload names to include.
	WorkloadNames pulumi.StringArrayOutput `pulumi:"workloadNames"`
	// Select workloads by labels.
	WorkloadSelector LabelSelectorArgsPtrOutput `pulumi:"workloadSelector"`
}

// NewWorkloadPolicyTarget registers a new resource with the given unique name, arguments, and options.
func NewWorkloadPolicyTarget(ctx *pulumi.Context,
	name string, args *WorkloadPolicyTargetArgs, opts ...pulumi.ResourceOption) (*WorkloadPolicyTarget, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterIds == nil {
		return nil, errors.New("invalid value for required argument 'ClusterIds'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.PolicyId == nil {
		return nil, errors.New("invalid value for required argument 'PolicyId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkloadPolicyTarget
	err := ctx.RegisterResource("devzero:resources:WorkloadPolicyTarget", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkloadPolicyTarget gets an existing WorkloadPolicyTarget resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkloadPolicyTarget(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkloadPolicyTargetState, opts ...pulumi.ResourceOption) (*WorkloadPolicyTarget, error) {
	var resource WorkloadPolicyTarget
	err := ctx.ReadResource("devzero:resources:WorkloadPolicyTarget", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkloadPolicyTarget resources.
type workloadPolicyTargetState struct {
}

type WorkloadPolicyTargetState struct {
}

func (WorkloadPolicyTargetState) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadPolicyTargetState)(nil)).Elem()
}

type workloadPolicyTargetArgs struct {
	ClusterIds        []string           `pulumi:"clusterIds"`
	Description       *string            `pulumi:"description"`
	Enabled           *bool              `pulumi:"enabled"`
	KindFilter        []string           `pulumi:"kindFilter"`
	Name              string             `pulumi:"name"`
	NamePattern       *NamePatternArgs   `pulumi:"namePattern"`
	NamespaceSelector *LabelSelectorArgs `pulumi:"namespaceSelector"`
	NodeGroupNames    []string           `pulumi:"nodeGroupNames"`
	PolicyId          string             `pulumi:"policyId"`
	Priority          *int               `pulumi:"priority"`
	WorkloadNames     []string           `pulumi:"workloadNames"`
	WorkloadSelector  *LabelSelectorArgs `pulumi:"workloadSelector"`
}

// The set of arguments for constructing a WorkloadPolicyTarget resource.
type WorkloadPolicyTargetArgs struct {
	ClusterIds        pulumi.StringArrayInput
	Description       pulumi.StringPtrInput
	Enabled           pulumi.BoolPtrInput
	KindFilter        pulumi.StringArrayInput
	Name              pulumi.StringInput
	NamePattern       NamePatternArgsPtrInput
	NamespaceSelector LabelSelectorArgsPtrInput
	NodeGroupNames    pulumi.StringArrayInput
	PolicyId          pulumi.StringInput
	Priority          pulumi.IntPtrInput
	WorkloadNames     pulumi.StringArrayInput
	WorkloadSelector  LabelSelectorArgsPtrInput
}

func (WorkloadPolicyTargetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadPolicyTargetArgs)(nil)).Elem()
}

type WorkloadPolicyTargetInput interface {
	pulumi.Input

	ToWorkloadPolicyTargetOutput() WorkloadPolicyTargetOutput
	ToWorkloadPolicyTargetOutputWithContext(ctx context.Context) WorkloadPolicyTargetOutput
}

func (*WorkloadPolicyTarget) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadPolicyTarget)(nil)).Elem()
}

func (i *WorkloadPolicyTarget) ToWorkloadPolicyTargetOutput() WorkloadPolicyTargetOutput {
	return i.ToWorkloadPolicyTargetOutputWithContext(context.Background())
}

func (i *WorkloadPolicyTarget) ToWorkloadPolicyTargetOutputWithContext(ctx context.Context) WorkloadPolicyTargetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyTargetOutput)
}

// WorkloadPolicyTargetArrayInput is an input type that accepts WorkloadPolicyTargetArray and WorkloadPolicyTargetArrayOutput values.
// You can construct a concrete instance of `WorkloadPolicyTargetArrayInput` via:
//
//	WorkloadPolicyTargetArray{ WorkloadPolicyTargetArgs{...} }
type WorkloadPolicyTargetArrayInput interface {
	pulumi.Input

	ToWorkloadPolicyTargetArrayOutput() WorkloadPolicyTargetArrayOutput
	ToWorkloadPolicyTargetArrayOutputWithContext(context.Context) WorkloadPolicyTargetArrayOutput
}

type WorkloadPolicyTargetArray []WorkloadPolicyTargetInput

func (WorkloadPolicyTargetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadPolicyTarget)(nil)).Elem()
}

func (i WorkloadPolicyTargetArray) ToWorkloadPolicyTargetArrayOutput() WorkloadPolicyTargetArrayOutput {
	return i.ToWorkloadPolicyTargetArrayOutputWithContext(context.Background())
}

func (i WorkloadPolicyTargetArray) ToWorkloadPolicyTargetArrayOutputWithContext(ctx context.Context) WorkloadPolicyTargetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyTargetArrayOutput)
}

// WorkloadPolicyTargetMapInput is an input type that accepts WorkloadPolicyTargetMap and WorkloadPolicyTargetMapOutput values.
// You can construct a concrete instance of `WorkloadPolicyTargetMapInput` via:
//
//	WorkloadPolicyTargetMap{ "key": WorkloadPolicyTargetArgs{...} }
type WorkloadPolicyTargetMapInput interface {
	pulumi.Input

	ToWorkloadPolicyTargetMapOutput() WorkloadPolicyTargetMapOutput
	ToWorkloadPolicyTargetMapOutputWithContext(context.Context) WorkloadPolicyTargetMapOutput
}

type WorkloadPolicyTargetMap map[string]WorkloadPolicyTargetInput

func (WorkloadPolicyTargetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadPolicyTarget)(nil)).Elem()
}

func (i WorkloadPolicyTargetMap) ToWorkloadPolicyTargetMapOutput() WorkloadPolicyTargetMapOutput {
	return i.ToWorkloadPolicyTargetMapOutputWithContext(context.Background())
}

func (i WorkloadPolicyTargetMap) ToWorkloadPolicyTargetMapOutputWithContext(ctx context.Context) WorkloadPolicyTargetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyTargetMapOutput)
}

type WorkloadPolicyTargetOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyTargetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadPolicyTarget)(nil)).Elem()
}

func (o WorkloadPolicyTargetOutput) ToWorkloadPolicyTargetOutput() WorkloadPolicyTargetOutput {
	return o
}

func (o WorkloadPolicyTargetOutput) ToWorkloadPolicyTargetOutputWithContext(ctx context.Context) WorkloadPolicyTargetOutput {
	return o
}

// Cluster IDs where this target applies.
func (o WorkloadPolicyTargetOutput) ClusterIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.StringArrayOutput { return v.ClusterIds }).(pulumi.StringArrayOutput)
}

// Free-form description of the target.
func (o WorkloadPolicyTargetOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Enable or disable this target.
func (o WorkloadPolicyTargetOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Restrict matching to specific Kubernetes kinds (e.g. Deployment, Pod).
func (o WorkloadPolicyTargetOutput) KindFilter() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.StringArrayOutput { return v.KindFilter }).(pulumi.StringArrayOutput)
}

// Human-friendly name for this target.
func (o WorkloadPolicyTargetOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Regex to match workload names.
func (o WorkloadPolicyTargetOutput) NamePattern() NamePatternArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) NamePatternArgsPtrOutput { return v.NamePattern }).(NamePatternArgsPtrOutput)
}

// Select namespaces by labels.
func (o WorkloadPolicyTargetOutput) NamespaceSelector() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) LabelSelectorArgsPtrOutput { return v.NamespaceSelector }).(LabelSelectorArgsPtrOutput)
}

// Restrict matching to specific node groups by name.
func (o WorkloadPolicyTargetOutput) NodeGroupNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.StringArrayOutput { return v.NodeGroupNames }).(pulumi.StringArrayOutput)
}

// Workload policy ID this target is attached to.
func (o WorkloadPolicyTargetOutput) PolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.StringOutput { return v.PolicyId }).(pulumi.StringOutput)
}

// Evaluation priority; higher values take precedence when targets overlap.
func (o WorkloadPolicyTargetOutput) Priority() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.IntPtrOutput { return v.Priority }).(pulumi.IntPtrOutput)
}

// Explicit list of workload names to include.
func (o WorkloadPolicyTargetOutput) WorkloadNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) pulumi.StringArrayOutput { return v.WorkloadNames }).(pulumi.StringArrayOutput)
}

// Select workloads by labels.
func (o WorkloadPolicyTargetOutput) WorkloadSelector() LabelSelectorArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicyTarget) LabelSelectorArgsPtrOutput { return v.WorkloadSelector }).(LabelSelectorArgsPtrOutput)
}

type WorkloadPolicyTargetArrayOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyTargetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadPolicyTarget)(nil)).Elem()
}

func (o WorkloadPolicyTargetArrayOutput) ToWorkloadPolicyTargetArrayOutput() WorkloadPolicyTargetArrayOutput {
	return o
}

func (o WorkloadPolicyTargetArrayOutput) ToWorkloadPolicyTargetArrayOutputWithContext(ctx context.Context) WorkloadPolicyTargetArrayOutput {
	return o
}

func (o WorkloadPolicyTargetArrayOutput) Index(i pulumi.IntInput) WorkloadPolicyTargetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkloadPolicyTarget {
		return vs[0].([]*WorkloadPolicyTarget)[vs[1].(int)]
	}).(WorkloadPolicyTargetOutput)
}

type WorkloadPolicyTargetMapOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyTargetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadPolicyTarget)(nil)).Elem()
}

func (o WorkloadPolicyTargetMapOutput) ToWorkloadPolicyTargetMapOutput() WorkloadPolicyTargetMapOutput {
	return o
}

func (o WorkloadPolicyTargetMapOutput) ToWorkloadPolicyTargetMapOutputWithContext(ctx context.Context) WorkloadPolicyTargetMapOutput {
	return o
}

func (o WorkloadPolicyTargetMapOutput) MapIndex(k pulumi.StringInput) WorkloadPolicyTargetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkloadPolicyTarget {
		return vs[0].(map[string]*WorkloadPolicyTarget)[vs[1].(string)]
	}).(WorkloadPolicyTargetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyTargetInput)(nil)).Elem(), &WorkloadPolicyTarget{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyTargetArrayInput)(nil)).Elem(), WorkloadPolicyTargetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyTargetMapInput)(nil)).Elem(), WorkloadPolicyTargetMap{})
	pulumi.RegisterOutputType(WorkloadPolicyTargetOutput{})
	pulumi.RegisterOutputType(WorkloadPolicyTargetArrayOutput{})
	pulumi.RegisterOutputType(WorkloadPolicyTargetMapOutput{})
}
