// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WorkloadPolicy struct {
	pulumi.CustomResourceState

	// Action triggers: 'on_detection' or 'on_schedule'.
	ActionTriggers pulumi.StringArrayOutput `pulumi:"actionTriggers"`
	// Minutes to wait between applying recommendations.
	CooldownMinutes    pulumi.IntPtrOutput          `pulumi:"cooldownMinutes"`
	CpuVerticalScaling VerticalScalingArgsPtrOutput `pulumi:"cpuVerticalScaling"`
	// Cron expression for scheduled application (5-field format).
	CronSchedule pulumi.StringPtrOutput `pulumi:"cronSchedule"`
	// Cron expression for background defragmentation.
	DefragmentationSchedule pulumi.StringPtrOutput `pulumi:"defragmentationSchedule"`
	// Free-form description of the policy.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
	DetectionTriggers pulumi.StringArrayOutput `pulumi:"detectionTriggers"`
	// Percentage drift from baseline that triggers VPA refresh.
	DriftDeltaPercent      pulumi.Float64PtrOutput        `pulumi:"driftDeltaPercent"`
	GpuVerticalScaling     VerticalScalingArgsPtrOutput   `pulumi:"gpuVerticalScaling"`
	GpuVramVerticalScaling VerticalScalingArgsPtrOutput   `pulumi:"gpuVramVerticalScaling"`
	HorizontalScaling      HorizontalScalingArgsPtrOutput `pulumi:"horizontalScaling"`
	// Hysteresis threshold vs target for HPA coordination.
	HysteresisVsTarget pulumi.Float64PtrOutput `pulumi:"hysteresisVsTarget"`
	// Allow live migration when applying recommendations.
	LiveMigrationEnabled pulumi.BoolPtrOutput `pulumi:"liveMigrationEnabled"`
	// Period in seconds to look back for resource usage data.
	LoopbackPeriodSeconds pulumi.IntPtrOutput          `pulumi:"loopbackPeriodSeconds"`
	MemoryVerticalScaling VerticalScalingArgsPtrOutput `pulumi:"memoryVerticalScaling"`
	// Global minimum change threshold for applying recommendations.
	MinChangePercent pulumi.Float64PtrOutput `pulumi:"minChangePercent"`
	// Global minimum data points required for recommendations.
	MinDataPoints pulumi.IntPtrOutput `pulumi:"minDataPoints"`
	// Minimum data points in VPA analysis window.
	MinVpaWindowDataPoints pulumi.IntPtrOutput `pulumi:"minVpaWindowDataPoints"`
	// Human-friendly name for the policy.
	Name pulumi.StringOutput `pulumi:"name"`
	// Kubernetes scheduler plugins to activate.
	SchedulerPlugins pulumi.StringArrayOutput `pulumi:"schedulerPlugins"`
	// Maximum coefficient of variation for workload to be considered stable.
	StabilityCvMax pulumi.Float64PtrOutput `pulumi:"stabilityCvMax"`
	// Period in seconds to ignore usage data after workload starts.
	StartupPeriodSeconds pulumi.IntPtrOutput `pulumi:"startupPeriodSeconds"`
}

// NewWorkloadPolicy registers a new resource with the given unique name, arguments, and options.
func NewWorkloadPolicy(ctx *pulumi.Context,
	name string, args *WorkloadPolicyArgs, opts ...pulumi.ResourceOption) (*WorkloadPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkloadPolicy
	err := ctx.RegisterResource("devzero:resources:WorkloadPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkloadPolicy gets an existing WorkloadPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkloadPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkloadPolicyState, opts ...pulumi.ResourceOption) (*WorkloadPolicy, error) {
	var resource WorkloadPolicy
	err := ctx.ReadResource("devzero:resources:WorkloadPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkloadPolicy resources.
type workloadPolicyState struct {
}

type WorkloadPolicyState struct {
}

func (WorkloadPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadPolicyState)(nil)).Elem()
}

type workloadPolicyArgs struct {
	ActionTriggers          []string               `pulumi:"actionTriggers"`
	CooldownMinutes         *int                   `pulumi:"cooldownMinutes"`
	CpuVerticalScaling      *VerticalScalingArgs   `pulumi:"cpuVerticalScaling"`
	CronSchedule            *string                `pulumi:"cronSchedule"`
	DefragmentationSchedule *string                `pulumi:"defragmentationSchedule"`
	Description             *string                `pulumi:"description"`
	DetectionTriggers       []string               `pulumi:"detectionTriggers"`
	DriftDeltaPercent       *float64               `pulumi:"driftDeltaPercent"`
	GpuVerticalScaling      *VerticalScalingArgs   `pulumi:"gpuVerticalScaling"`
	GpuVramVerticalScaling  *VerticalScalingArgs   `pulumi:"gpuVramVerticalScaling"`
	HorizontalScaling       *HorizontalScalingArgs `pulumi:"horizontalScaling"`
	HysteresisVsTarget      *float64               `pulumi:"hysteresisVsTarget"`
	LiveMigrationEnabled    *bool                  `pulumi:"liveMigrationEnabled"`
	LoopbackPeriodSeconds   *int                   `pulumi:"loopbackPeriodSeconds"`
	MemoryVerticalScaling   *VerticalScalingArgs   `pulumi:"memoryVerticalScaling"`
	MinChangePercent        *float64               `pulumi:"minChangePercent"`
	MinDataPoints           *int                   `pulumi:"minDataPoints"`
	MinVpaWindowDataPoints  *int                   `pulumi:"minVpaWindowDataPoints"`
	Name                    string                 `pulumi:"name"`
	SchedulerPlugins        []string               `pulumi:"schedulerPlugins"`
	StabilityCvMax          *float64               `pulumi:"stabilityCvMax"`
	StartupPeriodSeconds    *int                   `pulumi:"startupPeriodSeconds"`
}

// The set of arguments for constructing a WorkloadPolicy resource.
type WorkloadPolicyArgs struct {
	ActionTriggers          pulumi.StringArrayInput
	CooldownMinutes         pulumi.IntPtrInput
	CpuVerticalScaling      VerticalScalingArgsPtrInput
	CronSchedule            pulumi.StringPtrInput
	DefragmentationSchedule pulumi.StringPtrInput
	Description             pulumi.StringPtrInput
	DetectionTriggers       pulumi.StringArrayInput
	DriftDeltaPercent       pulumi.Float64PtrInput
	GpuVerticalScaling      VerticalScalingArgsPtrInput
	GpuVramVerticalScaling  VerticalScalingArgsPtrInput
	HorizontalScaling       HorizontalScalingArgsPtrInput
	HysteresisVsTarget      pulumi.Float64PtrInput
	LiveMigrationEnabled    pulumi.BoolPtrInput
	LoopbackPeriodSeconds   pulumi.IntPtrInput
	MemoryVerticalScaling   VerticalScalingArgsPtrInput
	MinChangePercent        pulumi.Float64PtrInput
	MinDataPoints           pulumi.IntPtrInput
	MinVpaWindowDataPoints  pulumi.IntPtrInput
	Name                    pulumi.StringInput
	SchedulerPlugins        pulumi.StringArrayInput
	StabilityCvMax          pulumi.Float64PtrInput
	StartupPeriodSeconds    pulumi.IntPtrInput
}

func (WorkloadPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadPolicyArgs)(nil)).Elem()
}

type WorkloadPolicyInput interface {
	pulumi.Input

	ToWorkloadPolicyOutput() WorkloadPolicyOutput
	ToWorkloadPolicyOutputWithContext(ctx context.Context) WorkloadPolicyOutput
}

func (*WorkloadPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadPolicy)(nil)).Elem()
}

func (i *WorkloadPolicy) ToWorkloadPolicyOutput() WorkloadPolicyOutput {
	return i.ToWorkloadPolicyOutputWithContext(context.Background())
}

func (i *WorkloadPolicy) ToWorkloadPolicyOutputWithContext(ctx context.Context) WorkloadPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyOutput)
}

// WorkloadPolicyArrayInput is an input type that accepts WorkloadPolicyArray and WorkloadPolicyArrayOutput values.
// You can construct a concrete instance of `WorkloadPolicyArrayInput` via:
//
//	WorkloadPolicyArray{ WorkloadPolicyArgs{...} }
type WorkloadPolicyArrayInput interface {
	pulumi.Input

	ToWorkloadPolicyArrayOutput() WorkloadPolicyArrayOutput
	ToWorkloadPolicyArrayOutputWithContext(context.Context) WorkloadPolicyArrayOutput
}

type WorkloadPolicyArray []WorkloadPolicyInput

func (WorkloadPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadPolicy)(nil)).Elem()
}

func (i WorkloadPolicyArray) ToWorkloadPolicyArrayOutput() WorkloadPolicyArrayOutput {
	return i.ToWorkloadPolicyArrayOutputWithContext(context.Background())
}

func (i WorkloadPolicyArray) ToWorkloadPolicyArrayOutputWithContext(ctx context.Context) WorkloadPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyArrayOutput)
}

// WorkloadPolicyMapInput is an input type that accepts WorkloadPolicyMap and WorkloadPolicyMapOutput values.
// You can construct a concrete instance of `WorkloadPolicyMapInput` via:
//
//	WorkloadPolicyMap{ "key": WorkloadPolicyArgs{...} }
type WorkloadPolicyMapInput interface {
	pulumi.Input

	ToWorkloadPolicyMapOutput() WorkloadPolicyMapOutput
	ToWorkloadPolicyMapOutputWithContext(context.Context) WorkloadPolicyMapOutput
}

type WorkloadPolicyMap map[string]WorkloadPolicyInput

func (WorkloadPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadPolicy)(nil)).Elem()
}

func (i WorkloadPolicyMap) ToWorkloadPolicyMapOutput() WorkloadPolicyMapOutput {
	return i.ToWorkloadPolicyMapOutputWithContext(context.Background())
}

func (i WorkloadPolicyMap) ToWorkloadPolicyMapOutputWithContext(ctx context.Context) WorkloadPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyMapOutput)
}

type WorkloadPolicyOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadPolicy)(nil)).Elem()
}

func (o WorkloadPolicyOutput) ToWorkloadPolicyOutput() WorkloadPolicyOutput {
	return o
}

func (o WorkloadPolicyOutput) ToWorkloadPolicyOutputWithContext(ctx context.Context) WorkloadPolicyOutput {
	return o
}

// Action triggers: 'on_detection' or 'on_schedule'.
func (o WorkloadPolicyOutput) ActionTriggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringArrayOutput { return v.ActionTriggers }).(pulumi.StringArrayOutput)
}

// Minutes to wait between applying recommendations.
func (o WorkloadPolicyOutput) CooldownMinutes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.CooldownMinutes }).(pulumi.IntPtrOutput)
}

func (o WorkloadPolicyOutput) CpuVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.CpuVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

// Cron expression for scheduled application (5-field format).
func (o WorkloadPolicyOutput) CronSchedule() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringPtrOutput { return v.CronSchedule }).(pulumi.StringPtrOutput)
}

// Cron expression for background defragmentation.
func (o WorkloadPolicyOutput) DefragmentationSchedule() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringPtrOutput { return v.DefragmentationSchedule }).(pulumi.StringPtrOutput)
}

// Free-form description of the policy.
func (o WorkloadPolicyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
func (o WorkloadPolicyOutput) DetectionTriggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringArrayOutput { return v.DetectionTriggers }).(pulumi.StringArrayOutput)
}

// Percentage drift from baseline that triggers VPA refresh.
func (o WorkloadPolicyOutput) DriftDeltaPercent() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.DriftDeltaPercent }).(pulumi.Float64PtrOutput)
}

func (o WorkloadPolicyOutput) GpuVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.GpuVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

func (o WorkloadPolicyOutput) GpuVramVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.GpuVramVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

func (o WorkloadPolicyOutput) HorizontalScaling() HorizontalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) HorizontalScalingArgsPtrOutput { return v.HorizontalScaling }).(HorizontalScalingArgsPtrOutput)
}

// Hysteresis threshold vs target for HPA coordination.
func (o WorkloadPolicyOutput) HysteresisVsTarget() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.HysteresisVsTarget }).(pulumi.Float64PtrOutput)
}

// Allow live migration when applying recommendations.
func (o WorkloadPolicyOutput) LiveMigrationEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.BoolPtrOutput { return v.LiveMigrationEnabled }).(pulumi.BoolPtrOutput)
}

// Period in seconds to look back for resource usage data.
func (o WorkloadPolicyOutput) LoopbackPeriodSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.LoopbackPeriodSeconds }).(pulumi.IntPtrOutput)
}

func (o WorkloadPolicyOutput) MemoryVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.MemoryVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

// Global minimum change threshold for applying recommendations.
func (o WorkloadPolicyOutput) MinChangePercent() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.MinChangePercent }).(pulumi.Float64PtrOutput)
}

// Global minimum data points required for recommendations.
func (o WorkloadPolicyOutput) MinDataPoints() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.MinDataPoints }).(pulumi.IntPtrOutput)
}

// Minimum data points in VPA analysis window.
func (o WorkloadPolicyOutput) MinVpaWindowDataPoints() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.MinVpaWindowDataPoints }).(pulumi.IntPtrOutput)
}

// Human-friendly name for the policy.
func (o WorkloadPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Kubernetes scheduler plugins to activate.
func (o WorkloadPolicyOutput) SchedulerPlugins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringArrayOutput { return v.SchedulerPlugins }).(pulumi.StringArrayOutput)
}

// Maximum coefficient of variation for workload to be considered stable.
func (o WorkloadPolicyOutput) StabilityCvMax() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.StabilityCvMax }).(pulumi.Float64PtrOutput)
}

// Period in seconds to ignore usage data after workload starts.
func (o WorkloadPolicyOutput) StartupPeriodSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.StartupPeriodSeconds }).(pulumi.IntPtrOutput)
}

type WorkloadPolicyArrayOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadPolicy)(nil)).Elem()
}

func (o WorkloadPolicyArrayOutput) ToWorkloadPolicyArrayOutput() WorkloadPolicyArrayOutput {
	return o
}

func (o WorkloadPolicyArrayOutput) ToWorkloadPolicyArrayOutputWithContext(ctx context.Context) WorkloadPolicyArrayOutput {
	return o
}

func (o WorkloadPolicyArrayOutput) Index(i pulumi.IntInput) WorkloadPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkloadPolicy {
		return vs[0].([]*WorkloadPolicy)[vs[1].(int)]
	}).(WorkloadPolicyOutput)
}

type WorkloadPolicyMapOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadPolicy)(nil)).Elem()
}

func (o WorkloadPolicyMapOutput) ToWorkloadPolicyMapOutput() WorkloadPolicyMapOutput {
	return o
}

func (o WorkloadPolicyMapOutput) ToWorkloadPolicyMapOutputWithContext(ctx context.Context) WorkloadPolicyMapOutput {
	return o
}

func (o WorkloadPolicyMapOutput) MapIndex(k pulumi.StringInput) WorkloadPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkloadPolicy {
		return vs[0].(map[string]*WorkloadPolicy)[vs[1].(string)]
	}).(WorkloadPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyInput)(nil)).Elem(), &WorkloadPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyArrayInput)(nil)).Elem(), WorkloadPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyMapInput)(nil)).Elem(), WorkloadPolicyMap{})
	pulumi.RegisterOutputType(WorkloadPolicyOutput{})
	pulumi.RegisterOutputType(WorkloadPolicyArrayOutput{})
	pulumi.RegisterOutputType(WorkloadPolicyMapOutput{})
}
