// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"errors"
	"github.com/devzero-inc/pulumi-provider-devzero/sdk/go/devzero/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WorkloadPolicy struct {
	pulumi.CustomResourceState

	// Action triggers: 'on_detection' or 'on_schedule'.
	ActionTriggers pulumi.StringArrayOutput `pulumi:"actionTriggers"`
	// Minutes to wait between applying recommendations. Default: 300 (5 h).
	CooldownMinutes    pulumi.IntPtrOutput          `pulumi:"cooldownMinutes"`
	CpuVerticalScaling VerticalScalingArgsPtrOutput `pulumi:"cpuVerticalScaling"`
	// Cron expression for scheduled application (5-field format).
	CronSchedule pulumi.StringPtrOutput `pulumi:"cronSchedule"`
	// Cron expression for background defragmentation.
	DefragmentationSchedule pulumi.StringPtrOutput `pulumi:"defragmentationSchedule"`
	// Free-form description of the policy.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
	DetectionTriggers pulumi.StringArrayOutput `pulumi:"detectionTriggers"`
	// Percentage drift from baseline that triggers VPA refresh.
	DriftDeltaPercent pulumi.Float64PtrOutput `pulumi:"driftDeltaPercent"`
	// Raise requests to cover peak usage when max/recommendation ratio exceeds pmaxRatioThreshold. Server/web default: true.
	EnablePmaxProtection   pulumi.BoolPtrOutput           `pulumi:"enablePmaxProtection"`
	GpuVerticalScaling     VerticalScalingArgsPtrOutput   `pulumi:"gpuVerticalScaling"`
	GpuVramVerticalScaling VerticalScalingArgsPtrOutput   `pulumi:"gpuVramVerticalScaling"`
	HorizontalScaling      HorizontalScalingArgsPtrOutput `pulumi:"horizontalScaling"`
	// Hysteresis threshold vs target for HPA coordination.
	HysteresisVsTarget pulumi.Float64PtrOutput `pulumi:"hysteresisVsTarget"`
	// Allow live migration when applying recommendations.
	LiveMigrationEnabled pulumi.BoolPtrOutput `pulumi:"liveMigrationEnabled"`
	// Period in seconds to look back for resource usage data. Default: 86400 (24 h).
	LoopbackPeriodSeconds pulumi.IntPtrOutput          `pulumi:"loopbackPeriodSeconds"`
	MemoryVerticalScaling VerticalScalingArgsPtrOutput `pulumi:"memoryVerticalScaling"`
	// Global minimum change threshold for applying recommendations. Default: 0.2 (20%).
	MinChangePercent pulumi.Float64PtrOutput `pulumi:"minChangePercent"`
	// Global minimum data points required for recommendations. Default: 15.
	MinDataPoints pulumi.IntPtrOutput `pulumi:"minDataPoints"`
	// Minimum data points in VPA analysis window. Default: 30.
	MinVpaWindowDataPoints pulumi.IntPtrOutput `pulumi:"minVpaWindowDataPoints"`
	// Human-friendly name for the policy.
	Name pulumi.StringOutput `pulumi:"name"`
	// Max-to-recommendation ratio that triggers pmax protection. Default: 3.0.
	PmaxRatioThreshold pulumi.Float64PtrOutput `pulumi:"pmaxRatioThreshold"`
	// Kubernetes scheduler plugins to activate.
	SchedulerPlugins pulumi.StringArrayOutput `pulumi:"schedulerPlugins"`
	// Maximum coefficient of variation for workload to be considered stable.
	StabilityCvMax pulumi.Float64PtrOutput `pulumi:"stabilityCvMax"`
	// Period in seconds to ignore usage data after workload starts.
	StartupPeriodSeconds pulumi.IntPtrOutput `pulumi:"startupPeriodSeconds"`
}

// NewWorkloadPolicy registers a new resource with the given unique name, arguments, and options.
func NewWorkloadPolicy(ctx *pulumi.Context,
	name string, args *WorkloadPolicyArgs, opts ...pulumi.ResourceOption) (*WorkloadPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.CooldownMinutes == nil {
		args.CooldownMinutes = pulumi.IntPtr(300)
	}
	if args.CpuVerticalScaling != nil {
		args.CpuVerticalScaling = args.CpuVerticalScaling.ToVerticalScalingArgsPtrOutput().ApplyT(func(v *VerticalScalingArgs) *VerticalScalingArgs { return v.Defaults() }).(VerticalScalingArgsPtrOutput)
	}
	if args.GpuVerticalScaling != nil {
		args.GpuVerticalScaling = args.GpuVerticalScaling.ToVerticalScalingArgsPtrOutput().ApplyT(func(v *VerticalScalingArgs) *VerticalScalingArgs { return v.Defaults() }).(VerticalScalingArgsPtrOutput)
	}
	if args.GpuVramVerticalScaling != nil {
		args.GpuVramVerticalScaling = args.GpuVramVerticalScaling.ToVerticalScalingArgsPtrOutput().ApplyT(func(v *VerticalScalingArgs) *VerticalScalingArgs { return v.Defaults() }).(VerticalScalingArgsPtrOutput)
	}
	if args.LoopbackPeriodSeconds == nil {
		args.LoopbackPeriodSeconds = pulumi.IntPtr(86400)
	}
	if args.MemoryVerticalScaling != nil {
		args.MemoryVerticalScaling = args.MemoryVerticalScaling.ToVerticalScalingArgsPtrOutput().ApplyT(func(v *VerticalScalingArgs) *VerticalScalingArgs { return v.Defaults() }).(VerticalScalingArgsPtrOutput)
	}
	if args.MinChangePercent == nil {
		args.MinChangePercent = pulumi.Float64Ptr(0.2)
	}
	if args.MinDataPoints == nil {
		args.MinDataPoints = pulumi.IntPtr(15)
	}
	if args.MinVpaWindowDataPoints == nil {
		args.MinVpaWindowDataPoints = pulumi.IntPtr(30)
	}
	if args.PmaxRatioThreshold == nil {
		args.PmaxRatioThreshold = pulumi.Float64Ptr(3.0)
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkloadPolicy
	err := ctx.RegisterResource("devzero:resources:WorkloadPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkloadPolicy gets an existing WorkloadPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkloadPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkloadPolicyState, opts ...pulumi.ResourceOption) (*WorkloadPolicy, error) {
	var resource WorkloadPolicy
	err := ctx.ReadResource("devzero:resources:WorkloadPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkloadPolicy resources.
type workloadPolicyState struct {
}

type WorkloadPolicyState struct {
}

func (WorkloadPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadPolicyState)(nil)).Elem()
}

type workloadPolicyArgs struct {
	// Action triggers: 'on_detection' or 'on_schedule'.
	ActionTriggers []string `pulumi:"actionTriggers"`
	// Minutes to wait between applying recommendations. Default: 300 (5 h).
	CooldownMinutes    *int                 `pulumi:"cooldownMinutes"`
	CpuVerticalScaling *VerticalScalingArgs `pulumi:"cpuVerticalScaling"`
	// Cron expression for scheduled application (5-field format).
	CronSchedule *string `pulumi:"cronSchedule"`
	// Cron expression for background defragmentation.
	DefragmentationSchedule *string `pulumi:"defragmentationSchedule"`
	// Free-form description of the policy.
	Description *string `pulumi:"description"`
	// Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
	DetectionTriggers []string `pulumi:"detectionTriggers"`
	// Percentage drift from baseline that triggers VPA refresh.
	DriftDeltaPercent *float64 `pulumi:"driftDeltaPercent"`
	// Raise requests to cover peak usage when max/recommendation ratio exceeds pmaxRatioThreshold. Server/web default: true.
	EnablePmaxProtection   *bool                  `pulumi:"enablePmaxProtection"`
	GpuVerticalScaling     *VerticalScalingArgs   `pulumi:"gpuVerticalScaling"`
	GpuVramVerticalScaling *VerticalScalingArgs   `pulumi:"gpuVramVerticalScaling"`
	HorizontalScaling      *HorizontalScalingArgs `pulumi:"horizontalScaling"`
	// Hysteresis threshold vs target for HPA coordination.
	HysteresisVsTarget *float64 `pulumi:"hysteresisVsTarget"`
	// Allow live migration when applying recommendations.
	LiveMigrationEnabled *bool `pulumi:"liveMigrationEnabled"`
	// Period in seconds to look back for resource usage data. Default: 86400 (24 h).
	LoopbackPeriodSeconds *int                 `pulumi:"loopbackPeriodSeconds"`
	MemoryVerticalScaling *VerticalScalingArgs `pulumi:"memoryVerticalScaling"`
	// Global minimum change threshold for applying recommendations. Default: 0.2 (20%).
	MinChangePercent *float64 `pulumi:"minChangePercent"`
	// Global minimum data points required for recommendations. Default: 15.
	MinDataPoints *int `pulumi:"minDataPoints"`
	// Minimum data points in VPA analysis window. Default: 30.
	MinVpaWindowDataPoints *int `pulumi:"minVpaWindowDataPoints"`
	// Human-friendly name for the policy.
	Name string `pulumi:"name"`
	// Max-to-recommendation ratio that triggers pmax protection. Default: 3.0.
	PmaxRatioThreshold *float64 `pulumi:"pmaxRatioThreshold"`
	// Kubernetes scheduler plugins to activate.
	SchedulerPlugins []string `pulumi:"schedulerPlugins"`
	// Maximum coefficient of variation for workload to be considered stable.
	StabilityCvMax *float64 `pulumi:"stabilityCvMax"`
	// Period in seconds to ignore usage data after workload starts.
	StartupPeriodSeconds *int `pulumi:"startupPeriodSeconds"`
}

// The set of arguments for constructing a WorkloadPolicy resource.
type WorkloadPolicyArgs struct {
	// Action triggers: 'on_detection' or 'on_schedule'.
	ActionTriggers pulumi.StringArrayInput
	// Minutes to wait between applying recommendations. Default: 300 (5 h).
	CooldownMinutes    pulumi.IntPtrInput
	CpuVerticalScaling VerticalScalingArgsPtrInput
	// Cron expression for scheduled application (5-field format).
	CronSchedule pulumi.StringPtrInput
	// Cron expression for background defragmentation.
	DefragmentationSchedule pulumi.StringPtrInput
	// Free-form description of the policy.
	Description pulumi.StringPtrInput
	// Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
	DetectionTriggers pulumi.StringArrayInput
	// Percentage drift from baseline that triggers VPA refresh.
	DriftDeltaPercent pulumi.Float64PtrInput
	// Raise requests to cover peak usage when max/recommendation ratio exceeds pmaxRatioThreshold. Server/web default: true.
	EnablePmaxProtection   pulumi.BoolPtrInput
	GpuVerticalScaling     VerticalScalingArgsPtrInput
	GpuVramVerticalScaling VerticalScalingArgsPtrInput
	HorizontalScaling      HorizontalScalingArgsPtrInput
	// Hysteresis threshold vs target for HPA coordination.
	HysteresisVsTarget pulumi.Float64PtrInput
	// Allow live migration when applying recommendations.
	LiveMigrationEnabled pulumi.BoolPtrInput
	// Period in seconds to look back for resource usage data. Default: 86400 (24 h).
	LoopbackPeriodSeconds pulumi.IntPtrInput
	MemoryVerticalScaling VerticalScalingArgsPtrInput
	// Global minimum change threshold for applying recommendations. Default: 0.2 (20%).
	MinChangePercent pulumi.Float64PtrInput
	// Global minimum data points required for recommendations. Default: 15.
	MinDataPoints pulumi.IntPtrInput
	// Minimum data points in VPA analysis window. Default: 30.
	MinVpaWindowDataPoints pulumi.IntPtrInput
	// Human-friendly name for the policy.
	Name pulumi.StringInput
	// Max-to-recommendation ratio that triggers pmax protection. Default: 3.0.
	PmaxRatioThreshold pulumi.Float64PtrInput
	// Kubernetes scheduler plugins to activate.
	SchedulerPlugins pulumi.StringArrayInput
	// Maximum coefficient of variation for workload to be considered stable.
	StabilityCvMax pulumi.Float64PtrInput
	// Period in seconds to ignore usage data after workload starts.
	StartupPeriodSeconds pulumi.IntPtrInput
}

func (WorkloadPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workloadPolicyArgs)(nil)).Elem()
}

type WorkloadPolicyInput interface {
	pulumi.Input

	ToWorkloadPolicyOutput() WorkloadPolicyOutput
	ToWorkloadPolicyOutputWithContext(ctx context.Context) WorkloadPolicyOutput
}

func (*WorkloadPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadPolicy)(nil)).Elem()
}

func (i *WorkloadPolicy) ToWorkloadPolicyOutput() WorkloadPolicyOutput {
	return i.ToWorkloadPolicyOutputWithContext(context.Background())
}

func (i *WorkloadPolicy) ToWorkloadPolicyOutputWithContext(ctx context.Context) WorkloadPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyOutput)
}

// WorkloadPolicyArrayInput is an input type that accepts WorkloadPolicyArray and WorkloadPolicyArrayOutput values.
// You can construct a concrete instance of `WorkloadPolicyArrayInput` via:
//
//	WorkloadPolicyArray{ WorkloadPolicyArgs{...} }
type WorkloadPolicyArrayInput interface {
	pulumi.Input

	ToWorkloadPolicyArrayOutput() WorkloadPolicyArrayOutput
	ToWorkloadPolicyArrayOutputWithContext(context.Context) WorkloadPolicyArrayOutput
}

type WorkloadPolicyArray []WorkloadPolicyInput

func (WorkloadPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadPolicy)(nil)).Elem()
}

func (i WorkloadPolicyArray) ToWorkloadPolicyArrayOutput() WorkloadPolicyArrayOutput {
	return i.ToWorkloadPolicyArrayOutputWithContext(context.Background())
}

func (i WorkloadPolicyArray) ToWorkloadPolicyArrayOutputWithContext(ctx context.Context) WorkloadPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyArrayOutput)
}

// WorkloadPolicyMapInput is an input type that accepts WorkloadPolicyMap and WorkloadPolicyMapOutput values.
// You can construct a concrete instance of `WorkloadPolicyMapInput` via:
//
//	WorkloadPolicyMap{ "key": WorkloadPolicyArgs{...} }
type WorkloadPolicyMapInput interface {
	pulumi.Input

	ToWorkloadPolicyMapOutput() WorkloadPolicyMapOutput
	ToWorkloadPolicyMapOutputWithContext(context.Context) WorkloadPolicyMapOutput
}

type WorkloadPolicyMap map[string]WorkloadPolicyInput

func (WorkloadPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadPolicy)(nil)).Elem()
}

func (i WorkloadPolicyMap) ToWorkloadPolicyMapOutput() WorkloadPolicyMapOutput {
	return i.ToWorkloadPolicyMapOutputWithContext(context.Background())
}

func (i WorkloadPolicyMap) ToWorkloadPolicyMapOutputWithContext(ctx context.Context) WorkloadPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkloadPolicyMapOutput)
}

type WorkloadPolicyOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkloadPolicy)(nil)).Elem()
}

func (o WorkloadPolicyOutput) ToWorkloadPolicyOutput() WorkloadPolicyOutput {
	return o
}

func (o WorkloadPolicyOutput) ToWorkloadPolicyOutputWithContext(ctx context.Context) WorkloadPolicyOutput {
	return o
}

// Action triggers: 'on_detection' or 'on_schedule'.
func (o WorkloadPolicyOutput) ActionTriggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringArrayOutput { return v.ActionTriggers }).(pulumi.StringArrayOutput)
}

// Minutes to wait between applying recommendations. Default: 300 (5 h).
func (o WorkloadPolicyOutput) CooldownMinutes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.CooldownMinutes }).(pulumi.IntPtrOutput)
}

func (o WorkloadPolicyOutput) CpuVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.CpuVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

// Cron expression for scheduled application (5-field format).
func (o WorkloadPolicyOutput) CronSchedule() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringPtrOutput { return v.CronSchedule }).(pulumi.StringPtrOutput)
}

// Cron expression for background defragmentation.
func (o WorkloadPolicyOutput) DefragmentationSchedule() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringPtrOutput { return v.DefragmentationSchedule }).(pulumi.StringPtrOutput)
}

// Free-form description of the policy.
func (o WorkloadPolicyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
func (o WorkloadPolicyOutput) DetectionTriggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringArrayOutput { return v.DetectionTriggers }).(pulumi.StringArrayOutput)
}

// Percentage drift from baseline that triggers VPA refresh.
func (o WorkloadPolicyOutput) DriftDeltaPercent() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.DriftDeltaPercent }).(pulumi.Float64PtrOutput)
}

// Raise requests to cover peak usage when max/recommendation ratio exceeds pmaxRatioThreshold. Server/web default: true.
func (o WorkloadPolicyOutput) EnablePmaxProtection() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.BoolPtrOutput { return v.EnablePmaxProtection }).(pulumi.BoolPtrOutput)
}

func (o WorkloadPolicyOutput) GpuVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.GpuVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

func (o WorkloadPolicyOutput) GpuVramVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.GpuVramVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

func (o WorkloadPolicyOutput) HorizontalScaling() HorizontalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) HorizontalScalingArgsPtrOutput { return v.HorizontalScaling }).(HorizontalScalingArgsPtrOutput)
}

// Hysteresis threshold vs target for HPA coordination.
func (o WorkloadPolicyOutput) HysteresisVsTarget() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.HysteresisVsTarget }).(pulumi.Float64PtrOutput)
}

// Allow live migration when applying recommendations.
func (o WorkloadPolicyOutput) LiveMigrationEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.BoolPtrOutput { return v.LiveMigrationEnabled }).(pulumi.BoolPtrOutput)
}

// Period in seconds to look back for resource usage data. Default: 86400 (24 h).
func (o WorkloadPolicyOutput) LoopbackPeriodSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.LoopbackPeriodSeconds }).(pulumi.IntPtrOutput)
}

func (o WorkloadPolicyOutput) MemoryVerticalScaling() VerticalScalingArgsPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) VerticalScalingArgsPtrOutput { return v.MemoryVerticalScaling }).(VerticalScalingArgsPtrOutput)
}

// Global minimum change threshold for applying recommendations. Default: 0.2 (20%).
func (o WorkloadPolicyOutput) MinChangePercent() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.MinChangePercent }).(pulumi.Float64PtrOutput)
}

// Global minimum data points required for recommendations. Default: 15.
func (o WorkloadPolicyOutput) MinDataPoints() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.MinDataPoints }).(pulumi.IntPtrOutput)
}

// Minimum data points in VPA analysis window. Default: 30.
func (o WorkloadPolicyOutput) MinVpaWindowDataPoints() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.MinVpaWindowDataPoints }).(pulumi.IntPtrOutput)
}

// Human-friendly name for the policy.
func (o WorkloadPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Max-to-recommendation ratio that triggers pmax protection. Default: 3.0.
func (o WorkloadPolicyOutput) PmaxRatioThreshold() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.PmaxRatioThreshold }).(pulumi.Float64PtrOutput)
}

// Kubernetes scheduler plugins to activate.
func (o WorkloadPolicyOutput) SchedulerPlugins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.StringArrayOutput { return v.SchedulerPlugins }).(pulumi.StringArrayOutput)
}

// Maximum coefficient of variation for workload to be considered stable.
func (o WorkloadPolicyOutput) StabilityCvMax() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.Float64PtrOutput { return v.StabilityCvMax }).(pulumi.Float64PtrOutput)
}

// Period in seconds to ignore usage data after workload starts.
func (o WorkloadPolicyOutput) StartupPeriodSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WorkloadPolicy) pulumi.IntPtrOutput { return v.StartupPeriodSeconds }).(pulumi.IntPtrOutput)
}

type WorkloadPolicyArrayOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkloadPolicy)(nil)).Elem()
}

func (o WorkloadPolicyArrayOutput) ToWorkloadPolicyArrayOutput() WorkloadPolicyArrayOutput {
	return o
}

func (o WorkloadPolicyArrayOutput) ToWorkloadPolicyArrayOutputWithContext(ctx context.Context) WorkloadPolicyArrayOutput {
	return o
}

func (o WorkloadPolicyArrayOutput) Index(i pulumi.IntInput) WorkloadPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkloadPolicy {
		return vs[0].([]*WorkloadPolicy)[vs[1].(int)]
	}).(WorkloadPolicyOutput)
}

type WorkloadPolicyMapOutput struct{ *pulumi.OutputState }

func (WorkloadPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkloadPolicy)(nil)).Elem()
}

func (o WorkloadPolicyMapOutput) ToWorkloadPolicyMapOutput() WorkloadPolicyMapOutput {
	return o
}

func (o WorkloadPolicyMapOutput) ToWorkloadPolicyMapOutputWithContext(ctx context.Context) WorkloadPolicyMapOutput {
	return o
}

func (o WorkloadPolicyMapOutput) MapIndex(k pulumi.StringInput) WorkloadPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkloadPolicy {
		return vs[0].(map[string]*WorkloadPolicy)[vs[1].(string)]
	}).(WorkloadPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyInput)(nil)).Elem(), &WorkloadPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyArrayInput)(nil)).Elem(), WorkloadPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkloadPolicyMapInput)(nil)).Elem(), WorkloadPolicyMap{})
	pulumi.RegisterOutputType(WorkloadPolicyOutput{})
	pulumi.RegisterOutputType(WorkloadPolicyArrayOutput{})
	pulumi.RegisterOutputType(WorkloadPolicyMapOutput{})
}
