# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_devzero.config as __config
    config = __config
    import pulumi_devzero.resources as __resources
    resources = __resources
else:
    config = _utilities.lazy_import('pulumi_devzero.config')
    resources = _utilities.lazy_import('pulumi_devzero.resources')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "devzero",
  "mod": "resources",
  "fqn": "pulumi_devzero.resources",
  "classes": {
   "devzero:resources:Cluster": "Cluster",
   "devzero:resources:NodePolicy": "NodePolicy",
   "devzero:resources:NodePolicyTarget": "NodePolicyTarget",
   "devzero:resources:WorkloadPolicy": "WorkloadPolicy",
   "devzero:resources:WorkloadPolicyTarget": "WorkloadPolicyTarget"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "devzero",
  "token": "pulumi:providers:devzero",
  "fqn": "pulumi_devzero",
  "class": "Provider"
 }
]
"""
)
