// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("devzero");

/**
 * The DevZero team ID.
 */
export declare const teamId: string | undefined;
Object.defineProperty(exports, "teamId", {
    get() {
        return __config.get("teamId");
    },
    enumerable: true,
});

/**
 * The DevZero API token for authentication.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

/**
 * The DevZero API base URL. Defaults to https://dakr.devzero.io
 */
export declare const url: string;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url") ?? "https://dakr.devzero.io";
    },
    enumerable: true,
});

