// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getClusterIdByName(args: GetClusterIdByNameArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterIdByNameResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("devzero:resources:getClusterIdByName", {
        "name": args.name,
        "teamId": args.teamId,
    }, opts);
}

export interface GetClusterIdByNameArgs {
    /**
     * The cluster name to look up.
     */
    name: string;
    /**
     * The team ID to search within.
     */
    teamId: string;
}

export interface GetClusterIdByNameResult {
    /**
     * The ID of the cluster matching the given team and name.
     */
    readonly clusterId: string;
}
export function getClusterIdByNameOutput(args: GetClusterIdByNameOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClusterIdByNameResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("devzero:resources:getClusterIdByName", {
        "name": args.name,
        "teamId": args.teamId,
    }, opts);
}

export interface GetClusterIdByNameOutputArgs {
    /**
     * The cluster name to look up.
     */
    name: pulumi.Input<string>;
    /**
     * The team ID to search within.
     */
    teamId: pulumi.Input<string>;
}
