// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ClusterArgs } from "./cluster";
export type Cluster = import("./cluster").Cluster;
export const Cluster: typeof import("./cluster").Cluster = null as any;
utilities.lazyLoad(exports, ["Cluster"], () => require("./cluster"));

export { GetClusterIdByNameArgs, GetClusterIdByNameResult, GetClusterIdByNameOutputArgs } from "./getClusterIdByName";
export const getClusterIdByName: typeof import("./getClusterIdByName").getClusterIdByName = null as any;
export const getClusterIdByNameOutput: typeof import("./getClusterIdByName").getClusterIdByNameOutput = null as any;
utilities.lazyLoad(exports, ["getClusterIdByName","getClusterIdByNameOutput"], () => require("./getClusterIdByName"));

export { NodePolicyArgs } from "./nodePolicy";
export type NodePolicy = import("./nodePolicy").NodePolicy;
export const NodePolicy: typeof import("./nodePolicy").NodePolicy = null as any;
utilities.lazyLoad(exports, ["NodePolicy"], () => require("./nodePolicy"));

export { NodePolicyTargetArgs } from "./nodePolicyTarget";
export type NodePolicyTarget = import("./nodePolicyTarget").NodePolicyTarget;
export const NodePolicyTarget: typeof import("./nodePolicyTarget").NodePolicyTarget = null as any;
utilities.lazyLoad(exports, ["NodePolicyTarget"], () => require("./nodePolicyTarget"));

export { WorkloadPolicyArgs } from "./workloadPolicy";
export type WorkloadPolicy = import("./workloadPolicy").WorkloadPolicy;
export const WorkloadPolicy: typeof import("./workloadPolicy").WorkloadPolicy = null as any;
utilities.lazyLoad(exports, ["WorkloadPolicy"], () => require("./workloadPolicy"));

export { WorkloadPolicyTargetArgs } from "./workloadPolicyTarget";
export type WorkloadPolicyTarget = import("./workloadPolicyTarget").WorkloadPolicyTarget;
export const WorkloadPolicyTarget: typeof import("./workloadPolicyTarget").WorkloadPolicyTarget = null as any;
utilities.lazyLoad(exports, ["WorkloadPolicyTarget"], () => require("./workloadPolicyTarget"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "devzero:resources:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "devzero:resources:NodePolicy":
                return new NodePolicy(name, <any>undefined, { urn })
            case "devzero:resources:NodePolicyTarget":
                return new NodePolicyTarget(name, <any>undefined, { urn })
            case "devzero:resources:WorkloadPolicy":
                return new WorkloadPolicy(name, <any>undefined, { urn })
            case "devzero:resources:WorkloadPolicyTarget":
                return new WorkloadPolicyTarget(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("devzero", "resources", _module)
