// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class NodePolicyTarget extends pulumi.CustomResource {
    /**
     * Get an existing NodePolicyTarget resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NodePolicyTarget {
        return new NodePolicyTarget(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'devzero:resources:NodePolicyTarget';

    /**
     * Returns true if the given object is an instance of NodePolicyTarget.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NodePolicyTarget {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NodePolicyTarget.__pulumiType;
    }

    /**
     * Cluster IDs where this node policy applies.
     */
    declare public readonly clusterIds: pulumi.Output<string[]>;
    /**
     * Free-form description of the target.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Whether this target is active. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Human-friendly name for the target.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Node policy ID this target is attached to.
     */
    declare public readonly policyId: pulumi.Output<string>;

    /**
     * Create a NodePolicyTarget resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NodePolicyTargetArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clusterIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterIds'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.policyId === undefined && !opts.urn) {
                throw new Error("Missing required property 'policyId'");
            }
            resourceInputs["clusterIds"] = args?.clusterIds;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["policyId"] = args?.policyId;
        } else {
            resourceInputs["clusterIds"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["policyId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NodePolicyTarget.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NodePolicyTarget resource.
 */
export interface NodePolicyTargetArgs {
    clusterIds: pulumi.Input<pulumi.Input<string>[]>;
    description?: pulumi.Input<string>;
    enabled?: pulumi.Input<boolean>;
    name: pulumi.Input<string>;
    policyId: pulumi.Input<string>;
}
