// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class NodePolicy extends pulumi.CustomResource {
    /**
     * Get an existing NodePolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NodePolicy {
        return new NodePolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'devzero:resources:NodePolicy';

    /**
     * Returns true if the given object is an instance of NodePolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NodePolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NodePolicy.__pulumiType;
    }

    /**
     * CPU architectures (e.g. amd64, arm64).
     */
    declare public readonly architectures: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * AWS-specific node class configuration.
     */
    declare public readonly aws: pulumi.Output<outputs.resources.AWSNodeClassSpecArgs | undefined>;
    /**
     * Azure-specific node class configuration.
     */
    declare public readonly azure: pulumi.Output<outputs.resources.AzureNodeClassSpecArgs | undefined>;
    /**
     * Capacity types (e.g. on-demand, spot).
     */
    declare public readonly capacityTypes: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Free-form description of the node policy.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Karpenter disruption policy for consolidation and expiry.
     */
    declare public readonly disruption: pulumi.Output<outputs.resources.DisruptionPolicyArgs | undefined>;
    /**
     * Filter instances by category (e.g. general-purpose, compute-optimized).
     */
    declare public readonly instanceCategories: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Filter instances by CPU count.
     */
    declare public readonly instanceCpus: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Filter instances by family (e.g. m5, c6i).
     */
    declare public readonly instanceFamilies: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Filter instances by generation.
     */
    declare public readonly instanceGenerations: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Filter instances by hypervisor type.
     */
    declare public readonly instanceHypervisors: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Filter instances by size (e.g. large, xlarge).
     */
    declare public readonly instanceSizes: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Explicitly select specific instance types.
     */
    declare public readonly instanceTypes: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Labels applied to provisioned nodes.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Resource limits on the total capacity managed by this policy.
     */
    declare public readonly limits: pulumi.Output<outputs.resources.ResourceLimitsArgs | undefined>;
    /**
     * Human-friendly name for the node policy.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Override name for the generated Karpenter NodeClass.
     */
    declare public readonly nodeClassName: pulumi.Output<string | undefined>;
    /**
     * Override name for the generated Karpenter NodePool.
     */
    declare public readonly nodePoolName: pulumi.Output<string | undefined>;
    /**
     * Operating systems for nodes (e.g. linux, windows).
     */
    declare public readonly operatingSystems: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Raw Karpenter YAML for full NodePool/NodeClass customization.
     */
    declare public readonly raw: pulumi.Output<outputs.resources.RawKarpenterSpecArgs[] | undefined>;
    /**
     * Taints applied to provisioned nodes.
     */
    declare public readonly taints: pulumi.Output<outputs.resources.TaintArgs[] | undefined>;
    /**
     * Priority weight for this policy; higher values take precedence.
     */
    declare public readonly weight: pulumi.Output<number | undefined>;
    /**
     * Availability zones where nodes may be provisioned.
     */
    declare public readonly zones: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;

    /**
     * Create a NodePolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NodePolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["architectures"] = args?.architectures;
            resourceInputs["aws"] = args?.aws;
            resourceInputs["azure"] = args?.azure;
            resourceInputs["capacityTypes"] = args?.capacityTypes;
            resourceInputs["description"] = args?.description;
            resourceInputs["disruption"] = args?.disruption;
            resourceInputs["instanceCategories"] = args?.instanceCategories;
            resourceInputs["instanceCpus"] = args?.instanceCpus;
            resourceInputs["instanceFamilies"] = args?.instanceFamilies;
            resourceInputs["instanceGenerations"] = args?.instanceGenerations;
            resourceInputs["instanceHypervisors"] = args?.instanceHypervisors;
            resourceInputs["instanceSizes"] = args?.instanceSizes;
            resourceInputs["instanceTypes"] = args?.instanceTypes;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["limits"] = args?.limits;
            resourceInputs["name"] = args?.name;
            resourceInputs["nodeClassName"] = args?.nodeClassName;
            resourceInputs["nodePoolName"] = args?.nodePoolName;
            resourceInputs["operatingSystems"] = args?.operatingSystems;
            resourceInputs["raw"] = args?.raw;
            resourceInputs["taints"] = args?.taints;
            resourceInputs["weight"] = args?.weight;
            resourceInputs["zones"] = args?.zones;
        } else {
            resourceInputs["architectures"] = undefined /*out*/;
            resourceInputs["aws"] = undefined /*out*/;
            resourceInputs["azure"] = undefined /*out*/;
            resourceInputs["capacityTypes"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["disruption"] = undefined /*out*/;
            resourceInputs["instanceCategories"] = undefined /*out*/;
            resourceInputs["instanceCpus"] = undefined /*out*/;
            resourceInputs["instanceFamilies"] = undefined /*out*/;
            resourceInputs["instanceGenerations"] = undefined /*out*/;
            resourceInputs["instanceHypervisors"] = undefined /*out*/;
            resourceInputs["instanceSizes"] = undefined /*out*/;
            resourceInputs["instanceTypes"] = undefined /*out*/;
            resourceInputs["labels"] = undefined /*out*/;
            resourceInputs["limits"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["nodeClassName"] = undefined /*out*/;
            resourceInputs["nodePoolName"] = undefined /*out*/;
            resourceInputs["operatingSystems"] = undefined /*out*/;
            resourceInputs["raw"] = undefined /*out*/;
            resourceInputs["taints"] = undefined /*out*/;
            resourceInputs["weight"] = undefined /*out*/;
            resourceInputs["zones"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NodePolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NodePolicy resource.
 */
export interface NodePolicyArgs {
    architectures?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    aws?: pulumi.Input<inputs.resources.AWSNodeClassSpecArgsArgs>;
    azure?: pulumi.Input<inputs.resources.AzureNodeClassSpecArgsArgs>;
    capacityTypes?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    description?: pulumi.Input<string>;
    disruption?: pulumi.Input<inputs.resources.DisruptionPolicyArgsArgs>;
    instanceCategories?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    instanceCpus?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    instanceFamilies?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    instanceGenerations?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    instanceHypervisors?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    instanceSizes?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    instanceTypes?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    limits?: pulumi.Input<inputs.resources.ResourceLimitsArgsArgs>;
    name: pulumi.Input<string>;
    nodeClassName?: pulumi.Input<string>;
    nodePoolName?: pulumi.Input<string>;
    operatingSystems?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    raw?: pulumi.Input<pulumi.Input<inputs.resources.RawKarpenterSpecArgsArgs>[]>;
    taints?: pulumi.Input<pulumi.Input<inputs.resources.TaintArgsArgs>[]>;
    weight?: pulumi.Input<number>;
    zones?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
}
