// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class WorkloadPolicyTarget extends pulumi.CustomResource {
    /**
     * Get an existing WorkloadPolicyTarget resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WorkloadPolicyTarget {
        return new WorkloadPolicyTarget(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'devzero:resources:WorkloadPolicyTarget';

    /**
     * Returns true if the given object is an instance of WorkloadPolicyTarget.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkloadPolicyTarget {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkloadPolicyTarget.__pulumiType;
    }

    /**
     * Cluster IDs where this target applies.
     */
    declare public readonly clusterIds: pulumi.Output<string[]>;
    /**
     * Free-form description of the target.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Enable or disable this target.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Restrict matching to specific Kubernetes kinds (e.g. Deployment, Pod).
     */
    declare public readonly kindFilter: pulumi.Output<string[] | undefined>;
    /**
     * Human-friendly name for this target.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Regex to match workload names.
     */
    declare public readonly namePattern: pulumi.Output<outputs.resources.NamePatternArgs | undefined>;
    /**
     * Select namespaces by labels.
     */
    declare public readonly namespaceSelector: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;
    /**
     * Restrict matching to specific node groups by name.
     */
    declare public readonly nodeGroupNames: pulumi.Output<string[] | undefined>;
    /**
     * Workload policy ID this target is attached to.
     */
    declare public readonly policyId: pulumi.Output<string>;
    /**
     * Evaluation priority; higher values take precedence when targets overlap.
     */
    declare public readonly priority: pulumi.Output<number | undefined>;
    /**
     * Explicit list of workload names to include.
     */
    declare public readonly workloadNames: pulumi.Output<string[] | undefined>;
    /**
     * Select workloads by labels.
     */
    declare public readonly workloadSelector: pulumi.Output<outputs.resources.LabelSelectorArgs | undefined>;

    /**
     * Create a WorkloadPolicyTarget resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkloadPolicyTargetArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.clusterIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterIds'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.policyId === undefined && !opts.urn) {
                throw new Error("Missing required property 'policyId'");
            }
            resourceInputs["clusterIds"] = args?.clusterIds;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["kindFilter"] = args?.kindFilter;
            resourceInputs["name"] = args?.name;
            resourceInputs["namePattern"] = args?.namePattern;
            resourceInputs["namespaceSelector"] = args?.namespaceSelector;
            resourceInputs["nodeGroupNames"] = args?.nodeGroupNames;
            resourceInputs["policyId"] = args?.policyId;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["workloadNames"] = args?.workloadNames;
            resourceInputs["workloadSelector"] = args?.workloadSelector;
        } else {
            resourceInputs["clusterIds"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["kindFilter"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["namePattern"] = undefined /*out*/;
            resourceInputs["namespaceSelector"] = undefined /*out*/;
            resourceInputs["nodeGroupNames"] = undefined /*out*/;
            resourceInputs["policyId"] = undefined /*out*/;
            resourceInputs["priority"] = undefined /*out*/;
            resourceInputs["workloadNames"] = undefined /*out*/;
            resourceInputs["workloadSelector"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkloadPolicyTarget.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WorkloadPolicyTarget resource.
 */
export interface WorkloadPolicyTargetArgs {
    clusterIds: pulumi.Input<pulumi.Input<string>[]>;
    description?: pulumi.Input<string>;
    enabled?: pulumi.Input<boolean>;
    kindFilter?: pulumi.Input<pulumi.Input<string>[]>;
    name: pulumi.Input<string>;
    namePattern?: pulumi.Input<inputs.resources.NamePatternArgsArgs>;
    namespaceSelector?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
    nodeGroupNames?: pulumi.Input<pulumi.Input<string>[]>;
    policyId: pulumi.Input<string>;
    priority?: pulumi.Input<number>;
    workloadNames?: pulumi.Input<pulumi.Input<string>[]>;
    workloadSelector?: pulumi.Input<inputs.resources.LabelSelectorArgsArgs>;
}
