// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class WorkloadPolicy extends pulumi.CustomResource {
    /**
     * Get an existing WorkloadPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WorkloadPolicy {
        return new WorkloadPolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'devzero:resources:WorkloadPolicy';

    /**
     * Returns true if the given object is an instance of WorkloadPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkloadPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkloadPolicy.__pulumiType;
    }

    /**
     * Action triggers: 'on_detection' or 'on_schedule'.
     */
    declare public readonly actionTriggers: pulumi.Output<string[] | undefined>;
    /**
     * Minutes to wait between applying recommendations. Default: 300 (5 h).
     */
    declare public readonly cooldownMinutes: pulumi.Output<number | undefined>;
    declare public readonly cpuVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    /**
     * Cron expression for scheduled application (5-field format).
     */
    declare public readonly cronSchedule: pulumi.Output<string | undefined>;
    /**
     * Cron expression for background defragmentation.
     */
    declare public readonly defragmentationSchedule: pulumi.Output<string | undefined>;
    /**
     * Free-form description of the policy.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
     */
    declare public readonly detectionTriggers: pulumi.Output<string[] | undefined>;
    /**
     * Percentage drift from baseline that triggers VPA refresh.
     */
    declare public readonly driftDeltaPercent: pulumi.Output<number | undefined>;
    /**
     * Raise requests to cover peak usage when max/recommendation ratio exceeds pmaxRatioThreshold. Server/web default: true.
     */
    declare public readonly enablePmaxProtection: pulumi.Output<boolean | undefined>;
    declare public readonly gpuVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    declare public readonly gpuVramVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    declare public readonly horizontalScaling: pulumi.Output<outputs.resources.HorizontalScalingArgs | undefined>;
    /**
     * Hysteresis threshold vs target for HPA coordination.
     */
    declare public readonly hysteresisVsTarget: pulumi.Output<number | undefined>;
    /**
     * Allow live migration when applying recommendations.
     */
    declare public readonly liveMigrationEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Period in seconds to look back for resource usage data. Default: 86400 (24 h).
     */
    declare public readonly loopbackPeriodSeconds: pulumi.Output<number | undefined>;
    declare public readonly memoryVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    /**
     * Global minimum change threshold for applying recommendations. Default: 0.2 (20%).
     */
    declare public readonly minChangePercent: pulumi.Output<number | undefined>;
    /**
     * Global minimum data points required for recommendations. Default: 15.
     */
    declare public readonly minDataPoints: pulumi.Output<number | undefined>;
    /**
     * Minimum data points in VPA analysis window. Default: 30.
     */
    declare public readonly minVpaWindowDataPoints: pulumi.Output<number | undefined>;
    /**
     * Human-friendly name for the policy.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Max-to-recommendation ratio that triggers pmax protection. Default: 3.0.
     */
    declare public readonly pmaxRatioThreshold: pulumi.Output<number | undefined>;
    /**
     * Kubernetes scheduler plugins to activate.
     */
    declare public readonly schedulerPlugins: pulumi.Output<string[] | undefined>;
    /**
     * Maximum coefficient of variation for workload to be considered stable.
     */
    declare public readonly stabilityCvMax: pulumi.Output<number | undefined>;
    /**
     * Period in seconds to ignore usage data after workload starts.
     */
    declare public readonly startupPeriodSeconds: pulumi.Output<number | undefined>;

    /**
     * Create a WorkloadPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkloadPolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["actionTriggers"] = args?.actionTriggers;
            resourceInputs["cooldownMinutes"] = (args?.cooldownMinutes) ?? 300;
            resourceInputs["cpuVerticalScaling"] = args ? (args.cpuVerticalScaling ? pulumi.output(args.cpuVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["cronSchedule"] = args?.cronSchedule;
            resourceInputs["defragmentationSchedule"] = args?.defragmentationSchedule;
            resourceInputs["description"] = args?.description;
            resourceInputs["detectionTriggers"] = args?.detectionTriggers;
            resourceInputs["driftDeltaPercent"] = args?.driftDeltaPercent;
            resourceInputs["enablePmaxProtection"] = args?.enablePmaxProtection;
            resourceInputs["gpuVerticalScaling"] = args ? (args.gpuVerticalScaling ? pulumi.output(args.gpuVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["gpuVramVerticalScaling"] = args ? (args.gpuVramVerticalScaling ? pulumi.output(args.gpuVramVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["horizontalScaling"] = args?.horizontalScaling;
            resourceInputs["hysteresisVsTarget"] = args?.hysteresisVsTarget;
            resourceInputs["liveMigrationEnabled"] = args?.liveMigrationEnabled;
            resourceInputs["loopbackPeriodSeconds"] = (args?.loopbackPeriodSeconds) ?? 86400;
            resourceInputs["memoryVerticalScaling"] = args ? (args.memoryVerticalScaling ? pulumi.output(args.memoryVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["minChangePercent"] = (args?.minChangePercent) ?? 0.2;
            resourceInputs["minDataPoints"] = (args?.minDataPoints) ?? 15;
            resourceInputs["minVpaWindowDataPoints"] = (args?.minVpaWindowDataPoints) ?? 30;
            resourceInputs["name"] = args?.name;
            resourceInputs["pmaxRatioThreshold"] = (args?.pmaxRatioThreshold) ?? 3;
            resourceInputs["schedulerPlugins"] = args?.schedulerPlugins;
            resourceInputs["stabilityCvMax"] = args?.stabilityCvMax;
            resourceInputs["startupPeriodSeconds"] = args?.startupPeriodSeconds;
        } else {
            resourceInputs["actionTriggers"] = undefined /*out*/;
            resourceInputs["cooldownMinutes"] = undefined /*out*/;
            resourceInputs["cpuVerticalScaling"] = undefined /*out*/;
            resourceInputs["cronSchedule"] = undefined /*out*/;
            resourceInputs["defragmentationSchedule"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["detectionTriggers"] = undefined /*out*/;
            resourceInputs["driftDeltaPercent"] = undefined /*out*/;
            resourceInputs["enablePmaxProtection"] = undefined /*out*/;
            resourceInputs["gpuVerticalScaling"] = undefined /*out*/;
            resourceInputs["gpuVramVerticalScaling"] = undefined /*out*/;
            resourceInputs["horizontalScaling"] = undefined /*out*/;
            resourceInputs["hysteresisVsTarget"] = undefined /*out*/;
            resourceInputs["liveMigrationEnabled"] = undefined /*out*/;
            resourceInputs["loopbackPeriodSeconds"] = undefined /*out*/;
            resourceInputs["memoryVerticalScaling"] = undefined /*out*/;
            resourceInputs["minChangePercent"] = undefined /*out*/;
            resourceInputs["minDataPoints"] = undefined /*out*/;
            resourceInputs["minVpaWindowDataPoints"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["pmaxRatioThreshold"] = undefined /*out*/;
            resourceInputs["schedulerPlugins"] = undefined /*out*/;
            resourceInputs["stabilityCvMax"] = undefined /*out*/;
            resourceInputs["startupPeriodSeconds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkloadPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WorkloadPolicy resource.
 */
export interface WorkloadPolicyArgs {
    /**
     * Action triggers: 'on_detection' or 'on_schedule'.
     */
    actionTriggers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Minutes to wait between applying recommendations. Default: 300 (5 h).
     */
    cooldownMinutes?: pulumi.Input<number>;
    cpuVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    /**
     * Cron expression for scheduled application (5-field format).
     */
    cronSchedule?: pulumi.Input<string>;
    /**
     * Cron expression for background defragmentation.
     */
    defragmentationSchedule?: pulumi.Input<string>;
    /**
     * Free-form description of the policy.
     */
    description?: pulumi.Input<string>;
    /**
     * Detection triggers: 'pod_creation', 'pod_update', or 'pod_reschedule'.
     */
    detectionTriggers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Percentage drift from baseline that triggers VPA refresh.
     */
    driftDeltaPercent?: pulumi.Input<number>;
    /**
     * Raise requests to cover peak usage when max/recommendation ratio exceeds pmaxRatioThreshold. Server/web default: true.
     */
    enablePmaxProtection?: pulumi.Input<boolean>;
    gpuVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    gpuVramVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    horizontalScaling?: pulumi.Input<inputs.resources.HorizontalScalingArgsArgs>;
    /**
     * Hysteresis threshold vs target for HPA coordination.
     */
    hysteresisVsTarget?: pulumi.Input<number>;
    /**
     * Allow live migration when applying recommendations.
     */
    liveMigrationEnabled?: pulumi.Input<boolean>;
    /**
     * Period in seconds to look back for resource usage data. Default: 86400 (24 h).
     */
    loopbackPeriodSeconds?: pulumi.Input<number>;
    memoryVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    /**
     * Global minimum change threshold for applying recommendations. Default: 0.2 (20%).
     */
    minChangePercent?: pulumi.Input<number>;
    /**
     * Global minimum data points required for recommendations. Default: 15.
     */
    minDataPoints?: pulumi.Input<number>;
    /**
     * Minimum data points in VPA analysis window. Default: 30.
     */
    minVpaWindowDataPoints?: pulumi.Input<number>;
    /**
     * Human-friendly name for the policy.
     */
    name: pulumi.Input<string>;
    /**
     * Max-to-recommendation ratio that triggers pmax protection. Default: 3.0.
     */
    pmaxRatioThreshold?: pulumi.Input<number>;
    /**
     * Kubernetes scheduler plugins to activate.
     */
    schedulerPlugins?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Maximum coefficient of variation for workload to be considered stable.
     */
    stabilityCvMax?: pulumi.Input<number>;
    /**
     * Period in seconds to ignore usage data after workload starts.
     */
    startupPeriodSeconds?: pulumi.Input<number>;
}
