// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class WorkloadPolicy extends pulumi.CustomResource {
    /**
     * Get an existing WorkloadPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WorkloadPolicy {
        return new WorkloadPolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'devzero:resources:WorkloadPolicy';

    /**
     * Returns true if the given object is an instance of WorkloadPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkloadPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkloadPolicy.__pulumiType;
    }

    /**
     * When to apply recommendations. Valid values: 'on_detection', 'on_schedule'. Example: ["on_detection"].
     */
    declare public readonly actionTriggers: pulumi.Output<string[] | undefined>;
    /**
     * Minimum minutes to wait between consecutive recommendation applications. Example: 300 (5 h, default).
     */
    declare public readonly cooldownMinutes: pulumi.Output<number | undefined>;
    declare public readonly cpuVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    /**
     * Cron expression for scheduled application (5-field UTC format). Required when actionTriggers includes 'on_schedule'. Example: '0 2 * * *' (daily at 2 am UTC).
     */
    declare public readonly cronSchedule: pulumi.Output<string | undefined>;
    /**
     * Cron expression for background node defragmentation. Example: '0 3 * * 0' (weekly Sunday at 3 am).
     */
    declare public readonly defragmentationSchedule: pulumi.Output<string | undefined>;
    /**
     * Free-form description of the policy. Example: 'VPA policy for production workloads'.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Events that trigger a new recommendation. Valid values: 'pod_creation', 'pod_update', 'pod_reschedule'. Example: ["pod_creation", "pod_reschedule"].
     */
    declare public readonly detectionTriggers: pulumi.Output<string[] | undefined>;
    /**
     * Percentage change from the baseline recommendation that triggers a VPA refresh. Example: 20.0.
     */
    declare public readonly driftDeltaPercent: pulumi.Output<number | undefined>;
    /**
     * Raise requests to cover observed peak usage when the peak/recommendation ratio exceeds pmaxRatioThreshold. Example: true. Server/web default: true.
     */
    declare public readonly enablePmaxProtection: pulumi.Output<boolean | undefined>;
    /**
     * Vertical scaling configuration for GPU cores. Uses the same fields as cpuVerticalScaling; units are GPU cores (millicores).
     */
    declare public readonly gpuVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    /**
     * Vertical scaling configuration for GPU VRAM. Uses the same fields as cpuVerticalScaling; units are bytes.
     */
    declare public readonly gpuVramVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    declare public readonly horizontalScaling: pulumi.Output<outputs.resources.HorizontalScalingArgs | undefined>;
    /**
     * Dead-band ratio around the HPA target to suppress oscillation between VPA and HPA. Example: 0.1 (10% band).
     */
    declare public readonly hysteresisVsTarget: pulumi.Output<number | undefined>;
    /**
     * Allow live pod migration when applying recommendations without restart. Example: false.
     */
    declare public readonly liveMigrationEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Seconds of historical usage data considered per recommendation. Example: 86400 (24 h, default).
     */
    declare public readonly loopbackPeriodSeconds: pulumi.Output<number | undefined>;
    declare public readonly memoryVerticalScaling: pulumi.Output<outputs.resources.VerticalScalingArgs | undefined>;
    /**
     * Minimum relative change (0-1) required before a recommendation is applied globally. Example: 0.2 means 20% change needed (default).
     */
    declare public readonly minChangePercent: pulumi.Output<number | undefined>;
    /**
     * Global minimum number of usage data points needed before any recommendation is emitted. Example: 15 (default).
     */
    declare public readonly minDataPoints: pulumi.Output<number | undefined>;
    /**
     * Minimum data points inside the VPA analysis window before a recommendation is generated. Example: 30 (default).
     */
    declare public readonly minVpaWindowDataPoints: pulumi.Output<number | undefined>;
    /**
     * Human-friendly name for the policy. Example: 'production-vpa-policy'.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Peak-to-recommendation ratio above which pmax protection activates. Example: 3.0 (default) — triggers when peak is 3× the recommendation.
     */
    declare public readonly pmaxRatioThreshold: pulumi.Output<number | undefined>;
    /**
     * Kubernetes scheduler plugins to activate for this policy. Example: ["binpacking"].
     */
    declare public readonly schedulerPlugins: pulumi.Output<string[] | undefined>;
    /**
     * Maximum coefficient of variation (stddev/mean) for a workload to be considered stable enough for VPA. Example: 0.3.
     */
    declare public readonly stabilityCvMax: pulumi.Output<number | undefined>;
    /**
     * Seconds after workload start to exclude from usage data (avoids cold-start spikes). Example: 300 (5 min).
     */
    declare public readonly startupPeriodSeconds: pulumi.Output<number | undefined>;

    /**
     * Create a WorkloadPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkloadPolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["actionTriggers"] = args?.actionTriggers;
            resourceInputs["cooldownMinutes"] = (args?.cooldownMinutes) ?? 300;
            resourceInputs["cpuVerticalScaling"] = args ? (args.cpuVerticalScaling ? pulumi.output(args.cpuVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["cronSchedule"] = args?.cronSchedule;
            resourceInputs["defragmentationSchedule"] = args?.defragmentationSchedule;
            resourceInputs["description"] = args?.description;
            resourceInputs["detectionTriggers"] = args?.detectionTriggers;
            resourceInputs["driftDeltaPercent"] = args?.driftDeltaPercent;
            resourceInputs["enablePmaxProtection"] = args?.enablePmaxProtection;
            resourceInputs["gpuVerticalScaling"] = args ? (args.gpuVerticalScaling ? pulumi.output(args.gpuVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["gpuVramVerticalScaling"] = args ? (args.gpuVramVerticalScaling ? pulumi.output(args.gpuVramVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["horizontalScaling"] = args?.horizontalScaling;
            resourceInputs["hysteresisVsTarget"] = args?.hysteresisVsTarget;
            resourceInputs["liveMigrationEnabled"] = args?.liveMigrationEnabled;
            resourceInputs["loopbackPeriodSeconds"] = (args?.loopbackPeriodSeconds) ?? 86400;
            resourceInputs["memoryVerticalScaling"] = args ? (args.memoryVerticalScaling ? pulumi.output(args.memoryVerticalScaling).apply(inputs.resources.verticalScalingArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["minChangePercent"] = (args?.minChangePercent) ?? 0.2;
            resourceInputs["minDataPoints"] = (args?.minDataPoints) ?? 15;
            resourceInputs["minVpaWindowDataPoints"] = (args?.minVpaWindowDataPoints) ?? 30;
            resourceInputs["name"] = args?.name;
            resourceInputs["pmaxRatioThreshold"] = (args?.pmaxRatioThreshold) ?? 3;
            resourceInputs["schedulerPlugins"] = args?.schedulerPlugins;
            resourceInputs["stabilityCvMax"] = args?.stabilityCvMax;
            resourceInputs["startupPeriodSeconds"] = args?.startupPeriodSeconds;
        } else {
            resourceInputs["actionTriggers"] = undefined /*out*/;
            resourceInputs["cooldownMinutes"] = undefined /*out*/;
            resourceInputs["cpuVerticalScaling"] = undefined /*out*/;
            resourceInputs["cronSchedule"] = undefined /*out*/;
            resourceInputs["defragmentationSchedule"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["detectionTriggers"] = undefined /*out*/;
            resourceInputs["driftDeltaPercent"] = undefined /*out*/;
            resourceInputs["enablePmaxProtection"] = undefined /*out*/;
            resourceInputs["gpuVerticalScaling"] = undefined /*out*/;
            resourceInputs["gpuVramVerticalScaling"] = undefined /*out*/;
            resourceInputs["horizontalScaling"] = undefined /*out*/;
            resourceInputs["hysteresisVsTarget"] = undefined /*out*/;
            resourceInputs["liveMigrationEnabled"] = undefined /*out*/;
            resourceInputs["loopbackPeriodSeconds"] = undefined /*out*/;
            resourceInputs["memoryVerticalScaling"] = undefined /*out*/;
            resourceInputs["minChangePercent"] = undefined /*out*/;
            resourceInputs["minDataPoints"] = undefined /*out*/;
            resourceInputs["minVpaWindowDataPoints"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["pmaxRatioThreshold"] = undefined /*out*/;
            resourceInputs["schedulerPlugins"] = undefined /*out*/;
            resourceInputs["stabilityCvMax"] = undefined /*out*/;
            resourceInputs["startupPeriodSeconds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkloadPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WorkloadPolicy resource.
 */
export interface WorkloadPolicyArgs {
    /**
     * When to apply recommendations. Valid values: 'on_detection', 'on_schedule'. Example: ["on_detection"].
     */
    actionTriggers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Minimum minutes to wait between consecutive recommendation applications. Example: 300 (5 h, default).
     */
    cooldownMinutes?: pulumi.Input<number>;
    cpuVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    /**
     * Cron expression for scheduled application (5-field UTC format). Required when actionTriggers includes 'on_schedule'. Example: '0 2 * * *' (daily at 2 am UTC).
     */
    cronSchedule?: pulumi.Input<string>;
    /**
     * Cron expression for background node defragmentation. Example: '0 3 * * 0' (weekly Sunday at 3 am).
     */
    defragmentationSchedule?: pulumi.Input<string>;
    /**
     * Free-form description of the policy. Example: 'VPA policy for production workloads'.
     */
    description?: pulumi.Input<string>;
    /**
     * Events that trigger a new recommendation. Valid values: 'pod_creation', 'pod_update', 'pod_reschedule'. Example: ["pod_creation", "pod_reschedule"].
     */
    detectionTriggers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Percentage change from the baseline recommendation that triggers a VPA refresh. Example: 20.0.
     */
    driftDeltaPercent?: pulumi.Input<number>;
    /**
     * Raise requests to cover observed peak usage when the peak/recommendation ratio exceeds pmaxRatioThreshold. Example: true. Server/web default: true.
     */
    enablePmaxProtection?: pulumi.Input<boolean>;
    /**
     * Vertical scaling configuration for GPU cores. Uses the same fields as cpuVerticalScaling; units are GPU cores (millicores).
     */
    gpuVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    /**
     * Vertical scaling configuration for GPU VRAM. Uses the same fields as cpuVerticalScaling; units are bytes.
     */
    gpuVramVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    horizontalScaling?: pulumi.Input<inputs.resources.HorizontalScalingArgsArgs>;
    /**
     * Dead-band ratio around the HPA target to suppress oscillation between VPA and HPA. Example: 0.1 (10% band).
     */
    hysteresisVsTarget?: pulumi.Input<number>;
    /**
     * Allow live pod migration when applying recommendations without restart. Example: false.
     */
    liveMigrationEnabled?: pulumi.Input<boolean>;
    /**
     * Seconds of historical usage data considered per recommendation. Example: 86400 (24 h, default).
     */
    loopbackPeriodSeconds?: pulumi.Input<number>;
    memoryVerticalScaling?: pulumi.Input<inputs.resources.VerticalScalingArgsArgs>;
    /**
     * Minimum relative change (0-1) required before a recommendation is applied globally. Example: 0.2 means 20% change needed (default).
     */
    minChangePercent?: pulumi.Input<number>;
    /**
     * Global minimum number of usage data points needed before any recommendation is emitted. Example: 15 (default).
     */
    minDataPoints?: pulumi.Input<number>;
    /**
     * Minimum data points inside the VPA analysis window before a recommendation is generated. Example: 30 (default).
     */
    minVpaWindowDataPoints?: pulumi.Input<number>;
    /**
     * Human-friendly name for the policy. Example: 'production-vpa-policy'.
     */
    name: pulumi.Input<string>;
    /**
     * Peak-to-recommendation ratio above which pmax protection activates. Example: 3.0 (default) — triggers when peak is 3× the recommendation.
     */
    pmaxRatioThreshold?: pulumi.Input<number>;
    /**
     * Kubernetes scheduler plugins to activate for this policy. Example: ["binpacking"].
     */
    schedulerPlugins?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Maximum coefficient of variation (stddev/mean) for a workload to be considered stable enough for VPA. Example: 0.3.
     */
    stabilityCvMax?: pulumi.Input<number>;
    /**
     * Seconds after workload start to exclude from usage data (avoids cold-start spikes). Example: 300 (5 min).
     */
    startupPeriodSeconds?: pulumi.Input<number>;
}
