// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export namespace resources {
    export interface AMISelectorTermArgsArgs {
        /**
         * Well-known alias for the AMI family (e.g. 'al2@latest').
         */
        alias?: pulumi.Input<string>;
        /**
         * Explicit AMI ID.
         */
        id?: pulumi.Input<string>;
        /**
         * AMI name filter (supports wildcards).
         */
        name?: pulumi.Input<string>;
        /**
         * AWS account ID or alias that owns the AMI.
         */
        owner?: pulumi.Input<string>;
        /**
         * SSM parameter path that stores the AMI ID.
         */
        ssmParameter?: pulumi.Input<string>;
        /**
         * Map of AWS tags used to select AMIs.
         */
        tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface AWSNodeClassSpecArgsArgs {
        /**
         * AMI family shorthand (e.g. 'AL2', 'Bottlerocket', 'Windows2022').
         */
        amiFamily?: pulumi.Input<string>;
        /**
         * Selectors for the AMIs used to launch nodes.
         */
        amiSelectorTerms?: pulumi.Input<pulumi.Input<inputs.resources.AMISelectorTermArgsArgs>[]>;
        /**
         * Whether to assign a public IP address to provisioned nodes.
         */
        associatePublicIpAddress?: pulumi.Input<boolean>;
        /**
         * EBS block device mappings for nodes.
         */
        blockDeviceMappings?: pulumi.Input<pulumi.Input<inputs.resources.BlockDeviceMappingArgsArgs>[]>;
        /**
         * Selectors for EC2 capacity reservations to prioritize.
         */
        capacityReservationSelectorTerms?: pulumi.Input<pulumi.Input<inputs.resources.CapacityReservationSelectorTermArgsArgs>[]>;
        /**
         * EC2 launch template context ARN.
         */
        context?: pulumi.Input<string>;
        /**
         * Enable detailed CloudWatch monitoring for instances.
         */
        detailedMonitoring?: pulumi.Input<boolean>;
        /**
         * IAM instance profile name (use instead of Role when profile already exists).
         */
        instanceProfile?: pulumi.Input<string>;
        /**
         * Policy for handling instance store volumes. One of: 'RAID0'.
         */
        instanceStorePolicy?: pulumi.Input<string>;
        /**
         * Kubelet configuration overrides for AWS nodes.
         */
        kubelet?: pulumi.Input<inputs.resources.KubeletConfigurationArgsArgs>;
        /**
         * EC2 instance metadata (IMDS) options.
         */
        metadataOptions?: pulumi.Input<inputs.resources.MetadataOptionsArgsArgs>;
        /**
         * IAM role name assigned to nodes.
         */
        role?: pulumi.Input<string>;
        /**
         * Selectors for security groups attached to nodes.
         */
        securityGroupSelectorTerms?: pulumi.Input<pulumi.Input<inputs.resources.SecurityGroupSelectorTermArgsArgs>[]>;
        /**
         * Selectors for the subnets nodes will be launched into.
         */
        subnetSelectorTerms?: pulumi.Input<pulumi.Input<inputs.resources.SubnetSelectorTermArgsArgs>[]>;
        /**
         * AWS tags applied to all resources created by this node class.
         */
        tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * Custom user data script injected into the node launch template.
         */
        userData?: pulumi.Input<string>;
    }

    export interface AzureKubeletConfigurationArgsArgs {
        /**
         * Unsafe sysctl patterns that are allowed (e.g. 'net.ipv4.*').
         */
        allowedUnsafeSysctls?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * Maximum number of container log files to retain.
         */
        containerLogMaxFiles?: pulumi.Input<number>;
        /**
         * Maximum container log file size before rotation (e.g. '10Mi').
         */
        containerLogMaxSize?: pulumi.Input<string>;
        /**
         * Whether to enforce CPU CFS quota for containers.
         */
        cpuCfsQuota?: pulumi.Input<boolean>;
        /**
         * CPU CFS quota period (e.g. '100ms').
         */
        cpuCfsQuotaPeriod?: pulumi.Input<string>;
        /**
         * CPU manager policy. One of: 'none', 'static'.
         */
        cpuManagerPolicy?: pulumi.Input<string>;
        /**
         * Disk usage percentage triggering image GC.
         */
        imageGcHighThresholdPercent?: pulumi.Input<number>;
        /**
         * Disk usage percentage below which image GC stops.
         */
        imageGcLowThresholdPercent?: pulumi.Input<number>;
        /**
         * Maximum number of process IDs per pod.
         */
        podPidsLimit?: pulumi.Input<number>;
        /**
         * Topology manager policy for NUMA-aware scheduling.
         */
        topologyManagerPolicy?: pulumi.Input<string>;
    }

    export interface AzureNodeClassSpecArgsArgs {
        /**
         * FIPS compliance mode. One of: 'Enabled', 'Disabled'.
         */
        fipsMode?: pulumi.Input<string>;
        /**
         * Azure node image family (e.g. 'AzureLinux', 'Ubuntu2204').
         */
        imageFamily?: pulumi.Input<string>;
        /**
         * Kubelet configuration overrides for Azure nodes.
         */
        kubelet?: pulumi.Input<inputs.resources.AzureKubeletConfigurationArgsArgs>;
        /**
         * Maximum pods per node (overrides AKS default).
         */
        maxPods?: pulumi.Input<number>;
        /**
         * OS disk size in GB.
         */
        osDiskSizeGb?: pulumi.Input<number>;
        /**
         * Azure tags applied to all resources created by this node class.
         */
        tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * Azure VNet subnet resource ID for node networking.
         */
        vnetSubnetId?: pulumi.Input<string>;
    }

    export interface BlockDeviceArgsArgs {
        /**
         * Whether to delete the EBS volume when the instance terminates.
         */
        deleteOnTermination?: pulumi.Input<boolean>;
        /**
         * Whether to encrypt the EBS volume.
         */
        encrypted?: pulumi.Input<boolean>;
        /**
         * IOPS to provision for io1/io2 volume types.
         */
        iops?: pulumi.Input<number>;
        /**
         * KMS key ID or ARN used to encrypt the volume.
         */
        kmsKeyId?: pulumi.Input<string>;
        /**
         * EBS snapshot ID to restore the volume from.
         */
        snapshotId?: pulumi.Input<string>;
        /**
         * Throughput in MiB/s for gp3 volumes.
         */
        throughput?: pulumi.Input<number>;
        /**
         * Rate in MiB/s for initializing volumes from snapshots.
         */
        volumeInitializationRate?: pulumi.Input<number>;
        /**
         * Volume size (e.g. '20Gi').
         */
        volumeSize?: pulumi.Input<string>;
        /**
         * EBS volume type (e.g. 'gp3', 'io1', 'st1').
         */
        volumeType?: pulumi.Input<string>;
    }

    export interface BlockDeviceMappingArgsArgs {
        /**
         * Device name to map the volume to (e.g. '/dev/xvda').
         */
        deviceName?: pulumi.Input<string>;
        /**
         * EBS volume configuration for this device.
         */
        ebs?: pulumi.Input<inputs.resources.BlockDeviceArgsArgs>;
        /**
         * Whether this mapping is for the root volume.
         */
        rootVolume?: pulumi.Input<boolean>;
    }

    export interface CapacityReservationSelectorTermArgsArgs {
        /**
         * Explicit capacity reservation ID.
         */
        id?: pulumi.Input<string>;
        /**
         * AWS account ID that owns the capacity reservation.
         */
        ownerId?: pulumi.Input<string>;
        /**
         * Map of AWS tags used to select capacity reservations.
         */
        tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface DisruptionBudgetArgsArgs {
        /**
         * Duration the budget window stays active (e.g. '1h', '30m').
         */
        duration?: pulumi.Input<string>;
        /**
         * Maximum nodes that may be disrupted, as an absolute count or percentage (e.g. '10%').
         */
        nodes?: pulumi.Input<string>;
        /**
         * Disruption reasons this budget applies to (e.g. 'Underutilized', 'Empty', 'Drifted').
         */
        reasons?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * Cron schedule during which this budget is active (5-field format).
         */
        schedule?: pulumi.Input<string>;
    }

    export interface DisruptionPolicyArgsArgs {
        /**
         * Disruption budgets limiting how many nodes can be disrupted at once.
         */
        budgets?: pulumi.Input<pulumi.Input<inputs.resources.DisruptionBudgetArgsArgs>[]>;
        /**
         * Duration to wait after a node becomes empty before consolidating (e.g. '30s').
         */
        consolidateAfter?: pulumi.Input<string>;
        /**
         * When to consolidate nodes. One of: 'WhenEmpty', 'WhenUnderutilized'.
         */
        consolidationPolicy?: pulumi.Input<string>;
        /**
         * Duration after which provisioned nodes are replaced regardless of load (e.g. '720h').
         */
        expireAfter?: pulumi.Input<string>;
        /**
         * Grace period in seconds before forcefully terminating a draining node.
         */
        terminationGracePeriodSeconds?: pulumi.Input<number>;
        /**
         * Seconds before an empty node is terminated (deprecated; prefer ConsolidateAfter).
         */
        ttlSecondsAfterEmpty?: pulumi.Input<number>;
    }

    export interface HorizontalScalingArgsArgs {
        /**
         * Enable horizontal (replica) scaling.
         */
        enabled?: pulumi.Input<boolean>;
        /**
         * Maximum percentage change in replica count per recommendation cycle.
         */
        maxReplicaChangePercent?: pulumi.Input<number>;
        /**
         * Maximum number of replicas to scale up to.
         */
        maxReplicas?: pulumi.Input<number>;
        /**
         * Minimum data points required before a recommendation is emitted.
         */
        minDataPoints?: pulumi.Input<number>;
        /**
         * Minimum number of replicas to maintain.
         */
        minReplicas?: pulumi.Input<number>;
        /**
         * Primary metric for HPA decisions. One of: 'cpu', 'memory', 'gpu', 'network_ingress', 'network_egress'.
         */
        primaryMetric?: pulumi.Input<string>;
        /**
         * Target utilization ratio (0-1) for the primary metric.
         */
        targetUtilization?: pulumi.Input<number>;
    }

    export interface KubeletConfigurationArgsArgs {
        /**
         * List of DNS server IP addresses used by kubelet.
         */
        clusterDns?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * Whether to enforce CPU CFS quota limits for containers.
         */
        cpuCfsQuota?: pulumi.Input<boolean>;
        /**
         * Hard eviction thresholds that trigger immediate pod eviction.
         */
        evictionHard?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * Maximum grace period in seconds when evicting pods.
         */
        evictionMaxPodGracePeriod?: pulumi.Input<number>;
        /**
         * Soft eviction thresholds that trigger eviction after a grace period.
         */
        evictionSoft?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * Grace period for each soft eviction threshold.
         */
        evictionSoftGracePeriod?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * Disk usage percentage that triggers image garbage collection.
         */
        imageGcHighThresholdPercent?: pulumi.Input<number>;
        /**
         * Disk usage percentage below which image GC stops freeing space.
         */
        imageGcLowThresholdPercent?: pulumi.Input<number>;
        /**
         * Resources reserved for Kubernetes system components.
         */
        kubeReserved?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * Maximum number of pods per node.
         */
        maxPods?: pulumi.Input<number>;
        /**
         * Maximum pods per CPU core (multiplied by core count for max pods).
         */
        podsPerCore?: pulumi.Input<number>;
        /**
         * Resources reserved for OS system daemons (e.g. {'cpu': '100m'}).
         */
        systemReserved?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface LabelSelectorArgsArgs {
        /**
         * List of label selector requirements joined by AND.
         */
        matchExpressions?: pulumi.Input<pulumi.Input<inputs.resources.LabelSelectorRequirementArgsArgs>[]>;
        /**
         * Map of label key-value pairs that must all match exactly.
         */
        matchLabels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface LabelSelectorRequirementArgsArgs {
        /**
         * The label key that the selector applies to.
         */
        key?: pulumi.Input<string>;
        /**
         * Operator relating the key and values. One of: 'In', 'NotIn', 'Exists', 'DoesNotExist'.
         */
        operator?: pulumi.Input<string>;
        /**
         * Array of string values. Required for 'In' and 'NotIn' operators.
         */
        values?: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface MetadataOptionsArgsArgs {
        /**
         * Enable or disable the instance metadata endpoint. One of: 'enabled', 'disabled'.
         */
        httpEndpoint?: pulumi.Input<string>;
        /**
         * Enable IPv6 for the metadata endpoint. One of: 'enabled', 'disabled'.
         */
        httpProtocolIpv6?: pulumi.Input<string>;
        /**
         * HTTP PUT response hop limit for metadata requests (1-64).
         */
        httpPutResponseHopLimit?: pulumi.Input<number>;
        /**
         * Whether to require IMDSv2 tokens. One of: 'optional', 'required'.
         */
        httpTokens?: pulumi.Input<string>;
    }

    export interface NamePatternArgsArgs {
        /**
         * Optional regex flags (e.g. 'i' for case-insensitive).
         */
        flags?: pulumi.Input<string>;
        /**
         * Regular expression pattern to match workload names.
         */
        pattern?: pulumi.Input<string>;
    }

    export interface RawKarpenterSpecArgsArgs {
        /**
         * Raw YAML for a complete Karpenter NodeClass resource (escape hatch).
         */
        nodeclassYaml?: pulumi.Input<string>;
        /**
         * Raw YAML for a complete Karpenter NodePool resource (escape hatch).
         */
        nodepoolYaml?: pulumi.Input<string>;
    }

    export interface ResourceLimitsArgsArgs {
        /**
         * Maximum total CPU that may be provisioned (e.g. '1000' for 1000 vCPUs).
         */
        cpu?: pulumi.Input<string>;
        /**
         * Maximum total memory that may be provisioned (e.g. '1000Gi').
         */
        memory?: pulumi.Input<string>;
    }

    export interface SecurityGroupSelectorTermArgsArgs {
        /**
         * Explicit AWS security group ID.
         */
        id?: pulumi.Input<string>;
        /**
         * Security group name filter.
         */
        name?: pulumi.Input<string>;
        /**
         * Map of AWS tags used to select security groups.
         */
        tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface SubnetSelectorTermArgsArgs {
        /**
         * Explicit AWS subnet ID.
         */
        id?: pulumi.Input<string>;
        /**
         * Map of AWS tags used to select subnets.
         */
        tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    }

    export interface TaintArgsArgs {
        /**
         * Taint effect. One of: 'NoSchedule', 'PreferNoSchedule', 'NoExecute'.
         */
        effect: pulumi.Input<string>;
        /**
         * Taint key to apply to provisioned nodes.
         */
        key: pulumi.Input<string>;
        /**
         * Taint value associated with the key.
         */
        value?: pulumi.Input<string>;
    }

    export interface VerticalScalingArgsArgs {
        /**
         * Recommend requests even when the workload has no existing requests set. Server/web default: true.
         */
        adjustReqEvenIfNotSet?: pulumi.Input<boolean>;
        /**
         * Enable vertical scaling for this resource type.
         */
        enabled?: pulumi.Input<boolean>;
        /**
         * Multiplier applied to the request to derive the resource limit.
         */
        limitMultiplier?: pulumi.Input<number>;
        /**
         * Whether to also adjust resource limits alongside requests.
         */
        limitsAdjustmentEnabled?: pulumi.Input<boolean>;
        /**
         * Actively remove limits from workloads (CPU only). Takes precedence over limitsAdjustmentEnabled. Web default: true for CPU, false for Memory.
         */
        limitsRemovalEnabled?: pulumi.Input<boolean>;
        /**
         * Maximum resource request in millicores (CPU) or bytes (memory/GPU).
         */
        maxRequest?: pulumi.Input<number>;
        /**
         * Maximum percentage decrease allowed in a single recommendation cycle.
         */
        maxScaleDownPercent?: pulumi.Input<number>;
        /**
         * Maximum percentage increase allowed in a single recommendation cycle.
         */
        maxScaleUpPercent?: pulumi.Input<number>;
        /**
         * Minimum number of data points required before a recommendation is emitted.
         */
        minDataPoints?: pulumi.Input<number>;
        /**
         * Minimum resource request in millicores (CPU) or bytes (memory/GPU).
         */
        minRequest?: pulumi.Input<number>;
        /**
         * Multiplier applied on top of the recommendation to add headroom.
         */
        overheadMultiplier?: pulumi.Input<number>;
        /**
         * Percentile of usage data used as the recommendation target (e.g. 0.95).
         */
        targetPercentile?: pulumi.Input<number>;
    }
    /**
     * verticalScalingArgsArgsProvideDefaults sets the appropriate defaults for VerticalScalingArgsArgs
     */
    export function verticalScalingArgsArgsProvideDefaults(val: VerticalScalingArgsArgs): VerticalScalingArgsArgs {
        return {
            ...val,
            maxScaleDownPercent: (val.maxScaleDownPercent) ?? 1,
            maxScaleUpPercent: (val.maxScaleUpPercent) ?? 1000,
            minDataPoints: (val.minDataPoints) ?? 20,
        };
    }
}
