// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export namespace resources {
    export interface AMISelectorTermArgs {
        /**
         * Well-known alias for the AMI family (e.g. 'al2@latest').
         */
        alias?: string;
        /**
         * Explicit AMI ID.
         */
        id?: string;
        /**
         * AMI name filter (supports wildcards).
         */
        name?: string;
        /**
         * AWS account ID or alias that owns the AMI.
         */
        owner?: string;
        /**
         * SSM parameter path that stores the AMI ID.
         */
        ssmParameter?: string;
        /**
         * Map of AWS tags used to select AMIs.
         */
        tags?: {[key: string]: string};
    }

    export interface AWSNodeClassSpecArgs {
        /**
         * AMI family shorthand (e.g. 'AL2', 'Bottlerocket', 'Windows2022').
         */
        amiFamily?: string;
        /**
         * Selectors for the AMIs used to launch nodes.
         */
        amiSelectorTerms?: outputs.resources.AMISelectorTermArgs[];
        /**
         * Whether to assign a public IP address to provisioned nodes.
         */
        associatePublicIpAddress?: boolean;
        /**
         * EBS block device mappings for nodes.
         */
        blockDeviceMappings?: outputs.resources.BlockDeviceMappingArgs[];
        /**
         * Selectors for EC2 capacity reservations to prioritize.
         */
        capacityReservationSelectorTerms?: outputs.resources.CapacityReservationSelectorTermArgs[];
        /**
         * EC2 launch template context ARN.
         */
        context?: string;
        /**
         * Enable detailed CloudWatch monitoring for instances.
         */
        detailedMonitoring?: boolean;
        /**
         * IAM instance profile name (use instead of Role when profile already exists).
         */
        instanceProfile?: string;
        /**
         * Policy for handling instance store volumes. One of: 'RAID0'.
         */
        instanceStorePolicy?: string;
        /**
         * Kubelet configuration overrides for AWS nodes.
         */
        kubelet?: outputs.resources.KubeletConfigurationArgs;
        /**
         * EC2 instance metadata (IMDS) options.
         */
        metadataOptions?: outputs.resources.MetadataOptionsArgs;
        /**
         * IAM role name assigned to nodes.
         */
        role?: string;
        /**
         * Selectors for security groups attached to nodes.
         */
        securityGroupSelectorTerms?: outputs.resources.SecurityGroupSelectorTermArgs[];
        /**
         * Selectors for the subnets nodes will be launched into.
         */
        subnetSelectorTerms?: outputs.resources.SubnetSelectorTermArgs[];
        /**
         * AWS tags applied to all resources created by this node class.
         */
        tags?: {[key: string]: string};
        /**
         * Custom user data script injected into the node launch template.
         */
        userData?: string;
    }

    export interface AzureKubeletConfigurationArgs {
        /**
         * Unsafe sysctl patterns that are allowed (e.g. 'net.ipv4.*').
         */
        allowedUnsafeSysctls?: string[];
        /**
         * Maximum number of container log files to retain.
         */
        containerLogMaxFiles?: number;
        /**
         * Maximum container log file size before rotation (e.g. '10Mi').
         */
        containerLogMaxSize?: string;
        /**
         * Whether to enforce CPU CFS quota for containers.
         */
        cpuCfsQuota?: boolean;
        /**
         * CPU CFS quota period (e.g. '100ms').
         */
        cpuCfsQuotaPeriod?: string;
        /**
         * CPU manager policy. One of: 'none', 'static'.
         */
        cpuManagerPolicy?: string;
        /**
         * Disk usage percentage triggering image GC.
         */
        imageGcHighThresholdPercent?: number;
        /**
         * Disk usage percentage below which image GC stops.
         */
        imageGcLowThresholdPercent?: number;
        /**
         * Maximum number of process IDs per pod.
         */
        podPidsLimit?: number;
        /**
         * Topology manager policy for NUMA-aware scheduling.
         */
        topologyManagerPolicy?: string;
    }

    export interface AzureNodeClassSpecArgs {
        /**
         * FIPS compliance mode. One of: 'Enabled', 'Disabled'.
         */
        fipsMode?: string;
        /**
         * Azure node image family (e.g. 'AzureLinux', 'Ubuntu2204').
         */
        imageFamily?: string;
        /**
         * Kubelet configuration overrides for Azure nodes.
         */
        kubelet?: outputs.resources.AzureKubeletConfigurationArgs;
        /**
         * Maximum pods per node (overrides AKS default).
         */
        maxPods?: number;
        /**
         * OS disk size in GB.
         */
        osDiskSizeGb?: number;
        /**
         * Azure tags applied to all resources created by this node class.
         */
        tags?: {[key: string]: string};
        /**
         * Azure VNet subnet resource ID for node networking.
         */
        vnetSubnetId?: string;
    }

    export interface BlockDeviceArgs {
        /**
         * Whether to delete the EBS volume when the instance terminates.
         */
        deleteOnTermination?: boolean;
        /**
         * Whether to encrypt the EBS volume.
         */
        encrypted?: boolean;
        /**
         * IOPS to provision for io1/io2 volume types.
         */
        iops?: number;
        /**
         * KMS key ID or ARN used to encrypt the volume.
         */
        kmsKeyId?: string;
        /**
         * EBS snapshot ID to restore the volume from.
         */
        snapshotId?: string;
        /**
         * Throughput in MiB/s for gp3 volumes.
         */
        throughput?: number;
        /**
         * Rate in MiB/s for initializing volumes from snapshots.
         */
        volumeInitializationRate?: number;
        /**
         * Volume size (e.g. '20Gi').
         */
        volumeSize?: string;
        /**
         * EBS volume type (e.g. 'gp3', 'io1', 'st1').
         */
        volumeType?: string;
    }

    export interface BlockDeviceMappingArgs {
        /**
         * Device name to map the volume to (e.g. '/dev/xvda').
         */
        deviceName?: string;
        /**
         * EBS volume configuration for this device.
         */
        ebs?: outputs.resources.BlockDeviceArgs;
        /**
         * Whether this mapping is for the root volume.
         */
        rootVolume?: boolean;
    }

    export interface CapacityReservationSelectorTermArgs {
        /**
         * Explicit capacity reservation ID.
         */
        id?: string;
        /**
         * AWS account ID that owns the capacity reservation.
         */
        ownerId?: string;
        /**
         * Map of AWS tags used to select capacity reservations.
         */
        tags?: {[key: string]: string};
    }

    export interface DisruptionBudgetArgs {
        /**
         * Duration the budget window stays active (e.g. '1h', '30m').
         */
        duration?: string;
        /**
         * Maximum nodes that may be disrupted, as an absolute count or percentage (e.g. '10%').
         */
        nodes?: string;
        /**
         * Disruption reasons this budget applies to (e.g. 'Underutilized', 'Empty', 'Drifted').
         */
        reasons?: string[];
        /**
         * Cron schedule during which this budget is active (5-field format).
         */
        schedule?: string;
    }

    export interface DisruptionPolicyArgs {
        /**
         * Disruption budgets limiting how many nodes can be disrupted at once.
         */
        budgets?: outputs.resources.DisruptionBudgetArgs[];
        /**
         * Duration to wait after a node becomes empty before consolidating (e.g. '30s').
         */
        consolidateAfter?: string;
        /**
         * When to consolidate nodes. One of: 'WhenEmpty', 'WhenUnderutilized'.
         */
        consolidationPolicy?: string;
        /**
         * Duration after which provisioned nodes are replaced regardless of load (e.g. '720h').
         */
        expireAfter?: string;
        /**
         * Grace period in seconds before forcefully terminating a draining node.
         */
        terminationGracePeriodSeconds?: number;
        /**
         * Seconds before an empty node is terminated (deprecated; prefer ConsolidateAfter).
         */
        ttlSecondsAfterEmpty?: number;
    }

    export interface HorizontalScalingArgs {
        /**
         * Enable horizontal (replica) scaling.
         */
        enabled?: boolean;
        /**
         * Maximum percentage change in replica count per recommendation cycle.
         */
        maxReplicaChangePercent?: number;
        /**
         * Maximum number of replicas to scale up to.
         */
        maxReplicas?: number;
        /**
         * Minimum data points required before a recommendation is emitted.
         */
        minDataPoints?: number;
        /**
         * Minimum number of replicas to maintain.
         */
        minReplicas?: number;
        /**
         * Primary metric for HPA decisions. One of: 'cpu', 'memory', 'gpu', 'network_ingress', 'network_egress'.
         */
        primaryMetric?: string;
        /**
         * Target utilization ratio (0-1) for the primary metric.
         */
        targetUtilization?: number;
    }

    export interface KubeletConfigurationArgs {
        /**
         * List of DNS server IP addresses used by kubelet.
         */
        clusterDns?: string[];
        /**
         * Whether to enforce CPU CFS quota limits for containers.
         */
        cpuCfsQuota?: boolean;
        /**
         * Hard eviction thresholds that trigger immediate pod eviction.
         */
        evictionHard?: {[key: string]: string};
        /**
         * Maximum grace period in seconds when evicting pods.
         */
        evictionMaxPodGracePeriod?: number;
        /**
         * Soft eviction thresholds that trigger eviction after a grace period.
         */
        evictionSoft?: {[key: string]: string};
        /**
         * Grace period for each soft eviction threshold.
         */
        evictionSoftGracePeriod?: {[key: string]: string};
        /**
         * Disk usage percentage that triggers image garbage collection.
         */
        imageGcHighThresholdPercent?: number;
        /**
         * Disk usage percentage below which image GC stops freeing space.
         */
        imageGcLowThresholdPercent?: number;
        /**
         * Resources reserved for Kubernetes system components.
         */
        kubeReserved?: {[key: string]: string};
        /**
         * Maximum number of pods per node.
         */
        maxPods?: number;
        /**
         * Maximum pods per CPU core (multiplied by core count for max pods).
         */
        podsPerCore?: number;
        /**
         * Resources reserved for OS system daemons (e.g. {'cpu': '100m'}).
         */
        systemReserved?: {[key: string]: string};
    }

    export interface LabelSelectorArgs {
        /**
         * List of label selector requirements joined by AND.
         */
        matchExpressions?: outputs.resources.LabelSelectorRequirementArgs[];
        /**
         * Map of label key-value pairs that must all match exactly.
         */
        matchLabels?: {[key: string]: string};
    }

    export interface LabelSelectorRequirementArgs {
        /**
         * The label key that the selector applies to.
         */
        key?: string;
        /**
         * Operator relating the key and values. One of: 'In', 'NotIn', 'Exists', 'DoesNotExist'.
         */
        operator?: string;
        /**
         * Array of string values. Required for 'In' and 'NotIn' operators.
         */
        values?: string[];
    }

    export interface MetadataOptionsArgs {
        /**
         * Enable or disable the instance metadata endpoint. One of: 'enabled', 'disabled'.
         */
        httpEndpoint?: string;
        /**
         * Enable IPv6 for the metadata endpoint. One of: 'enabled', 'disabled'.
         */
        httpProtocolIpv6?: string;
        /**
         * HTTP PUT response hop limit for metadata requests (1-64).
         */
        httpPutResponseHopLimit?: number;
        /**
         * Whether to require IMDSv2 tokens. One of: 'optional', 'required'.
         */
        httpTokens?: string;
    }

    export interface NamePatternArgs {
        /**
         * Optional regex flags (e.g. 'i' for case-insensitive).
         */
        flags?: string;
        /**
         * Regular expression pattern to match workload names.
         */
        pattern?: string;
    }

    export interface RawKarpenterSpecArgs {
        /**
         * Raw YAML for a complete Karpenter NodeClass resource (escape hatch).
         */
        nodeclassYaml?: string;
        /**
         * Raw YAML for a complete Karpenter NodePool resource (escape hatch).
         */
        nodepoolYaml?: string;
    }

    export interface ResourceLimitsArgs {
        /**
         * Maximum total CPU that may be provisioned (e.g. '1000' for 1000 vCPUs).
         */
        cpu?: string;
        /**
         * Maximum total memory that may be provisioned (e.g. '1000Gi').
         */
        memory?: string;
    }

    export interface SecurityGroupSelectorTermArgs {
        /**
         * Explicit AWS security group ID.
         */
        id?: string;
        /**
         * Security group name filter.
         */
        name?: string;
        /**
         * Map of AWS tags used to select security groups.
         */
        tags?: {[key: string]: string};
    }

    export interface SubnetSelectorTermArgs {
        /**
         * Explicit AWS subnet ID.
         */
        id?: string;
        /**
         * Map of AWS tags used to select subnets.
         */
        tags?: {[key: string]: string};
    }

    export interface TaintArgs {
        /**
         * Taint effect. One of: 'NoSchedule', 'PreferNoSchedule', 'NoExecute'.
         */
        effect: string;
        /**
         * Taint key to apply to provisioned nodes.
         */
        key: string;
        /**
         * Taint value associated with the key.
         */
        value?: string;
    }

    export interface VerticalScalingArgs {
        /**
         * Recommend requests even when the workload has no existing requests set. Server/web default: true.
         */
        adjustReqEvenIfNotSet?: boolean;
        /**
         * Enable vertical scaling for this resource type.
         */
        enabled?: boolean;
        /**
         * Multiplier applied to the request to derive the resource limit.
         */
        limitMultiplier?: number;
        /**
         * Whether to also adjust resource limits alongside requests.
         */
        limitsAdjustmentEnabled?: boolean;
        /**
         * Actively remove limits from workloads (CPU only). Takes precedence over limitsAdjustmentEnabled. Web default: true for CPU, false for Memory.
         */
        limitsRemovalEnabled?: boolean;
        /**
         * Maximum resource request in millicores (CPU) or bytes (memory/GPU).
         */
        maxRequest?: number;
        /**
         * Maximum percentage decrease allowed in a single recommendation cycle.
         */
        maxScaleDownPercent?: number;
        /**
         * Maximum percentage increase allowed in a single recommendation cycle.
         */
        maxScaleUpPercent?: number;
        /**
         * Minimum number of data points required before a recommendation is emitted.
         */
        minDataPoints?: number;
        /**
         * Minimum resource request in millicores (CPU) or bytes (memory/GPU).
         */
        minRequest?: number;
        /**
         * Multiplier applied on top of the recommendation to add headroom.
         */
        overheadMultiplier?: number;
        /**
         * Percentile of usage data used as the recommendation target (e.g. 0.95).
         */
        targetPercentile?: number;
    }
    /**
     * verticalScalingArgsProvideDefaults sets the appropriate defaults for VerticalScalingArgs
     */
    export function verticalScalingArgsProvideDefaults(val: VerticalScalingArgs): VerticalScalingArgs {
        return {
            ...val,
            maxScaleDownPercent: (val.maxScaleDownPercent) ?? 1,
            maxScaleUpPercent: (val.maxScaleUpPercent) ?? 1000,
            minDataPoints: (val.minDataPoints) ?? 20,
        };
    }

}
